USE smartlink;

CREATE TABLE IF NOT EXISTS user_preferences (
  user_id BIGINT UNSIGNED PRIMARY KEY,
  theme ENUM('SYSTEM','LIGHT','DARK') NOT NULL DEFAULT 'SYSTEM',
  default_report_range ENUM('TODAY','LAST_7_DAYS','LAST_30_DAYS') NOT NULL DEFAULT 'LAST_7_DAYS',
  default_fuel_type ENUM('ALL','PETROL','DIESEL') NOT NULL DEFAULT 'ALL',
  notify_in_app TINYINT(1) NOT NULL DEFAULT 1,
  notify_email TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_user_preferences_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
