ALTER TABLE user_passkey_challenges
  MODIFY COLUMN expires_at DATETIME(3) NOT NULL,
  MODIFY COLUMN used_at DATETIME(3) NULL,
  MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
