package com.example.smartlink.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.selection.selectable
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.example.smartlink.domain.model.StudentPortal
import com.example.smartlink.domain.model.DailyDrill
import com.example.smartlink.ui.components.*
import com.example.smartlink.ui.theme.SmartLinkSpacing

@Composable fun StudentHomeScreen(portal: StudentPortal, onRefresh: () -> Unit) = LazyColumn(Modifier.fillMaxSize().padding(SmartLinkSpacing.page), verticalArrangement = Arrangement.spacedBy(SmartLinkSpacing.section)) {
    item { SmartLinkSectionHeader("Hello, ${portal.profile.fullName.substringBefore(" ")}", portal.profile.className, action = { IconButton(onClick = onRefresh) { Icon(Icons.Default.Refresh, "Refresh") } }) }
    item { Surface(color = MaterialTheme.colorScheme.primary, shape = MaterialTheme.shapes.medium) { Column(Modifier.padding(20.dp)) { Text("SMARTLINK SCHOOLS", color = MaterialTheme.colorScheme.secondary, style = MaterialTheme.typography.labelSmall, fontWeight = FontWeight.Bold); Text("Your learning space", color = MaterialTheme.colorScheme.onPrimary, style = MaterialTheme.typography.headlineSmall, modifier = Modifier.padding(top = 8.dp)); Text("Progress, homework and school updates in one place.", color = MaterialTheme.colorScheme.onPrimary.copy(alpha = .78f), modifier = Modifier.padding(top = 6.dp)) } } }
    item { SmartLinkSectionHeader("My progress", "This term") }
    item { Column(verticalArrangement = Arrangement.spacedBy(12.dp)) { portal.metrics.chunked(2).forEach { row -> Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) { row.forEachIndexed { index, metric -> SmartLinkStatCard(metric.label, metric.value, if (index == 0) Icons.Default.BarChart else Icons.Default.FactCheck, Modifier.weight(1f)) }; if (row.size == 1) Spacer(Modifier.weight(1f)) } } } }
    item { SmartLinkDashboardCard("Stay on track", "Open Learning for homework and practice, or Timetable for today’s lessons.") { Text("Your school publishes updates here as they become available.", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant) } }
}
@Composable fun StudentResultsScreen(portal: StudentPortal, onDownloadReport: (String) -> Unit) = Column(Modifier.fillMaxSize().padding(SmartLinkSpacing.page)) { SmartLinkSectionHeader("Academic results", "Published results and assessment feedback"); portal.latestReport?.let { report -> SmartLinkDashboardCard(report.title, "Average ${report.average.ifBlank { "—" }} · Position ${report.position.ifBlank { "—" }}") { Button(onClick = { onDownloadReport(report.id) }, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Default.PictureAsPdf, null); Spacer(Modifier.width(8.dp)); Text("Open report PDF") } } }; Spacer(Modifier.height(14.dp)); if (portal.results.isEmpty()) SmartLinkEmptyState("No published results yet.") else LazyColumn(verticalArrangement = Arrangement.spacedBy(10.dp)) { items(portal.results) { SmartLinkListItem(it.title, it.detail, it.status, Icons.Default.MenuBook) } } }
@Composable fun StudentLearningScreen(portal: StudentPortal) = StudentListScreen("Learning", "Homework and daily learning activities", portal.homework, Icons.Default.Assignment, "No homework is due right now.")
@Composable fun StudentTimetableScreen(portal: StudentPortal) = StudentListScreen("Timetable", "Your school schedule", portal.timetable, Icons.Default.Schedule, "Your timetable will appear here.")
@Composable fun StudentDrillScreen(drill: DailyDrill?, loading: Boolean, onLoad: () -> Unit, onSave: (String, String) -> Unit, onSubmit: () -> Unit) = Column(Modifier.fillMaxSize().padding(SmartLinkSpacing.page)) { SmartLinkSectionHeader("Daily drills", "Personalised practice from your learning topics", action = { IconButton(onClick = onLoad) { Icon(Icons.Default.Refresh, "Refresh") } }); Spacer(Modifier.height(14.dp)); if (loading && drill == null) { SmartLinkLoadingState() } else if (drill == null) { SmartLinkEmptyState("Daily practice will appear when approved questions are available.") } else { SmartLinkDashboardCard(drill.subject, drill.topic) { Text(if (drill.status == "completed") "Completed: ${drill.percentage.ifBlank { "—" }}%" else "${drill.questions.size} questions ready") }; Spacer(Modifier.height(12.dp)); LazyColumn(verticalArrangement = Arrangement.spacedBy(10.dp), modifier = Modifier.weight(1f)) { items(drill.questions) { question -> var answer by remember(question.sessionQuestionId) { mutableStateOf(question.savedAnswer) }; SmartLinkDashboardCard(question.text, "${question.type.replace('_', ' ')}") { if (question.options.isNotEmpty()) question.options.forEach { option -> Row(Modifier.fillMaxWidth().selectable(answer == option) { answer = option; onSave(question.sessionQuestionId, option) }.padding(vertical = 6.dp), verticalAlignment = Alignment.CenterVertically) { RadioButton(answer == option, null); Text(option, modifier = Modifier.padding(start = 6.dp)) } } else { OutlinedTextField(answer, { answer = it }, label = { Text("Your answer") }, modifier = Modifier.fillMaxWidth()); Button(onClick = { onSave(question.sessionQuestionId, answer) }, enabled = answer.isNotBlank() && drill.status != "completed", modifier = Modifier.padding(top = 8.dp)) { Text("Save answer") } } } } }; if (drill.status != "completed") Button(onClick = onSubmit, enabled = drill.questions.isNotEmpty() && !loading, modifier = Modifier.fillMaxWidth().padding(top = 12.dp)) { Text("Submit drill") } } }
@Composable fun StudentNoticesScreen(portal: StudentPortal, onReact: (String, String) -> Unit) = Column(Modifier.fillMaxSize().padding(SmartLinkSpacing.page)) { SmartLinkSectionHeader("Notices", "School announcements and updates"); Spacer(Modifier.height(16.dp)); if (portal.announcements.isEmpty()) SmartLinkEmptyState("No announcements are available.") else LazyColumn(verticalArrangement = Arrangement.spacedBy(10.dp)) { items(portal.announcements) { item -> SmartLinkDashboardCard(item.title, item.date) { Text(item.body); Row(Modifier.padding(top = 10.dp), horizontalArrangement = Arrangement.spacedBy(6.dp)) { item.reactions.forEach { reaction -> FilterChip(selected = reaction == item.myReaction, onClick = { onReact(item.id, reaction) }, label = { Text(reaction) }) } } } } } }
@Composable private fun StudentListScreen(title: String, subtitle: String, items: List<com.example.smartlink.domain.model.SchoolListItem>, icon: androidx.compose.ui.graphics.vector.ImageVector, empty: String) = Column(Modifier.fillMaxSize().padding(SmartLinkSpacing.page)) { SmartLinkSectionHeader(title, subtitle); Spacer(Modifier.height(16.dp)); if (items.isEmpty()) SmartLinkEmptyState(empty) else LazyColumn(verticalArrangement = Arrangement.spacedBy(10.dp)) { items(items) { SmartLinkListItem(it.title, it.detail, it.status, icon) } } }
@Composable fun StudentProfileScreen(portal: StudentPortal, onSignOut: () -> Unit) = Column(Modifier.fillMaxSize().padding(SmartLinkSpacing.page)) { SmartLinkSectionHeader("My profile", "Your school identity"); Spacer(Modifier.height(18.dp)); SmartLinkDashboardCard(portal.profile.fullName, portal.profile.className) { Text("Admission no. ${portal.profile.admissionNumber.ifBlank { "Not recorded" }}", style = MaterialTheme.typography.bodyMedium) }; Spacer(Modifier.height(18.dp)); OutlinedButton(onClick = onSignOut, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Default.Logout, null); Spacer(Modifier.width(8.dp)); Text("Sign out") } }
