import { APP_TIME_ZONE } from '../dateTime'

function toMoneyNumber(value) {
  const numeric = Number(value)
  if (!Number.isFinite(numeric)) return null
  return Number(numeric.toFixed(2))
}

function formatMoney(amount, currencyCode = 'MWK') {
  const normalized = toMoneyNumber(amount)
  if (normalized === null) return `${currencyCode} -`
  const isWhole = Math.abs(normalized % 1) < 0.001
  return `${currencyCode} ${normalized.toLocaleString(undefined, {
    minimumFractionDigits: isWhole ? 0 : 2,
    maximumFractionDigits: 2,
  })}`
}

function formatOptionalMoney(amount, currencyCode = 'MWK', fallback = '-') {
  const normalized = toMoneyNumber(amount)
  if (normalized === null) return fallback
  return formatMoney(normalized, currencyCode)
}

function formatTextValue(value, fallback = '-') {
  const normalized = String(value ?? '').trim()
  return normalized || fallback
}

function formatPumpLabel(pumpNumber, fallback = '-') {
  const numeric = Number(pumpNumber)
  if (!Number.isFinite(numeric) || numeric <= 0) return fallback
  return `Pump ${numeric}`
}

function formatDateTime(value, fallback = '-') {
  if (!value) return fallback
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return fallback
  return date.toLocaleString(undefined, {
    weekday: 'short',
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZone: APP_TIME_ZONE,
  })
}

function sanitizeToken(value, fallback = 'receipt') {
  const normalized = String(value || '')
    .trim()
    .replace(/[^a-zA-Z0-9_-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
  return normalized || fallback
}

function escapePdfText(value) {
  return String(value ?? '')
    .replace(/[^\x20-\x7E]/g, '?')
    .replaceAll('\\', '\\\\')
    .replaceAll('(', '\\(')
    .replaceAll(')', '\\)')
}

function wrapText(value, maxChars = 58) {
  const text = String(value ?? '').trim()
  if (!text) return ['-']

  const words = text.split(/\s+/)
  const lines = []
  let current = ''

  for (const word of words) {
    if (word.length > maxChars) {
      if (current) {
        lines.push(current)
        current = ''
      }
      for (let index = 0; index < word.length; index += maxChars) {
        lines.push(word.slice(index, index + maxChars))
      }
      continue
    }

    const next = current ? `${current} ${word}` : word
    if (next.length > maxChars) {
      lines.push(current)
      current = word
    } else {
      current = next
    }
  }

  if (current) lines.push(current)
  return lines.length ? lines : ['-']
}

function buildReceiptLines(receipt) {
  return [
    `SmartPay`,
    `${receipt.title || 'Payment Receipt'}`,
    `${receipt.subtitle || 'Digital payment confirmation'}`,
    '',
    `Transaction ID: ${receipt.transactionId || '-'}`,
    `Receipt Reference: ${receipt.reference || '-'}`,
    `Payment Method: ${receipt.paymentMethod || 'SmartPay'}`,
    `Payment Status: ${receipt.paymentStatus || 'PAID'}`,
    '',
    `Station: ${receipt.stationName || '-'}`,
    `Location: ${receipt.stationArea || '-'}`,
    `Service: ${receipt.serviceLabel || '-'}`,
    `Fuel Type: ${receipt.fuelType || '-'}`,
    `Volume: ${receipt.volumeLabel || '-'}`,
    `Unit Price: ${formatMoney(receipt.pricePerLitre, receipt.currencyCode)}`,
    `Promotion Campaign: ${formatTextValue(receipt.promotionLabel)}`,
    `Promotion Type: ${formatTextValue(receipt.promotionType)}`,
    `Promotion Value: ${formatTextValue(receipt.promotionValueLabel)}`,
    `Discount Amount: ${formatOptionalMoney(receipt.discountAmount, receipt.currencyCode)}`,
    `Cashback Amount: ${formatOptionalMoney(receipt.cashbackAmount, receipt.currencyCode)}`,
    `Total Paid: ${formatMoney(receipt.totalAmount, receipt.currencyCode)}`,
    `Pump: ${formatPumpLabel(receipt.pumpNumber)}`,
    `Nozzle: ${formatTextValue(receipt.nozzleLabel)}`,
    `Completed At: ${formatDateTime(receipt.completedAt)}`,
    `Generated At: ${formatDateTime(receipt.generatedAt)}`,
    '',
    'Generated by SmartPay. This Receipt confirms the recorded digital payment for the completed service.',
  ]
}

function buildPdfBlob(receipt) {
  const lines = buildReceiptLines(receipt)
    .flatMap((line) => wrapText(line))

  const pageHeight = 842
  const startY = 790
  const lineHeight = 18
  const commands = [
    'BT',
    '/F1 12 Tf',
    '14 TL',
  ]

  let currentY = startY
  for (const line of lines) {
    if (currentY < 60) break
    commands.push(`1 0 0 1 52 ${currentY} Tm (${escapePdfText(line)}) Tj`)
    currentY -= lineHeight
  }
  commands.push('ET')

  const contentStream = commands.join('\n')
  const contentLength = new TextEncoder().encode(contentStream).length

  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Count 1 /Kids [3 0 R] >> endobj',
    `3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 ${pageHeight}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj`,
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    `5 0 obj << /Length ${contentLength} >> stream\n${contentStream}\nendstream endobj`,
  ]

  let pdf = '%PDF-1.4\n'
  const offsets = []
  for (const object of objects) {
    offsets.push(pdf.length)
    pdf += `${object}\n`
  }

  const xrefOffset = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n`
  pdf += '0000000000 65535 f \n'
  for (const offset of offsets) {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  return new Blob([pdf], { type: 'application/pdf' })
}

export function downloadBlobFile(blob, filename = 'smartpay-receipt.pdf') {
  if (typeof window === 'undefined' || typeof document === 'undefined') {
    throw new Error('Receipt downloads are available only in the browser.')
  }
  if (!(blob instanceof Blob)) {
    throw new Error('A PDF file is required for download.')
  }

  const safeFilename = sanitizeToken(filename, 'smartpay-receipt')
  const finalFilename = safeFilename.toLowerCase().endsWith('.pdf') ? safeFilename : `${safeFilename}.pdf`
  const url = window.URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = finalFilename
  document.body.appendChild(link)
  link.click()
  link.remove()
  window.setTimeout(() => {
    window.URL.revokeObjectURL(url)
  }, 0)
}

export function downloadSmartPayReceipt(receipt) {
  const normalizedReceipt = {
    systemName: 'SmartPay',
    currencyCode: 'MWK',
    paymentMethod: 'SmartPay',
    paymentStatus: 'PAID',
    generatedAt: new Date().toISOString(),
    ...receipt,
  }

  const blob = buildPdfBlob(normalizedReceipt)
  const filename = `smartpay-receipt-${sanitizeToken(
    normalizedReceipt.reference || normalizedReceipt.transactionId || normalizedReceipt.title,
    'receipt',
  )}.pdf`
  downloadBlobFile(blob, filename)
}
