export const INTERNAL_ROLE_CODES = {
  PLATFORM_OWNER: "PLATFORM_OWNER",
  NETWORK_OPERATIONS_MANAGER: "NETWORK_OPERATIONS_MANAGER",
  STATION_ONBOARDING_MANAGER: "STATION_ONBOARDING_MANAGER",
  FIELD_AGENT: "FIELD_AGENT",
  CUSTOMER_SUPPORT_AGENT: "CUSTOMER_SUPPORT_AGENT",
  FINANCE_MANAGER: "FINANCE_MANAGER",
  RISK_COMPLIANCE_OFFICER: "RISK_COMPLIANCE_OFFICER",
  DATA_ANALYST: "DATA_ANALYST",
  SOFTWARE_DEVELOPER: "SOFTWARE_DEVELOPER",
  PLATFORM_INFRASTRUCTURE_ENGINEER: "PLATFORM_INFRASTRUCTURE_ENGINEER",
}

export const INTERNAL_PERMISSIONS = {
  OVERVIEW_VIEW: "overview:view",
  CHAT_VIEW: "chat:view",
  CHAT_SEND: "chat:send",
  CHAT_PIN: "chat:pin",
  NETWORK_VIEW: "network:view",
  NETWORK_INCIDENT_MANAGE: "network:incident_manage",
  NETWORK_STATION_ACTION: "network:station_action",
  NETWORK_EXPORT: "network:export",
  STATIONS_VIEW: "stations:view",
  STATIONS_ACTIVATE: "stations:activate",
  STATIONS_CONFIGURE: "stations:configure",
  ONBOARDING_VIEW: "onboarding:view",
  ONBOARDING_MANAGE: "onboarding:manage",
  FIELD_VIEW: "field:view",
  FIELD_MANAGE: "field:manage",
  SUPPORT_VIEW: "support:view",
  SUPPORT_RESOLVE: "support:resolve",
  SUPPORT_ESCALATE: "support:escalate",
  SUPPORT_REFUND_LIMITED: "support:refund_limited",
  FINANCE_VIEW: "finance:view",
  FINANCE_SETTLE: "finance:settle",
  FINANCE_SETTLEMENT_REJECT: "finance:settlement_reject",
  FINANCE_REFUND_APPROVE: "finance:refund_approve",
  RISK_VIEW: "risk:view",
  RISK_FREEZE: "risk:freeze",
  RISK_UNFREEZE: "risk:unfreeze",
  ANALYTICS_VIEW: "analytics:view",
  ANALYTICS_EXPORT: "analytics:export",
  AUDIT_VIEW: "audit:view",
  AUDIT_EXPORT: "audit:export",
  STAFF_VIEW: "staff:view",
  STAFF_MANAGE: "staff:manage",
  STAFF_CREATE: "staff:create",
  STAFF_SUSPEND: "staff:suspend",
  STAFF_RESET_ACCESS: "staff:reset_access",
  PERMISSIONS_VIEW_MATRIX: "permissions:view_matrix",
  SYSTEM_HEALTH_VIEW: "system_health:view",
  ENGINEERING_LOGS_VIEW: "engineering.logs:view",
  SETTINGS_VIEW: "settings:view",
  SETTINGS_EDIT: "settings:edit",
  SECURITY_OVERRIDE: "security:override",
  SECURITY_FORCE_SIGN_OUT: "security:force_sign_out",
  SECURITY_LOCK_ACCOUNT: "security:lock_account",
  SECURITY_EVENT_DETAIL: "security:event_detail",
  RISK_OVERRIDE_APPROVE: "risk:override_approve",
  WALLET_LOOKUP: "wallet.lookup",
  WALLET_BALANCE_VIEW: "wallet.balance.view",
  WALLET_TRANSACTIONS_VIEW: "wallet.transactions.view",
  WALLET_POINTS_VIEW: "wallet.points.view",
  WALLET_POINTS_ADJUST: "wallet.points.adjust",
  WALLET_REFUND_REQUEST: "wallet.refund.request",
  WALLET_WALLET_CREDIT_ISSUE: "wallet.wallet_credit.issue",
  WALLET_LEDGER_ADJUST: "wallet.ledger.adjust",
  WALLET_BALANCE_TRANSFER: "wallet.balance.transfer",
  WALLET_AUDIT_VIEW: "wallet.audit.view",
  WALLET_FREEZE: "wallet.freeze",
  WALLET_UNFREEZE: "wallet.unfreeze",
  WALLET_REVIEW_MARK: "wallet.review.mark",
  WALLET_STATEMENT_EXPORT: "wallet.statement.export",
  WALLET_HOLD_PLACE: "wallet.hold.place",
  WALLET_HOLD_RELEASE: "wallet.hold.release",
}

export const SUPPORT_AGENT_WALLET_PERMISSIONS = [
  INTERNAL_PERMISSIONS.WALLET_LOOKUP,
  INTERNAL_PERMISSIONS.WALLET_BALANCE_VIEW,
  INTERNAL_PERMISSIONS.WALLET_TRANSACTIONS_VIEW,
  INTERNAL_PERMISSIONS.WALLET_POINTS_VIEW,
]

export const SENIOR_SUPPORT_WALLET_PERMISSIONS = [
  ...SUPPORT_AGENT_WALLET_PERMISSIONS,
  INTERNAL_PERMISSIONS.WALLET_POINTS_ADJUST,
  INTERNAL_PERMISSIONS.WALLET_REFUND_REQUEST,
  INTERNAL_PERMISSIONS.WALLET_WALLET_CREDIT_ISSUE,
  INTERNAL_PERMISSIONS.WALLET_AUDIT_VIEW,
  INTERNAL_PERMISSIONS.WALLET_REVIEW_MARK,
  INTERNAL_PERMISSIONS.WALLET_STATEMENT_EXPORT,
  INTERNAL_PERMISSIONS.WALLET_FREEZE,
  INTERNAL_PERMISSIONS.WALLET_UNFREEZE,
]

export const ADMIN_WALLET_PERMISSIONS = [
  ...SENIOR_SUPPORT_WALLET_PERMISSIONS,
  INTERNAL_PERMISSIONS.WALLET_LEDGER_ADJUST,
  INTERNAL_PERMISSIONS.WALLET_BALANCE_TRANSFER,
  INTERNAL_PERMISSIONS.WALLET_HOLD_PLACE,
  INTERNAL_PERMISSIONS.WALLET_HOLD_RELEASE,
]

export const PLATFORM_OWNER_RESTRICTED_PERMISSIONS = [
  INTERNAL_PERMISSIONS.SUPPORT_RESOLVE,
  INTERNAL_PERMISSIONS.SUPPORT_REFUND_LIMITED,
  INTERNAL_PERMISSIONS.FINANCE_SETTLE,
  INTERNAL_PERMISSIONS.FINANCE_REFUND_APPROVE,
]

export const NETWORK_OPERATIONS_MANAGER_DEFAULT_PERMISSIONS = [
  INTERNAL_PERMISSIONS.CHAT_VIEW,
  INTERNAL_PERMISSIONS.CHAT_SEND,
  INTERNAL_PERMISSIONS.NETWORK_INCIDENT_MANAGE,
  INTERNAL_PERMISSIONS.NETWORK_STATION_ACTION,
  INTERNAL_PERMISSIONS.NETWORK_EXPORT,
]

export const STATION_ONBOARDING_MANAGER_DEFAULT_PERMISSIONS = [
  INTERNAL_PERMISSIONS.CHAT_VIEW,
  INTERNAL_PERMISSIONS.CHAT_SEND,
  INTERNAL_PERMISSIONS.OVERVIEW_VIEW,
  INTERNAL_PERMISSIONS.STATIONS_VIEW,
  INTERNAL_PERMISSIONS.STATIONS_ACTIVATE,
  INTERNAL_PERMISSIONS.STATIONS_CONFIGURE,
  INTERNAL_PERMISSIONS.ONBOARDING_VIEW,
  INTERNAL_PERMISSIONS.ONBOARDING_MANAGE,
  INTERNAL_PERMISSIONS.FIELD_VIEW,
  INTERNAL_PERMISSIONS.FIELD_MANAGE,
]

export const FIELD_AGENT_DEFAULT_PERMISSIONS = [
  INTERNAL_PERMISSIONS.CHAT_VIEW,
  INTERNAL_PERMISSIONS.CHAT_SEND,
  INTERNAL_PERMISSIONS.STATIONS_VIEW,
  INTERNAL_PERMISSIONS.ONBOARDING_VIEW,
  INTERNAL_PERMISSIONS.FIELD_VIEW,
  INTERNAL_PERMISSIONS.FIELD_MANAGE,
]

export const CUSTOMER_SUPPORT_AGENT_DEFAULT_PERMISSIONS = [
  INTERNAL_PERMISSIONS.CHAT_VIEW,
  INTERNAL_PERMISSIONS.CHAT_SEND,
  INTERNAL_PERMISSIONS.OVERVIEW_VIEW,
  INTERNAL_PERMISSIONS.STATIONS_VIEW,
  INTERNAL_PERMISSIONS.SUPPORT_VIEW,
  INTERNAL_PERMISSIONS.SUPPORT_RESOLVE,
  INTERNAL_PERMISSIONS.SUPPORT_ESCALATE,
  INTERNAL_PERMISSIONS.SUPPORT_REFUND_LIMITED,
  ...SUPPORT_AGENT_WALLET_PERMISSIONS,
]

export const FINANCE_MANAGER_DEFAULT_PERMISSIONS = [
  INTERNAL_PERMISSIONS.CHAT_VIEW,
  INTERNAL_PERMISSIONS.CHAT_SEND,
  INTERNAL_PERMISSIONS.OVERVIEW_VIEW,
  INTERNAL_PERMISSIONS.FINANCE_VIEW,
  INTERNAL_PERMISSIONS.FINANCE_SETTLE,
  INTERNAL_PERMISSIONS.FINANCE_SETTLEMENT_REJECT,
  INTERNAL_PERMISSIONS.FINANCE_REFUND_APPROVE,
  INTERNAL_PERMISSIONS.AUDIT_VIEW,
  ...SENIOR_SUPPORT_WALLET_PERMISSIONS,
]

export const RISK_COMPLIANCE_OFFICER_DEFAULT_PERMISSIONS = [
  INTERNAL_PERMISSIONS.CHAT_VIEW,
  INTERNAL_PERMISSIONS.CHAT_SEND,
  INTERNAL_PERMISSIONS.OVERVIEW_VIEW,
  INTERNAL_PERMISSIONS.RISK_VIEW,
  INTERNAL_PERMISSIONS.RISK_FREEZE,
  INTERNAL_PERMISSIONS.RISK_UNFREEZE,
  INTERNAL_PERMISSIONS.AUDIT_VIEW,
  INTERNAL_PERMISSIONS.AUDIT_EXPORT,
  INTERNAL_PERMISSIONS.SECURITY_EVENT_DETAIL,
  ...SENIOR_SUPPORT_WALLET_PERMISSIONS,
]

export const DATA_ANALYST_DEFAULT_PERMISSIONS = [
  INTERNAL_PERMISSIONS.CHAT_VIEW,
  INTERNAL_PERMISSIONS.CHAT_SEND,
  INTERNAL_PERMISSIONS.OVERVIEW_VIEW,
  INTERNAL_PERMISSIONS.ANALYTICS_VIEW,
  INTERNAL_PERMISSIONS.ANALYTICS_EXPORT,
]

export const SOFTWARE_DEVELOPER_DEFAULT_PERMISSIONS = [
  INTERNAL_PERMISSIONS.CHAT_VIEW,
  INTERNAL_PERMISSIONS.CHAT_SEND,
  INTERNAL_PERMISSIONS.SYSTEM_HEALTH_VIEW,
  INTERNAL_PERMISSIONS.ENGINEERING_LOGS_VIEW,
  INTERNAL_PERMISSIONS.SECURITY_EVENT_DETAIL,
]

export const PLATFORM_OWNER_DEFAULT_PERMISSIONS = [
  INTERNAL_PERMISSIONS.OVERVIEW_VIEW,
  INTERNAL_PERMISSIONS.CHAT_VIEW,
  INTERNAL_PERMISSIONS.CHAT_SEND,
  INTERNAL_PERMISSIONS.CHAT_PIN,
  INTERNAL_PERMISSIONS.NETWORK_VIEW,
  INTERNAL_PERMISSIONS.NETWORK_INCIDENT_MANAGE,
  INTERNAL_PERMISSIONS.NETWORK_STATION_ACTION,
  INTERNAL_PERMISSIONS.NETWORK_EXPORT,
  INTERNAL_PERMISSIONS.STATIONS_VIEW,
  INTERNAL_PERMISSIONS.STATIONS_ACTIVATE,
  INTERNAL_PERMISSIONS.STATIONS_CONFIGURE,
  INTERNAL_PERMISSIONS.ONBOARDING_VIEW,
  INTERNAL_PERMISSIONS.ONBOARDING_MANAGE,
  INTERNAL_PERMISSIONS.FIELD_VIEW,
  INTERNAL_PERMISSIONS.FIELD_MANAGE,
  INTERNAL_PERMISSIONS.SUPPORT_VIEW,
  INTERNAL_PERMISSIONS.SUPPORT_ESCALATE,
  INTERNAL_PERMISSIONS.FINANCE_VIEW,
  INTERNAL_PERMISSIONS.FINANCE_SETTLEMENT_REJECT,
  INTERNAL_PERMISSIONS.RISK_VIEW,
  INTERNAL_PERMISSIONS.RISK_FREEZE,
  INTERNAL_PERMISSIONS.RISK_UNFREEZE,
  INTERNAL_PERMISSIONS.RISK_OVERRIDE_APPROVE,
  INTERNAL_PERMISSIONS.ANALYTICS_VIEW,
  INTERNAL_PERMISSIONS.ANALYTICS_EXPORT,
  INTERNAL_PERMISSIONS.AUDIT_VIEW,
  INTERNAL_PERMISSIONS.AUDIT_EXPORT,
  INTERNAL_PERMISSIONS.STAFF_VIEW,
  INTERNAL_PERMISSIONS.STAFF_MANAGE,
  INTERNAL_PERMISSIONS.STAFF_CREATE,
  INTERNAL_PERMISSIONS.STAFF_SUSPEND,
  INTERNAL_PERMISSIONS.STAFF_RESET_ACCESS,
  INTERNAL_PERMISSIONS.PERMISSIONS_VIEW_MATRIX,
  INTERNAL_PERMISSIONS.SYSTEM_HEALTH_VIEW,
  INTERNAL_PERMISSIONS.ENGINEERING_LOGS_VIEW,
  INTERNAL_PERMISSIONS.SETTINGS_VIEW,
  INTERNAL_PERMISSIONS.SETTINGS_EDIT,
  INTERNAL_PERMISSIONS.SECURITY_OVERRIDE,
  INTERNAL_PERMISSIONS.SECURITY_FORCE_SIGN_OUT,
  INTERNAL_PERMISSIONS.SECURITY_LOCK_ACCOUNT,
  INTERNAL_PERMISSIONS.SECURITY_EVENT_DETAIL,
  ...ADMIN_WALLET_PERMISSIONS,
]

export const PLATFORM_INFRASTRUCTURE_ENGINEER_DEFAULT_PERMISSIONS = [
  INTERNAL_PERMISSIONS.CHAT_VIEW,
  INTERNAL_PERMISSIONS.CHAT_SEND,
  INTERNAL_PERMISSIONS.SYSTEM_HEALTH_VIEW,
  INTERNAL_PERMISSIONS.ENGINEERING_LOGS_VIEW,
  INTERNAL_PERMISSIONS.SECURITY_EVENT_DETAIL,
  ...ADMIN_WALLET_PERMISSIONS,
]

export const INTERNAL_ROLE_NAV = {
  overview: INTERNAL_PERMISSIONS.OVERVIEW_VIEW,
  chat: INTERNAL_PERMISSIONS.CHAT_VIEW,
  networkOperations: INTERNAL_PERMISSIONS.NETWORK_VIEW,
  stations: INTERNAL_PERMISSIONS.STATIONS_VIEW,
  stationOnboarding: INTERNAL_PERMISSIONS.ONBOARDING_VIEW,
  fieldOperations: INTERNAL_PERMISSIONS.FIELD_VIEW,
  support: INTERNAL_PERMISSIONS.SUPPORT_VIEW,
  finance: INTERNAL_PERMISSIONS.FINANCE_VIEW,
  risk: INTERNAL_PERMISSIONS.RISK_VIEW,
  analytics: INTERNAL_PERMISSIONS.ANALYTICS_VIEW,
  audit: INTERNAL_PERMISSIONS.AUDIT_VIEW,
  walletOperations: INTERNAL_PERMISSIONS.WALLET_LOOKUP,
  staff: INTERNAL_PERMISSIONS.STAFF_VIEW,
  systemHealth: INTERNAL_PERMISSIONS.SYSTEM_HEALTH_VIEW,
  settings: INTERNAL_PERMISSIONS.SETTINGS_VIEW,
}

export function normalizePermissionList(rows = []) {
  return [...new Set((rows || []).map((row) => String(row || "").trim()).filter(Boolean))].sort()
}

export function resolveEffectiveInternalPermissions(roleCodes = [], permissionCodes = []) {
  const effective = new Set(normalizePermissionList(permissionCodes))
  const normalizedRoleCodes = (roleCodes || []).map((row) => String(row || "").trim()).filter(Boolean)

  if (normalizedRoleCodes.length) {
    effective.add(INTERNAL_PERMISSIONS.CHAT_VIEW)
    effective.add(INTERNAL_PERMISSIONS.CHAT_SEND)
  }

  if (normalizedRoleCodes.includes(INTERNAL_ROLE_CODES.PLATFORM_OWNER)) {
    PLATFORM_OWNER_RESTRICTED_PERMISSIONS.forEach((permissionCode) => effective.delete(permissionCode))
    PLATFORM_OWNER_DEFAULT_PERMISSIONS.forEach((permissionCode) => effective.add(permissionCode))
  }

  if (normalizedRoleCodes.includes(INTERNAL_ROLE_CODES.NETWORK_OPERATIONS_MANAGER)) {
    NETWORK_OPERATIONS_MANAGER_DEFAULT_PERMISSIONS.forEach((permissionCode) => effective.add(permissionCode))
  }

  if (normalizedRoleCodes.includes(INTERNAL_ROLE_CODES.STATION_ONBOARDING_MANAGER)) {
    STATION_ONBOARDING_MANAGER_DEFAULT_PERMISSIONS.forEach((permissionCode) => effective.add(permissionCode))
  }

  if (normalizedRoleCodes.includes(INTERNAL_ROLE_CODES.FIELD_AGENT)) {
    FIELD_AGENT_DEFAULT_PERMISSIONS.forEach((permissionCode) => effective.add(permissionCode))
  }

  if (normalizedRoleCodes.includes(INTERNAL_ROLE_CODES.CUSTOMER_SUPPORT_AGENT)) {
    CUSTOMER_SUPPORT_AGENT_DEFAULT_PERMISSIONS.forEach((permissionCode) => effective.add(permissionCode))
  }

  if (normalizedRoleCodes.includes(INTERNAL_ROLE_CODES.FINANCE_MANAGER)) {
    FINANCE_MANAGER_DEFAULT_PERMISSIONS.forEach((permissionCode) => effective.add(permissionCode))
  }

  if (normalizedRoleCodes.includes(INTERNAL_ROLE_CODES.RISK_COMPLIANCE_OFFICER)) {
    RISK_COMPLIANCE_OFFICER_DEFAULT_PERMISSIONS.forEach((permissionCode) => effective.add(permissionCode))
  }

  if (normalizedRoleCodes.includes(INTERNAL_ROLE_CODES.DATA_ANALYST)) {
    DATA_ANALYST_DEFAULT_PERMISSIONS.forEach((permissionCode) => effective.add(permissionCode))
  }

  if (normalizedRoleCodes.includes(INTERNAL_ROLE_CODES.SOFTWARE_DEVELOPER)) {
    SOFTWARE_DEVELOPER_DEFAULT_PERMISSIONS.forEach((permissionCode) => effective.add(permissionCode))
  }

  if (normalizedRoleCodes.includes(INTERNAL_ROLE_CODES.PLATFORM_INFRASTRUCTURE_ENGINEER)) {
    PLATFORM_INFRASTRUCTURE_ENGINEER_DEFAULT_PERMISSIONS.forEach((permissionCode) => effective.add(permissionCode))
  }

  return [...effective].sort()
}

export function hasInternalPermission(permissionSet, permissionCode) {
  return permissionSet instanceof Set ? permissionSet.has(permissionCode) : false
}
