export async function createWalletAuditLog(
  db,
  {
    walletId = null,
    ledgerTransactionId = null,
    actorUserId = null,
    actorRole = null,
    targetUserId = null,
    capabilityUsed = null,
    actionType,
    actionSummary,
    entityType = null,
    entityId = null,
    amountDeltaMwk = null,
    pointsDelta = null,
    balanceBefore = null,
    balanceAfter = null,
    reasonCode = null,
    note = null,
    approvalRequestId = null,
    correlationId = null,
    debitLedgerEntryId = null,
    creditLedgerEntryId = null,
    ipAddress = null,
    userAgent = null,
    metadata = null,
  }
) {
  await db.$executeRaw`
    INSERT INTO wallet_audit_logs (
      wallet_id,
      ledger_transaction_id,
      actor_user_id,
      actor_role,
      capability_used,
      target_user_id,
      action_type,
      action_summary,
      entity_type,
      entity_id,
      amount_delta_mwk,
      points_delta,
      balance_before_json,
      balance_after_json,
      reason_code,
      note,
      approval_request_id,
      correlation_id,
      debit_ledger_entry_id,
      credit_ledger_entry_id,
      ip_address,
      user_agent,
      metadata_json
    )
    VALUES (
      ${walletId},
      ${ledgerTransactionId},
      ${actorUserId},
      ${actorRole || null},
      ${capabilityUsed || null},
      ${targetUserId},
      ${String(actionType || "").trim()},
      ${String(actionSummary || "").trim() || String(actionType || "").trim()},
      ${entityType || null},
      ${entityId || null},
      ${amountDeltaMwk},
      ${pointsDelta},
      ${balanceBefore ? JSON.stringify(balanceBefore) : null},
      ${balanceAfter ? JSON.stringify(balanceAfter) : null},
      ${reasonCode || null},
      ${note || null},
      ${approvalRequestId},
      ${correlationId || null},
      ${debitLedgerEntryId},
      ${creditLedgerEntryId},
      ${ipAddress || null},
      ${userAgent || null},
      ${metadata ? JSON.stringify(metadata) : null}
    )
  `
}
