import { useMemo, useState } from 'react'
import { CheckCircle2, X } from 'lucide-react'
import { useSearchParams } from 'react-router'
import type { TeamPrincipal } from './teamApi'
import { money, queryString, shortDate, teamRequest, titleCase } from './teamApi'
import { TeamBadge, TeamCard, TeamEmpty, TeamError, TeamFormModal, TeamLoading, TeamPageHeader, TeamPagination, TeamTable, useTeamData, type TeamFormField } from './TeamCommon'

export function TeamProposalsPage({token,user}:{token:string;user:TeamPrincipal}){
  const [params,setParams]=useSearchParams();const [createOpen,setCreateOpen]=useState(false);const [action,setAction]=useState<any>(null);const page=Number(params.get('page')||1),status=params.get('status')||''
  const {data,loading,error,reload}=useTeamData(`/proposals${queryString({page,status,page_size:20})}`,token,params.toString());const opportunities=useTeamData('/opportunities?page_size=100',token,'proposal-options')
  const opportunityOptions=(opportunities.data?.items||[]).map((item:any)=>({value:item.public_ref,label:`${item.school_name} · ${item.title}`}))
  const fields:TeamFormField[]=[{name:'opportunity_ref',label:'Opportunity',type:'select',required:true,options:opportunityOptions},{name:'package_name',label:'Package',required:true},{name:'modules_included',label:'Modules included (comma separated)',required:true},{name:'campus_count',label:'Campuses',type:'number'},{name:'estimated_students',label:'Estimated students',type:'number'},{name:'setup_fee',label:'Setup fee',type:'number'},{name:'term_subscription',label:'Term subscription',type:'number'},{name:'training_fee',label:'Training fee',type:'number'},{name:'migration_fee',label:'Migration fee',type:'number'},{name:'website_fee',label:'Website fee',type:'number'},{name:'requested_discount',label:'Requested discount',type:'number'},{name:'payment_terms',label:'Payment terms',type:'textarea',required:true},{name:'expires_at',label:'Expiry date',type:'date',required:true},{name:'internal_notes',label:'Internal notes',type:'textarea'}]
  const actionFields:TeamFormField[]=action?.kind==='decision'?[{name:'decision',label:'Decision',type:'select',required:true,options:[{value:'approved',label:'Approve'},{value:'rejected',label:'Reject'}]},{name:'note',label:'Decision note',type:'textarea'}]:action?.kind==='submit'?[{name:'reason',label:'Discount reason (required when discount requested)',type:'textarea'}]:[{name:'note',label:'Sending note',type:'textarea'}]
  const perform=async(values:any)=>{if(action.kind==='decision')await teamRequest(`/proposals/${action.row.public_ref}/decision`,{method:'POST',body:JSON.stringify(values)},token);else if(action.kind==='submit')await teamRequest(`/proposals/${action.row.public_ref}/submit`,{method:'POST',body:JSON.stringify(values)},token);else await teamRequest(`/proposals/${action.row.public_ref}/sent`,{method:'POST',body:JSON.stringify(values)},token);await reload()}
  return<><TeamPageHeader title="Proposals and quotations" subtitle="Structured commercial records, approval controls, original prices and immutable approved discounts." action="New proposal" onAction={()=>setCreateOpen(true)}/><TeamCard><div className="border-b border-slate-100 p-3"><select value={status} onChange={event=>setParams(event.target.value?{status:event.target.value}:{})} className="h-8 rounded border border-slate-200 text-[10px]"><option value="">All statuses</option>{['draft','awaiting_approval','approved','sent','viewed','accepted','rejected','expired','replaced'].map(value=><option key={value} value={value}>{titleCase(value)}</option>)}</select></div>{loading?<TeamLoading/>:error?<TeamError message={error} retry={reload}/>:data?.items?.length?<><TeamTable rows={data.items} columns={[{key:'proposal_number',label:'Proposal',render:row=><div><div className="font-semibold">{row.proposal_number}</div><div className="text-[9px] text-slate-400">{row.school_name}</div></div>},{key:'package_name',label:'Package'},{key:'original_amount',label:'Original',render:row=>money(row.original_amount)},{key:'requested_discount',label:'Discount',render:row=>money(row.requested_discount)},{key:'final_amount',label:'Final',render:row=><span className="font-semibold">{money(row.final_amount)}</span>},{key:'status',label:'Status',render:row=><TeamBadge value={row.status}/>},{key:'expires_at',label:'Expires',render:row=>shortDate(row.expires_at)},{key:'actions',label:'Action',render:row=>row.status==='draft'?<button onClick={()=>setAction({kind:'submit',row})} className="rounded border border-slate-200 px-2 py-1 text-[9px] font-semibold">Submit</button>:row.status==='awaiting_approval'&&user.permissions.includes('DISCOUNTS_APPROVE')?<button onClick={()=>setAction({kind:'decision',row})} className="rounded border border-amber-200 bg-amber-50 px-2 py-1 text-[9px] font-semibold text-amber-700">Decide</button>:row.status==='approved'?<button onClick={()=>setAction({kind:'sent',row})} className="rounded border border-blue-200 bg-blue-50 px-2 py-1 text-[9px] font-semibold text-blue-700">Mark sent</button>:null}]}/><TeamPagination pagination={data.pagination} onPage={next=>setParams({page:String(next)})}/></>:<TeamEmpty title="No proposals matched" detail="Prepare a proposal for a qualified opportunity."/>}</TeamCard>
    <TeamFormModal open={createOpen} title="Prepare proposal" description="The first active school contact is used as recipient. Add the decision-maker from the school profile first." fields={fields} initial={{package_name:'SmartLink Core',campus_count:1}} onClose={()=>setCreateOpen(false)} onSubmit={async values=>{const modules=String(values.modules_included||'').split(',').map((name:string)=>name.trim()).filter(Boolean).map((name:string)=>({name,code:name.toLowerCase().replace(/[^a-z0-9]+/g,'_'),amount:0}));await teamRequest('/proposals',{method:'POST',body:JSON.stringify({...values,modules})},token);await reload()}}/>
    <TeamFormModal open={Boolean(action)} title={action?.kind==='decision'?'Decide proposal approval':action?.kind==='submit'?'Submit proposal':'Mark proposal as sent'} description="The action and commercial amounts are written to immutable audit history." fields={actionFields} onClose={()=>setAction(null)} onSubmit={perform}/>
  </>
}

export function TeamOnboardingPage({token,user}:{token:string;user:TeamPrincipal}){
  const [params,setParams]=useSearchParams();const [createOpen,setCreateOpen]=useState(false);const [selected,setSelected]=useState<string|null>(null);const page=Number(params.get('page')||1),stage=params.get('stage')||''
  const {data,loading,error,reload}=useTeamData(`/onboarding${queryString({page,stage,page_size:20})}`,token,params.toString());const opportunities=useTeamData('/opportunities?stage=closed_won&page_size=100',token,'won-options');const members=useTeamData('/team-members',token,'onboarding-members')
  const fields:TeamFormField[]=[{name:'opportunity_ref',label:'Closed Won opportunity',type:'select',required:true,options:(opportunities.data?.items||[]).map((item:any)=>({value:item.public_ref,label:`${item.school_name} · ${item.title}`}))},{name:'implementation_owner_ref',label:'Implementation owner',type:'select',required:true,options:(members.data?.items||[]).map((item:any)=>({value:item.public_ref,label:item.full_name}))},{name:'start_date',label:'Start date',type:'date'},{name:'expected_go_live_date',label:'Expected go-live',type:'date',required:true},{name:'notes',label:'Notes',type:'textarea'}]
  return<><TeamPageHeader title="Onboarding pipeline" subtitle="Closed Won customer handoff, assigned ownership, checklist-derived progress and explicit go-live approval." action="Create onboarding" onAction={()=>setCreateOpen(true)}/><TeamCard><div className="border-b border-slate-100 p-3"><select value={stage} onChange={event=>setParams(event.target.value?{stage:event.target.value}:{})} className="h-8 rounded border border-slate-200 text-[10px]"><option value="">All stages</option>{['contract_signed','initial_payment_pending','initial_payment_received','implementation_assigned','discovery_completed','school_configuration','data_templates_issued','data_received','migration_in_progress','migration_validation','user_accounts_created','administrator_training','bursar_training','teacher_training','pilot_testing','issues_being_resolved','go_live_approval','live','post_launch_monitoring','complete'].map(value=><option key={value} value={value}>{titleCase(value)}</option>)}</select></div>{loading?<TeamLoading/>:error?<TeamError message={error} retry={reload}/>:data?.items?.length?<><TeamTable onRow={row=>setSelected(row.public_ref)} rows={data.items} columns={[{key:'school_name',label:'School',render:row=><div><div className="font-semibold">{row.school_name}</div><div className="text-[9px] text-slate-400">{row.implementation_owner_name}</div></div>},{key:'stage',label:'Stage',render:row=><TeamBadge value={row.stage}/>},{key:'completion_percentage',label:'Progress',render:row=><div className="w-28"><div className="mb-1 text-[9px] font-semibold">{row.completion_percentage}%</div><div className="h-1.5 rounded bg-slate-100"><div className="h-full rounded bg-[#1b6ca8]" style={{width:`${row.completion_percentage}%`}}/></div></div>},{key:'risk_status',label:'Risk',render:row=><TeamBadge value={row.risk_status}/>},{key:'expected_go_live_date',label:'Expected go-live',render:row=>shortDate(row.expected_go_live_date)},{key:'main_blocker',label:'Blocker'}]}/><TeamPagination pagination={data.pagination} onPage={next=>setParams({page:String(next)})}/></>:<TeamEmpty title="No onboarding projects matched" detail="Close an opportunity as won, then create the customer handoff."/>}</TeamCard><TeamFormModal open={createOpen} title="Create onboarding project" fields={fields} onClose={()=>setCreateOpen(false)} onSubmit={async values=>{await teamRequest('/onboarding',{method:'POST',body:JSON.stringify(values)},token);await reload()}}/>{selected?<OnboardingDetail token={token} user={user} projectRef={selected} onClose={()=>setSelected(null)} onChanged={reload}/>:null}</>
}

function OnboardingDetail({token,user,projectRef,onClose,onChanged}:{token:string;user:TeamPrincipal;projectRef:string;onClose:()=>void;onChanged:()=>Promise<void>}){
  const {data,loading,error,reload}=useTeamData(`/onboarding/${projectRef}`,token,projectRef);const [goLive,setGoLive]=useState(false)
  const toggle=async(item:any)=>{await teamRequest(`/onboarding/${projectRef}/checklist/${item.public_ref}`,{method:'PATCH',body:JSON.stringify({is_complete:!item.is_complete})},token);await reload();await onChanged()}
  return<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/45 p-3"><div className="flex max-h-[92vh] w-full max-w-3xl flex-col overflow-hidden rounded-[12px] bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-[15px] font-semibold">{data?.project?.school_name||'Onboarding project'}</h2><p className="mt-1 text-[10px] text-slate-500">Checklist progress is calculated from stored completion records.</p></div><button type="button" onClick={onClose} className="grid size-8 place-items-center rounded-full hover:bg-slate-100"><X className="size-4"/></button></div>{loading?<TeamLoading/>:error?<TeamError message={error} retry={reload}/>:<><div className="grid grid-cols-3 gap-3 border-b border-slate-100 p-4"><div><div className="text-[9px] text-slate-400">Stage</div><div className="mt-1"><TeamBadge value={data.project.stage}/></div></div><div><div className="text-[9px] text-slate-400">Progress</div><div className="mt-1 text-[16px] font-semibold">{data.project.completion_percentage}%</div></div><div><div className="text-[9px] text-slate-400">Risk</div><div className="mt-1"><TeamBadge value={data.project.risk_status}/></div></div></div><div className="min-h-0 flex-1 overflow-y-auto p-4"><div className="grid gap-2 sm:grid-cols-2">{data.checklist.map((item:any)=><button key={item.public_ref} type="button" onClick={()=>toggle(item)} className={`flex items-center gap-3 rounded-[7px] border p-3 text-left ${item.is_complete?'border-emerald-200 bg-emerald-50':'border-slate-200 bg-white hover:bg-slate-50'}`}><span className={`grid size-5 shrink-0 place-items-center rounded-full border ${item.is_complete?'border-emerald-600 bg-emerald-600 text-white':'border-slate-300'}`}>{item.is_complete?<CheckCircle2 className="size-3.5"/>:null}</span><span className="text-[10px] font-medium">{item.label}</span></button>)}</div></div>{user.permissions.includes('ONBOARDING_APPROVE_GO_LIVE')?<div className="border-t border-slate-100 p-4 text-right"><button type="button" onClick={()=>setGoLive(true)} className="rounded-[6px] bg-emerald-700 px-3 py-2 text-[10px] font-semibold text-white">Approve go-live</button></div>:null}</>}</div><TeamFormModal open={goLive} title="Approve go-live" description="Required checks must be complete. An authorised override must include a reason and will be audited." fields={[{name:'override_reason',label:'Override reason (only if checks remain)',type:'textarea'}]} onClose={()=>setGoLive(false)} onSubmit={async values=>{await teamRequest(`/onboarding/${projectRef}/go-live`,{method:'POST',body:JSON.stringify(values)},token);await reload();await onChanged()}}/></div>
}

export function TeamSubscriptionsPage({token}:{token:string}){
  const [params,setParams]=useSearchParams();const [createOpen,setCreateOpen]=useState(false);const page=Number(params.get('page')||1),expiring=params.get('expiring')||'';const {data,loading,error,reload}=useTeamData(`/subscriptions${queryString({page,expiring,page_size:20})}`,token,params.toString());const schools=useTeamData('/schools?status=customer&page_size=100',token,'customer-options');const members=useTeamData('/team-members',token,'subscription-members')
  const fields:TeamFormField[]=[{name:'school_ref',label:'Customer school',type:'select',required:true,options:(schools.data?.items||[]).map((item:any)=>({value:item.public_ref,label:item.name}))},{name:'package_name',label:'Package',required:true},{name:'starts_on',label:'Start date',type:'date',required:true},{name:'expires_on',label:'Expiry date',type:'date',required:true},{name:'academic_term',label:'Academic term'},{name:'duration_months',label:'Duration months',type:'number'},{name:'amount',label:'Amount',type:'number',required:true},{name:'invoice_status',label:'Invoice status',type:'select',options:['not_issued','draft','issued','part_paid','paid','void'].map(value=>({value,label:titleCase(value)}))},{name:'payment_status',label:'Payment status',type:'select',options:['pending','part_paid','paid','overdue','waived'].map(value=>({value,label:titleCase(value)}))},{name:'grace_period_days',label:'Grace-period days',type:'number'},{name:'renewal_owner_ref',label:'Renewal owner',type:'select',required:true,options:(members.data?.items||[]).map((item:any)=>({value:item.public_ref,label:item.full_name}))},{name:'notes',label:'Notes',type:'textarea'}]
  return<><TeamPageHeader title="Subscriptions" subtitle="Renewal and payment alerts are operational only; development records never suspend a live school automatically." action="New subscription" onAction={()=>setCreateOpen(true)}/><TeamCard><div className="border-b border-slate-100 p-3"><button type="button" onClick={()=>setParams(expiring?{}:{expiring:'true'})} className={`h-8 rounded border px-3 text-[10px] font-semibold ${expiring?'border-amber-200 bg-amber-50 text-amber-700':'border-slate-200'}`}>Expiring within 30 days</button></div>{loading?<TeamLoading/>:error?<TeamError message={error} retry={reload}/>:data?.items?.length?<><TeamTable rows={data.items} columns={[{key:'school_name',label:'School'},{key:'package_name',label:'Package'},{key:'status',label:'Status',render:row=><TeamBadge value={row.status}/>},{key:'payment_status',label:'Payment',render:row=><TeamBadge value={row.payment_status}/>},{key:'amount',label:'Amount',render:row=>money(row.amount)},{key:'expires_on',label:'Expires',render:row=><div><div>{shortDate(row.expires_on)}</div><div className="text-[9px] text-slate-400">{row.days_to_expiry} days</div></div>},{key:'renewal_owner_name',label:'Renewal owner'}]}/><TeamPagination pagination={data.pagination} onPage={next=>setParams({page:String(next)})}/></>:<TeamEmpty title="No subscriptions matched" detail="Create a subscription for a converted customer."/>}</TeamCard><TeamFormModal open={createOpen} title="Create subscription" fields={fields} initial={{package_name:'SmartLink Core',invoice_status:'not_issued',payment_status:'pending',grace_period_days:7}} onClose={()=>setCreateOpen(false)} onSubmit={async values=>{await teamRequest('/subscriptions',{method:'POST',body:JSON.stringify(values)},token);await reload()}}/></>
}
