import { useState } from 'react'
import { useSearchParams } from 'react-router'
import type { TeamPrincipal } from './teamApi'
import { money, queryString, shortDate, teamRequest, titleCase } from './teamApi'
import { TeamBadge, TeamCard, TeamCardHeader, TeamEmpty, TeamError, TeamFormModal, TeamLoading, TeamPageHeader, TeamPagination, TeamTable, useTeamData, type TeamFormField } from './TeamCommon'

export function TeamMembersPage({token,user}:{token:string;user:TeamPrincipal}){
  const [createOpen,setCreateOpen]=useState(false);const {data,loading,error,reload}=useTeamData('/team-members',token)
  const canManage=user.permissions.includes('TEAM_MEMBERS_MANAGE')
  const fields:TeamFormField[]=[{name:'full_name',label:'Full name',required:true},{name:'email',label:'Work email',type:'email',required:true},{name:'job_title',label:'Job title'},{name:'phone',label:'Phone'},{name:'role',label:'Primary role',type:'select',required:true,options:[['platform_owner','Platform Owner'],['operations_partnerships_manager','Operations & Partnerships Manager'],['outreach_officer','Outreach Officer'],['implementation_support_officer','Implementation & Support Officer'],['finance_officer','Finance Officer'],['developer','Developer']].map(([value,label])=>({value,label}))},{name:'temporary_password',label:'Temporary password',required:true}]
  return<><TeamPageHeader title="Team members" subtitle="Internal accounts are separate from school tenant users. Role changes take effect from the database on every request." action={canManage?'New team member':undefined} onAction={()=>setCreateOpen(true)}/><TeamCard>{loading?<TeamLoading/>:error?<TeamError message={error} retry={reload}/>:data?.items?.length?<TeamTable rows={data.items} columns={[{key:'full_name',label:'Team member',render:row=><div><div className="font-semibold">{row.full_name}</div><div className="text-[9px] text-slate-400">{row.email}</div></div>},{key:'job_title',label:'Job title'},{key:'role_labels',label:'Roles'},{key:'is_active',label:'Status',render:row=><TeamBadge value={row.is_active?'active':'disabled'}/>},{key:'must_change_password',label:'Password',render:row=><TeamBadge value={row.must_change_password?'change required':'ready'}/>},{key:'last_login_at',label:'Last login',render:row=>shortDate(row.last_login_at,true)}]}/>:<TeamEmpty title="No team members" detail="Create the first authorised internal account using the protected seed or API workflow."/>}</TeamCard><TeamFormModal open={createOpen} title="Create team member" description="The temporary password is hashed with bcrypt and must be changed on first login." fields={fields} onClose={()=>setCreateOpen(false)} onSubmit={async values=>{await teamRequest('/team-members',{method:'POST',body:JSON.stringify({...values,roles:[values.role]})},token);await reload()}}/></>
}

export function TeamReportsPage({token}:{token:string}){
  const {data,loading,error,reload}=useTeamData('/reports',token)
  if(loading)return<TeamLoading/>;if(error)return<TeamError message={error} retry={reload}/>
  const total=Number(data?.conversion?.total||0),won=Number(data?.conversion?.won||0)
  return<><TeamPageHeader title="Operational reports" subtitle="Pipeline, workload, support and subscription summaries calculated from current authorised records."/><div className="grid gap-3 md:grid-cols-3"><TeamCard className="p-4"><div className="text-[9px] uppercase text-slate-400">All opportunities</div><div className="mt-2 text-[24px] font-semibold">{total}</div></TeamCard><TeamCard className="p-4"><div className="text-[9px] uppercase text-slate-400">Closed won</div><div className="mt-2 text-[24px] font-semibold text-emerald-700">{won}</div></TeamCard><TeamCard className="p-4"><div className="text-[9px] uppercase text-slate-400">Win rate</div><div className="mt-2 text-[24px] font-semibold">{total?Math.round(won/total*100):0}%</div></TeamCard></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><TeamCard><TeamCardHeader title="Pipeline by stage"/><TeamTable rows={data?.pipeline||[]} columns={[{key:'stage',label:'Stage',render:row=><TeamBadge value={row.stage}/>},{key:'opportunities',label:'Opportunities'},{key:'value',label:'Value',render:row=>money(row.value)}]}/></TeamCard><TeamCard><TeamCardHeader title="Task workload"/><TeamTable rows={data?.task_workload||[]} columns={[{key:'full_name',label:'Team member'},{key:'open_tasks',label:'Open tasks'},{key:'overdue_tasks',label:'Overdue'}]}/></TeamCard><TeamCard><TeamCardHeader title="Support distribution"/><TeamTable rows={data?.support||[]} columns={[{key:'severity',label:'Severity',render:row=><TeamBadge value={row.severity}/>},{key:'status',label:'Status',render:row=><TeamBadge value={row.status}/>},{key:'total',label:'Tickets'}]}/></TeamCard><TeamCard><TeamCardHeader title="Subscription distribution"/><TeamTable rows={data?.subscriptions||[]} columns={[{key:'status',label:'Status',render:row=><TeamBadge value={row.status}/>},{key:'payment_status',label:'Payment',render:row=><TeamBadge value={row.payment_status}/>},{key:'total',label:'Subscriptions'},{key:'amount',label:'Value',render:row=>money(row.amount)}]}/></TeamCard></div></>
}

export function TeamAuditPage({token}:{token:string}){
  const [params,setParams]=useSearchParams();const page=Number(params.get('page')||1),entityType=params.get('entity_type')||'';const {data,loading,error,reload}=useTeamData(`/audit-log${queryString({page,entity_type:entityType,page_size:30})}`,token,params.toString())
  return<><TeamPageHeader title="Immutable audit log" subtitle="This history can be read by authorised roles but has no edit or delete route—even for Platform Owners."/><TeamCard><div className="border-b border-slate-100 p-3"><select value={entityType} onChange={event=>setParams(event.target.value?{entity_type:event.target.value}:{})} className="h-8 rounded border border-slate-200 text-[10px]"><option value="">All entity types</option>{['team_user','school','school_contact','opportunity','task','meeting','proposal','onboarding','subscription','support_ticket'].map(value=><option key={value}>{value}</option>)}</select></div>{loading?<TeamLoading/>:error?<TeamError message={error} retry={reload}/>:data?.items?.length?<><TeamTable rows={data.items} columns={[{key:'created_at',label:'Timestamp',render:row=>shortDate(row.created_at,true)},{key:'actor_name',label:'Actor'},{key:'action',label:'Action',render:row=>titleCase(row.action)},{key:'entity_type',label:'Entity',render:row=><TeamBadge value={row.entity_type}/>},{key:'school_name',label:'School'},{key:'reason',label:'Reason'},{key:'ip_address',label:'IP'}]}/><TeamPagination pagination={data.pagination} onPage={next=>setParams({page:String(next)})}/></>:<TeamEmpty title="No audit entries matched" detail="Important login and operational actions will appear here."/>}</TeamCard></>
}

export function TeamSettingsPage({token}:{token:string}){
  const {data,loading,error,reload}=useTeamData('/roles',token)
  if(loading)return<TeamLoading/>;if(error)return<TeamError message={error} retry={reload}/>
  const assigned=new Map<string,Set<string>>();for(const item of data?.assignments||[]){if(!assigned.has(item.role_code))assigned.set(item.role_code,new Set());assigned.get(item.role_code)!.add(item.permission_code)}
  return<><TeamPageHeader title="Roles and permissions" subtitle="A Team Suite user can hold multiple roles. Backend permission checks remain authoritative."/><div className="space-y-4">{(data?.roles||[]).map((role:any)=><TeamCard key={role.code}><TeamCardHeader title={role.name} subtitle={role.description}/><div className="flex flex-wrap gap-2 p-4">{(data.permissions||[]).filter((permission:any)=>assigned.get(role.code)?.has(permission.code)).map((permission:any)=><span key={permission.code} title={permission.description} className="rounded-[6px] border border-slate-200 bg-slate-50 px-2.5 py-1.5 text-[9px] font-semibold text-slate-600">{permission.name}</span>)}</div></TeamCard>)}</div></>
}
