import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarClock, CircleAlert, Clock3, MessageSquareText, Target, Users } from 'lucide-react'
import { useNavigate, useParams, useSearchParams } from 'react-router'
import { money, queryString, shortDate, teamRequest, titleCase } from './teamApi'
import { TeamBadge, TeamCard, TeamCardHeader, TeamEmpty, TeamError, TeamFormModal, TeamLoading, TeamPageHeader, TeamPagination, TeamTable, useTeamData, type TeamFormField } from './TeamCommon'

export function TeamDashboardPage({ token }: { token: string }) {
  const navigate = useNavigate()
  const { data, loading, error, reload } = useTeamData('/dashboard', token)
  if (loading) return <TeamLoading label="Calculating live Team Suite metrics…" />
  if (error) return <TeamError message={error} retry={reload} />
  const maxFunnel = Math.max(1, ...(data?.conversion_funnel || []).map((item: any) => Number(item.total || 0)))
  return <><TeamPageHeader title="Team command centre" subtitle="Live pipeline, follow-up, onboarding, renewal and support signals calculated from Team Suite records." />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{(data?.metrics || []).map((metric: any) => <button key={metric.key} type="button" onClick={() => navigate(metric.path)} className="group rounded-[9px] border border-[#dce3ec] bg-white p-4 text-left shadow-[0_2px_10px_rgba(15,30,46,0.035)] transition hover:-translate-y-0.5 hover:border-[#8bb8d6] hover:shadow-md"><div className="text-[10px] font-semibold uppercase tracking-[0.08em] text-slate-500">{metric.label}</div><div className="mt-3 flex items-end justify-between"><span className="text-[26px] font-semibold tracking-[-0.04em] text-[#142333]">{metric.value}</span><ArrowRight className="size-4 text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-[#175f91]" /></div></button>)}</div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3">
      <TeamCard className="xl:col-span-2"><TeamCardHeader title="Today’s tasks" subtitle="Due today and still requiring action" /><TeamTable rows={data?.today_tasks || []} columns={[{key:'title',label:'Task'},{key:'school_name',label:'School'},{key:'priority',label:'Priority',render:(row)=><TeamBadge value={row.priority}/>},{key:'due_at',label:'Due',render:(row)=>shortDate(row.due_at,true)}]} />{!data?.today_tasks?.length ? <TeamEmpty title="No tasks due today" detail="New assigned tasks and due work will appear here." /> : null}</TeamCard>
      <TeamCard><TeamCardHeader title="Pipeline value" subtitle="Open opportunities only" /><div className="p-5"><div className="text-[10px] uppercase tracking-wide text-slate-500">Expected value</div><div className="mt-2 text-[24px] font-semibold tracking-tight">{money(data?.pipeline_value?.total_value)}</div><div className="mt-5 text-[10px] uppercase tracking-wide text-slate-500">Probability weighted</div><div className="mt-2 text-[18px] font-semibold text-[#175f91]">{money(data?.pipeline_value?.weighted_value)}</div></div></TeamCard>
      <TeamCard><TeamCardHeader title="Upcoming meetings" subtitle="Confirmed future team engagements" /><div className="divide-y divide-slate-100">{(data?.upcoming_meetings || []).map((meeting:any)=><div key={meeting.public_ref} className="flex gap-3 px-4 py-3"><CalendarClock className="mt-0.5 size-4 shrink-0 text-[#175f91]"/><div className="min-w-0"><div className="truncate text-[11px] font-semibold">{meeting.school_name}</div><div className="mt-1 text-[10px] text-slate-500">{titleCase(meeting.meeting_type)} · {shortDate(meeting.scheduled_at,true)}</div></div></div>)}{!data?.upcoming_meetings?.length?<TeamEmpty title="No upcoming meetings" detail="Scheduled meetings and demos will appear here."/>:null}</div></TeamCard>
      <TeamCard><TeamCardHeader title="Opportunities requiring attention" subtitle="Missing, overdue or stale next actions" /><div className="divide-y divide-slate-100">{(data?.opportunities_requiring_attention || []).map((item:any)=><button type="button" onClick={()=>navigate('/team/pipeline')} key={item.public_ref} className="flex w-full gap-3 px-4 py-3 text-left hover:bg-slate-50"><CircleAlert className="mt-0.5 size-4 shrink-0 text-amber-600"/><div className="min-w-0"><div className="truncate text-[11px] font-semibold">{item.title}</div><div className="mt-1 flex items-center gap-2"><span className="text-[10px] text-slate-500">{item.school_name}</span><TeamBadge value={item.stage}/></div></div></button>)}{!data?.opportunities_requiring_attention?.length?<TeamEmpty title="No attention flags" detail="Every active opportunity currently has a timely next action."/>:null}</div></TeamCard>
      <TeamCard><TeamCardHeader title="Conversion funnel" subtitle="Real records by current stage" /><div className="space-y-2.5 p-4">{(data?.conversion_funnel || []).map((item:any)=><div key={item.stage}><div className="mb-1 flex justify-between text-[9px]"><span className="font-medium text-slate-600">{titleCase(item.stage)}</span><span className="font-semibold">{item.total}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#1b6ca8]" style={{width:`${Math.max(4,Number(item.total)/maxFunnel*100)}%`}}/></div></div>)}</div></TeamCard>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><TeamCard><TeamCardHeader title="Recent school activity" subtitle="Latest manual and workflow events"/><div className="divide-y divide-slate-100">{(data?.recent_activity||[]).map((activity:any)=><div key={activity.public_ref} className="flex gap-3 px-4 py-3"><MessageSquareText className="mt-0.5 size-4 text-slate-400"/><div className="min-w-0"><div className="truncate text-[11px] font-semibold">{activity.summary}</div><div className="mt-1 text-[10px] text-slate-500">{activity.school_name} · {activity.team_user_name} · {shortDate(activity.occurred_at,true)}</div></div></div>)}</div></TeamCard><TeamCard><TeamCardHeader title="Team workload" subtitle="Open and overdue assignments"/><TeamTable rows={data?.team_workload||[]} columns={[{key:'full_name',label:'Team member'},{key:'open_tasks',label:'Open'},{key:'overdue_tasks',label:'Overdue',render:(row)=><span className={Number(row.overdue_tasks)>0?'font-semibold text-rose-600':''}>{row.overdue_tasks}</span>}]} /></TeamCard></div>
  </>
}

const schoolFields: TeamFormField[] = [
  {name:'name',label:'School name',required:true},{name:'school_type',label:'School type',type:'select',required:true,options:['preschool','primary','secondary','combined','college','other'].map(value=>({value,label:titleCase(value)}))},
  {name:'district',label:'District'},{name:'location',label:'Location'},{name:'main_phone',label:'Main phone'},{name:'whatsapp_number',label:'WhatsApp number'},{name:'email',label:'Email',type:'email'},{name:'estimated_enrolment',label:'Estimated enrolment',type:'number'},
  {name:'estimated_deal_value',label:'Estimated deal value (MWK)',type:'number'},{name:'priority',label:'Priority',type:'select',options:['low','medium','high','critical'].map(value=>({value,label:titleCase(value)}))},{name:'lead_source',label:'Lead source'},{name:'next_action',label:'Next action'},
  {name:'next_action_at',label:'Next-action date',type:'datetime-local'},{name:'notes',label:'Internal notes',type:'textarea'},
]

export function TeamSchoolsPage({ token }: { token: string }) {
  const navigate=useNavigate();const [params,setParams]=useSearchParams();const [createOpen,setCreateOpen]=useState(false)
  const page=Number(params.get('page')||1),search=params.get('search')||'',status=params.get('status')||'',priority=params.get('priority')||'',noNextAction=params.get('no_next_action')||''
  const path=`/schools${queryString({page,search,status,priority,no_next_action:noNextAction,page_size:20})}`
  const {data,loading,error,reload}=useTeamData(path,token,params.toString())
  return <><TeamPageHeader title="School directory" subtitle="Prospects and customers are operational records, kept separate from live SmartLink Schools tenants until conversion." action="New prospect" onAction={()=>setCreateOpen(true)}/>
    <TeamCard><div className="flex flex-wrap gap-2 border-b border-slate-100 p-3"><input defaultValue={search} onKeyDown={(event)=>{if(event.key==='Enter')setParams(current=>{current.set('search',(event.target as HTMLInputElement).value);current.set('page','1');return current})}} placeholder="Search name, phone, email…" className="h-8 min-w-[220px] flex-1 rounded-[6px] border border-slate-200 px-2.5 text-[11px]"/><select value={status} onChange={event=>setParams(current=>{event.target.value?current.set('status',event.target.value):current.delete('status');current.set('page','1');return current})} className="h-8 rounded-[6px] border border-slate-200 px-2 text-[10px]"><option value="">All statuses</option>{['prospect','qualified_prospect','active_opportunity','customer','former_customer','disqualified','follow_up_later','do_not_contact'].map(value=><option key={value} value={value}>{titleCase(value)}</option>)}</select><select value={priority} onChange={event=>setParams(current=>{event.target.value?current.set('priority',event.target.value):current.delete('priority');return current})} className="h-8 rounded-[6px] border border-slate-200 px-2 text-[10px]"><option value="">All priorities</option>{['critical','high','medium','low'].map(value=><option key={value}>{value}</option>)}</select></div>
      {loading?<TeamLoading/>:error?<TeamError message={error} retry={reload}/>:data?.items?.length?<><TeamTable onRow={row=>navigate(`/team/schools/${row.public_ref}`)} rows={data.items} columns={[{key:'name',label:'School',render:row=><div><div className="font-semibold text-[#142333]">{row.name}</div><div className="mt-0.5 text-[9px] text-slate-400">{titleCase(row.school_type)} · {row.district||row.location||'Location not recorded'}</div></div>},{key:'status',label:'Status',render:row=><TeamBadge value={row.status}/>},{key:'pipeline_stage',label:'Pipeline',render:row=><TeamBadge value={row.pipeline_stage}/>},{key:'assigned_user_name',label:'Owner'},{key:'estimated_deal_value',label:'Estimated value',render:row=>money(row.estimated_deal_value)},{key:'next_action_at',label:'Next action',render:row=><div><div className="max-w-[220px] truncate">{row.next_action||'No next action'}</div><div className="mt-0.5 text-[9px] text-slate-400">{shortDate(row.next_action_at,true)}</div></div>}]} /><TeamPagination pagination={data.pagination} onPage={next=>setParams(current=>{current.set('page',String(next));return current})}/></>:<TeamEmpty title="No schools matched" detail="Create a prospect or change the active filters."/>}</TeamCard>
    <TeamFormModal open={createOpen} title="Create school prospect" description="Duplicate matching remains visible; legitimate campuses can be related after creation." fields={schoolFields} initial={{school_type:'combined',priority:'medium'}} onClose={()=>setCreateOpen(false)} onSubmit={async values=>{const result=await teamRequest('/schools',{method:'POST',body:JSON.stringify(values)},token);await reload();navigate(`/team/schools/${result.school.public_ref}`)}}/>
  </>
}

type SchoolAction='contact'|'activity'|'opportunity'|'task'|'meeting'|'support'|null
export function TeamSchoolProfilePage({token}:{token:string}){
  const {schoolRef}=useParams();const navigate=useNavigate();const [tab,setTab]=useState('overview');const [action,setAction]=useState<SchoolAction>(null)
  const {data,loading,error,reload}=useTeamData(`/schools/${schoolRef}`,token,schoolRef)
  const fields=useMemo<TeamFormField[]>(()=>{
    if(action==='contact')return[{name:'full_name',label:'Full name',required:true},{name:'position',label:'Position'},{name:'phone',label:'Phone'},{name:'whatsapp_number',label:'WhatsApp'},{name:'email',label:'Email',type:'email'},{name:'classifications',label:'Classification',type:'select',options:['decision_maker','champion','influencer','blocker','end_user','technical_contact','finance_contact'].map(value=>({value,label:titleCase(value)}))},{name:'communication_consent',label:'Communication consent recorded',type:'checkbox'},{name:'notes',label:'Notes',type:'textarea'}]
    if(action==='activity')return[{name:'activity_type',label:'Activity type',type:'select',required:true,options:['whatsapp_sent','whatsapp_reply','phone_call','email_sent','email_received','school_visit','follow_up','internal_note'].map(value=>({value,label:titleCase(value)}))},{name:'contact_ref',label:'Contact',type:'select',options:(data?.contacts||[]).map((item:any)=>({value:item.public_ref,label:item.full_name}))},{name:'summary',label:'Summary',required:true},{name:'outcome',label:'Outcome'},{name:'next_action',label:'Next action'},{name:'next_action_at',label:'Next-action date',type:'datetime-local'},{name:'notes',label:'Full notes',type:'textarea'}]
    if(action==='opportunity')return[{name:'title',label:'Opportunity title',required:true},{name:'stage',label:'Stage',type:'select',options:['discovered','researching','qualified','ready_for_outreach','first_message_sent','awaiting_response','responded','needs_assessment','meeting_scheduled','demo_scheduled'].map(value=>({value,label:titleCase(value)}))},{name:'estimated_setup_revenue',label:'Setup revenue',type:'number'},{name:'estimated_term_revenue',label:'Term revenue',type:'number'},{name:'probability',label:'Probability %',type:'number'},{name:'expected_close_date',label:'Expected close date',type:'date'},{name:'proposed_package',label:'Proposed package'},{name:'next_action',label:'Next action'},{name:'next_action_at',label:'Next-action date',type:'datetime-local'}]
    if(action==='task')return[{name:'title',label:'Task title',required:true},{name:'description',label:'Description',type:'textarea'},{name:'due_at',label:'Due date',type:'datetime-local',required:true},{name:'priority',label:'Priority',type:'select',options:['low','medium','high','critical'].map(value=>({value,label:titleCase(value)}))},{name:'category',label:'Category',type:'select',options:['research_school','verify_phone_number','send_introduction','follow_up','schedule_meeting','prepare_demo','send_proposal','visit_school','collect_documents','request_payment','begin_migration','conduct_training','resolve_support_issue','other'].map(value=>({value,label:titleCase(value)}))}]
    if(action==='meeting')return[{name:'meeting_type',label:'Meeting type',type:'select',required:true,options:['discovery','introductory','product_demo','technical','pricing','contract','onboarding','training','support_review'].map(value=>({value,label:titleCase(value)}))},{name:'scheduled_at',label:'Date and time',type:'datetime-local',required:true},{name:'attendance_mode',label:'Mode',type:'select',options:[{value:'physical',label:'Physical'},{value:'remote',label:'Remote'}]},{name:'location',label:'Location or link'},{name:'agenda',label:'Agenda',type:'textarea'}]
    return[{name:'reporter_name',label:'Reporter',required:true},{name:'module_name',label:'Module'},{name:'category',label:'Category',type:'select',required:true,options:['login_problem','permissions','student_records','fees','results','assessment_builder','report_cards','migration','performance_issue','data_correction','training_request','feature_request','bug','configuration_request','other'].map(value=>({value,label:titleCase(value)}))},{name:'severity',label:'Severity',type:'select',options:['critical','high','medium','low'].map(value=>({value,label:titleCase(value)}))},{name:'description',label:'Description',type:'textarea',required:true},{name:'target_resolution_at',label:'Target resolution',type:'datetime-local'},{name:'internal_notes',label:'Internal notes',type:'textarea'}]
  },[action,data])
  if(loading)return<TeamLoading/>;if(error)return<TeamError message={error} retry={reload}/>;const school=data.school
  const tabs=['overview','contacts','activity','opportunity','tasks','meetings','proposals','onboarding','subscription','support','audit history']
  const submit=async(values:any)=>{if(action==='contact'){values.classifications=values.classifications?[values.classifications]:[];await teamRequest(`/schools/${schoolRef}/contacts`,{method:'POST',body:JSON.stringify(values)},token)}else if(action==='activity')await teamRequest('/activities',{method:'POST',body:JSON.stringify({...values,school_ref:schoolRef})},token);else if(action==='opportunity')await teamRequest('/opportunities',{method:'POST',body:JSON.stringify({...values,school_ref:schoolRef})},token);else if(action==='task')await teamRequest('/tasks',{method:'POST',body:JSON.stringify({...values,school_ref:schoolRef})},token);else if(action==='meeting')await teamRequest('/meetings',{method:'POST',body:JSON.stringify({...values,school_ref:schoolRef})},token);else await teamRequest('/support',{method:'POST',body:JSON.stringify({...values,school_ref:schoolRef})},token);await reload()}
  return<><button type="button" onClick={()=>navigate('/team/schools')} className="mb-3 inline-flex items-center gap-2 text-[10px] font-semibold text-slate-500 hover:text-[#175f91]"><ArrowLeft className="size-3.5"/>School directory</button><TeamPageHeader title={school.name} subtitle={`${titleCase(school.school_type)} · ${school.district||school.location||'Location not recorded'} · Assigned operational record`}/>
    <div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><TeamCard className="p-4"><div className="text-[9px] uppercase text-slate-400">Status</div><div className="mt-2"><TeamBadge value={school.status}/></div></TeamCard><TeamCard className="p-4"><div className="text-[9px] uppercase text-slate-400">Pipeline stage</div><div className="mt-2"><TeamBadge value={school.pipeline_stage}/></div></TeamCard><TeamCard className="p-4"><div className="text-[9px] uppercase text-slate-400">Estimated value</div><div className="mt-2 text-[16px] font-semibold">{money(school.estimated_deal_value)}</div></TeamCard><TeamCard className="p-4"><div className="text-[9px] uppercase text-slate-400">Next action</div><div className="mt-2 truncate text-[11px] font-semibold">{school.next_action||'Not scheduled'}</div><div className="mt-1 text-[9px] text-slate-400">{shortDate(school.next_action_at,true)}</div></TeamCard></div>
    <div className="mb-4 flex flex-wrap gap-2">{([['contact','Add contact'],['activity','Record interaction'],['opportunity','New opportunity'],['task','Create task'],['meeting','Schedule meeting'],['support','Open support ticket']] as const).map(([key,label])=><button key={key} type="button" onClick={()=>setAction(key)} className="h-8 rounded-[6px] border border-slate-200 bg-white px-3 text-[10px] font-semibold hover:border-[#8bb8d6] hover:text-[#175f91]">{label}</button>)}</div>
    <TeamCard><div className="flex gap-1 overflow-x-auto border-b border-slate-100 px-3 pt-2">{tabs.map(item=><button key={item} type="button" onClick={()=>setTab(item)} className={`whitespace-nowrap border-b-2 px-3 py-2 text-[10px] font-semibold ${tab===item?'border-[#175f91] text-[#175f91]':'border-transparent text-slate-500'}`}>{titleCase(item)}</button>)}</div>
      {tab==='overview'?<div className="grid gap-5 p-5 md:grid-cols-2"><div><h3 className="text-[11px] font-semibold">School details</h3><dl className="mt-3 grid grid-cols-2 gap-3 text-[10px]">{[['Email',school.email],['Phone',school.main_phone],['WhatsApp',school.whatsapp_number],['Curriculum',school.curriculum],['Enrolment',school.estimated_enrolment],['Campuses',school.campus_count],['Priority',titleCase(school.priority)],['Lead source',school.lead_source]].map(([label,value])=><div key={label}><dt className="text-slate-400">{label}</dt><dd className="mt-1 font-medium text-slate-700">{value||'—'}</dd></div>)}</dl></div><div><h3 className="text-[11px] font-semibold">Qualification</h3><p className="mt-3 whitespace-pre-wrap text-[11px] leading-5 text-slate-600">{school.notes||'No internal qualification notes yet.'}</p></div></div>:null}
      {tab==='contacts'?<ProfileTable rows={data.contacts} empty="No contacts have been added." columns={[{key:'full_name',label:'Contact'},{key:'position',label:'Position'},{key:'classifications',label:'Relationship',render:(row:any)=><TeamBadge value={String(row.classifications||'unknown').split(',')[0]}/>},{key:'phone',label:'Phone'},{key:'email',label:'Email'},{key:'last_contacted_at',label:'Last contacted',render:(row:any)=>shortDate(row.last_contacted_at,true)}]}/>:null}
      {tab==='activity'?<ProfileTable rows={data.activities} empty="No interactions have been recorded." columns={[{key:'occurred_at',label:'Date',render:(row:any)=>shortDate(row.occurred_at,true)},{key:'activity_type',label:'Type',render:(row:any)=><TeamBadge value={row.activity_type}/>},{key:'summary',label:'Summary'},{key:'team_user_name',label:'Team member'},{key:'next_action',label:'Next action'}]}/>:null}
      {tab==='opportunity'?<ProfileTable rows={data.opportunities} empty="No opportunity has been created." columns={[{key:'title',label:'Opportunity'},{key:'stage',label:'Stage',render:(row:any)=><TeamBadge value={row.stage}/>},{key:'owner_name',label:'Owner'},{key:'total_expected_value',label:'Value',render:(row:any)=>money(row.total_expected_value)},{key:'next_action_at',label:'Next action',render:(row:any)=>shortDate(row.next_action_at,true)}]}/>:null}
      {tab==='tasks'?<ProfileTable rows={data.tasks} empty="No tasks are linked to this school." columns={[{key:'title',label:'Task'},{key:'assigned_user_name',label:'Assigned'},{key:'priority',label:'Priority',render:(row:any)=><TeamBadge value={row.priority}/>},{key:'status',label:'Status',render:(row:any)=><TeamBadge value={row.status}/>},{key:'due_at',label:'Due',render:(row:any)=>shortDate(row.due_at,true)}]}/>:null}
      {tab==='meetings'?<ProfileTable rows={data.meetings} empty="No meetings are linked to this school." columns={[{key:'meeting_type',label:'Type',render:(row:any)=>titleCase(row.meeting_type)},{key:'scheduled_at',label:'Date',render:(row:any)=>shortDate(row.scheduled_at,true)},{key:'attendance_mode',label:'Mode',render:(row:any)=><TeamBadge value={row.attendance_mode}/>},{key:'outcome',label:'Outcome',render:(row:any)=><TeamBadge value={row.outcome}/>},{key:'organiser_name',label:'Organiser'}]}/>:null}
      {tab==='proposals'?<ProfileTable rows={data.proposals} empty="No proposals are linked to this school." columns={[{key:'proposal_number',label:'Proposal'},{key:'package_name',label:'Package'},{key:'final_amount',label:'Amount',render:(row:any)=>money(row.final_amount)},{key:'status',label:'Status',render:(row:any)=><TeamBadge value={row.status}/>},{key:'expires_at',label:'Expires',render:(row:any)=>shortDate(row.expires_at)}]}/>:null}
      {tab==='onboarding'?<ProfileTable rows={data.onboarding} empty="No onboarding project exists." columns={[{key:'stage',label:'Stage',render:(row:any)=><TeamBadge value={row.stage}/>},{key:'completion_percentage',label:'Progress',render:(row:any)=>`${row.completion_percentage}%`},{key:'risk_status',label:'Risk',render:(row:any)=><TeamBadge value={row.risk_status}/>},{key:'implementation_owner_name',label:'Owner'},{key:'expected_go_live_date',label:'Expected go-live',render:(row:any)=>shortDate(row.expected_go_live_date)}]}/>:null}
      {tab==='subscription'?<ProfileTable rows={data.subscriptions} empty="No subscription exists." columns={[{key:'package_name',label:'Package'},{key:'status',label:'Status',render:(row:any)=><TeamBadge value={row.status}/>},{key:'payment_status',label:'Payment',render:(row:any)=><TeamBadge value={row.payment_status}/>},{key:'amount',label:'Amount',render:(row:any)=>money(row.amount)},{key:'expires_on',label:'Expires',render:(row:any)=>shortDate(row.expires_on)}]}/>:null}
      {tab==='support'?<ProfileTable rows={data.support_tickets} empty="No support tickets exist." columns={[{key:'ticket_number',label:'Ticket'},{key:'category',label:'Category',render:(row:any)=>titleCase(row.category)},{key:'severity',label:'Severity',render:(row:any)=><TeamBadge value={row.severity}/>},{key:'status',label:'Status',render:(row:any)=><TeamBadge value={row.status}/>},{key:'assigned_user_name',label:'Assigned'}]}/>:null}
      {tab==='audit history'?<ProfileTable rows={data.audit_history} empty="No permitted audit entries exist." columns={[{key:'created_at',label:'Date',render:(row:any)=>shortDate(row.created_at,true)},{key:'action',label:'Action',render:(row:any)=>titleCase(row.action)},{key:'entity_type',label:'Entity',render:(row:any)=>titleCase(row.entity_type)},{key:'actor_name',label:'Actor'},{key:'reason',label:'Reason'}]}/>:null}
    </TeamCard>
    <TeamFormModal open={Boolean(action)} title={titleCase(action||'Action')} description="This action is stored in the school timeline and audit history where applicable." fields={fields} initial={action==='activity'?{activity_type:'whatsapp_sent'}:action==='opportunity'?{stage:'discovered',probability:10}:action==='task'?{priority:'medium',category:'follow_up'}:action==='meeting'?{attendance_mode:'physical',meeting_type:'discovery'}:action==='support'?{severity:'medium',category:'other'}:{}} onClose={()=>setAction(null)} onSubmit={submit}/>
  </>
}

function ProfileTable({rows,columns,empty}:{rows:any[];columns:any[];empty:string}){return rows?.length?<TeamTable rows={rows} columns={columns}/>:<TeamEmpty title="Nothing here yet" detail={empty}/>} 
