import fs from "node:fs"
import path from "node:path"
import PDFDocument from "pdfkit"

const COLORS = {
  brand: "#295f97",
  brandSoft: "#edf3fb",
  text: "#1e3f63",
  muted: "#5e7c9d",
  border: "#cfddef",
  white: "#ffffff",
  rowAlt: "#fafcff",
  warningSoft: "#fff4df",
  warningText: "#8a5a00",
  criticalSoft: "#fdecec",
  criticalText: "#b83c3c",
  infoSoft: "#e9f2fe",
  infoText: "#295f97",
}

function safeLogo() {
  const logoPath = path.resolve(process.cwd(), "..", "front-end", "public", "logo13.png")
  return fs.existsSync(logoPath) ? logoPath : null
}

function toLabel(value, fallback = "N/A") {
  if (value === null || value === undefined || value === "") return fallback
  return String(value)
}

function n(value, digits = 2) {
  const numeric = Number(value)
  if (!Number.isFinite(numeric)) return "N/A"
  return numeric.toLocaleString(undefined, {
    minimumFractionDigits: 0,
    maximumFractionDigits: digits,
  })
}

function litres(value, digits = 1) {
  const numeric = Number(value)
  if (!Number.isFinite(numeric)) return "N/A"
  return `${numeric.toLocaleString(undefined, {
    minimumFractionDigits: 0,
    maximumFractionDigits: digits,
  })} L`
}

function money(value) {
  const numeric = Number(value)
  if (!Number.isFinite(numeric)) return "N/A"
  return `MWK ${numeric.toLocaleString(undefined, { maximumFractionDigits: 0 })}`
}

function percent(value, digits = 1) {
  const numeric = Number(value)
  if (!Number.isFinite(numeric)) return "N/A"
  return `${numeric.toFixed(digits)}%`
}

function minutes(value) {
  const numeric = Number(value)
  if (!Number.isFinite(numeric)) return "N/A"
  return `${Math.max(0, Math.round(numeric))} min`
}

function badgeTheme(level) {
  const key = String(level || "INFO").toUpperCase()
  if (key === "CRITICAL" || key === "HIGH") {
    return { fill: COLORS.criticalSoft, text: COLORS.criticalText }
  }
  if (key === "WARNING" || key === "MEDIUM") {
    return { fill: COLORS.warningSoft, text: COLORS.warningText }
  }
  return { fill: COLORS.infoSoft, text: COLORS.infoText }
}

function ensureSpace(doc, heightNeeded) {
  if (doc.y + heightNeeded <= doc.page.height - doc.page.margins.bottom) return
  doc.addPage()
}

function drawHeader(doc, { station, generatedBy, targetDate }) {
  const left = doc.page.margins.left
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right
  const logo = safeLogo()

  if (logo) {
    doc.image(logo, left, doc.y, { fit: [42, 42] })
  } else {
    doc
      .save()
      .roundedRect(left, doc.y, 42, 42, 8)
      .fillAndStroke(COLORS.brandSoft, COLORS.border)
      .restore()
    doc.font("Helvetica-Bold").fontSize(12).fillColor(COLORS.brand).text("SL", left + 12, doc.y + 14)
  }

  doc.font("Helvetica-Bold").fontSize(18).fillColor(COLORS.brand)
  doc.text("SMARTLINK STATION INSIGHTS", left + 56, doc.y + 2, { width: width - 56 })
  doc.font("Helvetica").fontSize(9).fillColor(COLORS.muted)
  doc.text(
    "Predictive analytics and operational intelligence generated from station telemetry, tank readings, and transaction history.",
    left + 56,
    doc.y + 6,
    { width: width - 56, lineGap: 2 }
  )

  doc.y = Math.max(doc.y + 18, 78)
  doc
    .roundedRect(left, doc.y, width, 48, 8)
    .fillAndStroke(COLORS.white, COLORS.border)
  doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.text)
  doc.text(station?.name || station?.public_id || "Station", left + 12, doc.y + 10)
  doc.font("Helvetica").fontSize(9).fillColor(COLORS.muted)
  doc.text(`Station ID: ${toLabel(station?.public_id)}`, left + 12, doc.y + 24)
  doc.text(`Report Date: ${toLabel(targetDate)}`, left + width - 180, doc.y + 10, { width: 168, align: "right" })
  doc.text(`Generated By: ${toLabel(generatedBy, "Station Staff")}`, left + width - 180, doc.y + 24, {
    width: 168,
    align: "right",
  })
  doc.y += 62
}

function drawSectionTitle(doc, title) {
  ensureSpace(doc, 28)
  const left = doc.page.margins.left
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right
  doc
    .save()
    .roundedRect(left, doc.y, width, 22, 6)
    .fill(COLORS.brand)
    .restore()
  doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.white).text(title, left + 10, doc.y + 6)
  doc.y += 30
}

function drawFormula(doc, text) {
  ensureSpace(doc, 28)
  const left = doc.page.margins.left
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right
  doc
    .save()
    .roundedRect(left, doc.y, width, 22, 6)
    .fillAndStroke(COLORS.brandSoft, COLORS.border)
    .restore()
  doc.font("Helvetica-Bold").fontSize(9).fillColor(COLORS.text).text(text, left + 10, doc.y + 7)
  doc.y += 30
}

function drawParagraph(doc, text, options = {}) {
  if (!text) return
  ensureSpace(doc, options.minHeight || 24)
  const left = doc.page.margins.left
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right
  doc
    .font(options.bold ? "Helvetica-Bold" : "Helvetica")
    .fontSize(options.size || 9)
    .fillColor(options.color || COLORS.text)
    .text(text, left, doc.y, {
      width,
      lineGap: 2,
    })
  doc.y += options.spacingAfter || 8
}

function drawTable(doc, columns, rows, { emptyText = "No data available.", rowHeight = 20 } = {}) {
  const left = doc.page.margins.left
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right
  const safeRows = Array.isArray(rows) && rows.length ? rows : [{ __empty: true }]
  const totalWeight = columns.reduce((sum, column) => sum + (column.width || 1), 0) || 1
  const widths = columns.map((column, index) => {
    if (index === columns.length - 1) return 0
    return Math.floor((width * (column.width || 1)) / totalWeight)
  })
  const used = widths.reduce((sum, cellWidth) => sum + cellWidth, 0)
  widths[columns.length - 1] = width - used

  const drawHeader = () => {
    ensureSpace(doc, rowHeight + 4)
    doc.save()
    doc.rect(left, doc.y, width, rowHeight).fillAndStroke(COLORS.brandSoft, COLORS.border)
    let cellX = left
    columns.forEach((column, index) => {
      doc
        .font("Helvetica-Bold")
        .fontSize(8)
        .fillColor(COLORS.brand)
        .text(column.label, cellX + 6, doc.y + 6, {
          width: widths[index] - 12,
          lineBreak: false,
          ellipsis: true,
          align: column.align || "left",
        })
      if (index > 0) {
        doc.moveTo(cellX, doc.y).lineTo(cellX, doc.y + rowHeight).strokeColor(COLORS.border).stroke()
      }
      cellX += widths[index]
    })
    doc.restore()
    doc.y += rowHeight
  }

  drawHeader()

  safeRows.forEach((row, rowIndex) => {
    ensureSpace(doc, rowHeight + 2)
    if (rowIndex % 2 === 1) {
      doc.save()
      doc.rect(left, doc.y, width, rowHeight).fill(COLORS.rowAlt)
      doc.restore()
    }
    doc.rect(left, doc.y, width, rowHeight).strokeColor(COLORS.border).stroke()

    let cellX = left
    columns.forEach((column, index) => {
      const value = row.__empty ? (index === 0 ? emptyText : "") : toLabel(row[column.key], "")
      doc
        .font("Helvetica")
        .fontSize(8)
        .fillColor(COLORS.text)
        .text(value, cellX + 6, doc.y + 6, {
          width: widths[index] - 12,
          lineBreak: false,
          ellipsis: true,
          align: column.align || "left",
        })
      if (index > 0) {
        doc.moveTo(cellX, doc.y).lineTo(cellX, doc.y + rowHeight).strokeColor(COLORS.border).stroke()
      }
      cellX += widths[index]
    })

    doc.y += rowHeight
  })

  doc.y += 10
}

function drawAlertList(doc, alerts) {
  const rows = Array.isArray(alerts) ? alerts : []
  if (!rows.length) {
    drawParagraph(doc, "No active alerts.")
    return
  }

  rows.forEach((alert) => {
    ensureSpace(doc, 34)
    const left = doc.page.margins.left
    const width = doc.page.width - doc.page.margins.left - doc.page.margins.right
    const theme = badgeTheme(alert?.severity)

    doc.save()
    doc.roundedRect(left, doc.y, width, 30, 6).fillAndStroke(COLORS.white, COLORS.border)
    doc.roundedRect(left + 8, doc.y + 7, 72, 16, 8).fill(theme.fill)
    doc.restore()

    doc.font("Helvetica-Bold").fontSize(8).fillColor(theme.text).text(toLabel(alert?.severity, "INFO"), left + 18, doc.y + 12)
    doc.font("Helvetica-Bold").fontSize(9).fillColor(COLORS.text).text(toLabel(alert?.title), left + 90, doc.y + 7, {
      width: width - 100,
      lineBreak: false,
      ellipsis: true,
    })
    doc.font("Helvetica").fontSize(8).fillColor(COLORS.muted).text(toLabel(alert?.message), left + 90, doc.y + 17, {
      width: width - 100,
      lineBreak: false,
      ellipsis: true,
    })
    doc.y += 38
  })
}

export function streamInsightsPdf({ res, station, generatedBy, targetDate, snapshot }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
      bufferPages: false,
    })

    doc.on("end", resolve)
    doc.on("error", reject)
    res.on("error", reject)
    doc.pipe(res)

    drawHeader(doc, { station, generatedBy, targetDate })

    drawSectionTitle(doc, "Dashboard Overview")
    drawTable(
      doc,
      [
        { key: "metric", label: "Metric", width: 2.3 },
        { key: "value", label: "Value", width: 1.3 },
      ],
      [
        { metric: "Petrol Sold Today", value: litres(snapshot?.summary?.keyMetrics?.petrolSoldTodayLitres) },
        { metric: "Diesel Sold Today", value: litres(snapshot?.summary?.keyMetrics?.dieselSoldTodayLitres) },
        { metric: "Total Revenue", value: money(snapshot?.summary?.keyMetrics?.totalRevenue) },
        { metric: "Active Pumps", value: n(snapshot?.summary?.keyMetrics?.activePumps, 0) },
        { metric: "Current Queue", value: n(snapshot?.summary?.keyMetrics?.currentQueue, 0) },
      ]
    )

    drawSectionTitle(doc, "Fuel Demand Overview")
    drawFormula(doc, "Sales Velocity = Total Litres Sold / Time Period")
    drawTable(
      doc,
      [
        { key: "fuelType", label: "Fuel Type", width: 1.2 },
        { key: "totalLitresSold", label: "Total Litres", width: 1.2 },
        { key: "window", label: "Window", width: 0.8 },
        { key: "salesVelocityLph", label: "Sales Velocity (L/hour)", width: 1.4 },
      ],
      (snapshot?.salesVelocity?.rows || []).map((row) => ({
        fuelType: row.fuelType,
        totalLitresSold: litres(row.totalLitresSold),
        window: `${row.windowHours} hr`,
        salesVelocityLph: n(row.salesVelocityLph, 2),
      }))
    )

    drawSectionTitle(doc, "Pump Utilization")
    drawFormula(doc, "Pump Utilization = Dispensing Time / Total Time")
    drawTable(
      doc,
      [
        { key: "pump", label: "Pump", width: 0.9 },
        { key: "fuelType", label: "Fuel Type", width: 1 },
        { key: "utilization", label: "Utilization", width: 1 },
        { key: "litresSold", label: "Litres Sold", width: 1 },
      ],
      (snapshot?.pumpUtilization?.rows || []).map((row) => ({
        pump: `Pump ${row.pumpNumber}`,
        fuelType: row.fuelType,
        utilization: Number.isFinite(Number(row.utilizationPercent)) ? percent(row.utilizationPercent) : "N/A",
        litresSold: litres(row.litresSold),
      }))
    )
    ;(snapshot?.pumpUtilization?.insights || []).forEach((item) => drawParagraph(doc, `- ${item}`, { size: 8 }))

    drawSectionTitle(doc, "Fuel Inventory Prediction")
    drawFormula(doc, "Time Until Empty = Tank Remaining / Sales Velocity")
    drawTable(
      doc,
      [
        { key: "tankName", label: "Tank", width: 1.4 },
        { key: "remaining", label: "Remaining", width: 1.2 },
        { key: "velocity", label: "Velocity", width: 1 },
        { key: "stockoutEstimate", label: "Stockout Estimate", width: 1.2 },
        { key: "alertLevel", label: "Alert Level", width: 1 },
      ],
      (snapshot?.inventoryPrediction?.rows || []).map((row) => ({
        tankName: row.tankName,
        remaining: row.remainingLitres === null ? "N/A" : litres(row.remainingLitres),
        velocity: `${n(row.velocityLph, 2)} L/h`,
        stockoutEstimate: row.stockoutEstimate || "Unavailable",
        alertLevel: row.alertLevel || "UNKNOWN",
      }))
    )
    drawTable(
      doc,
      [
        { key: "level", label: "Alert Level", width: 1 },
        { key: "criteria", label: "Threshold", width: 2 },
      ],
      snapshot?.inventoryPrediction?.alertLevels || []
    )

    drawSectionTitle(doc, "Queue Demand Prediction")
    drawFormula(doc, "Cars Per Hour = Sales Velocity / Average Litres Per Car")
    drawParagraph(
      doc,
      `${toLabel(snapshot?.queuePrediction?.exampleCalculation?.salesVelocityLph, "N/A")} L/h / ${toLabel(snapshot?.queuePrediction?.exampleCalculation?.avgLitresPerCar, "N/A")} L/car = ${toLabel(snapshot?.queuePrediction?.exampleCalculation?.carsPerHour, "N/A")} cars/hour`,
      { size: 9 }
    )
    drawParagraph(doc, toLabel(snapshot?.queuePrediction?.exampleCalculation?.note, "No live throughput data available."), {
      size: 8,
      color: COLORS.muted,
    })
    drawTable(
      doc,
      [
        { key: "vehiclesInQueue", label: "Vehicles in Queue", width: 1.2 },
        { key: "estimatedWait", label: "Estimated Wait", width: 1.2 },
      ],
      (snapshot?.queuePrediction?.queueExamples || []).map((row) => ({
        vehiclesInQueue: n(row.vehiclesInQueue, 0),
        estimatedWait: minutes(row.estimatedWaitMinutes),
      }))
    )

    drawSectionTitle(doc, "Demand Forecast")
    drawTable(
      doc,
      [
        { key: "time", label: "Time", width: 0.8 },
        { key: "demandLevel", label: "Expected Demand Level", width: 1.3 },
        { key: "expectedLitres", label: "Expected Litres", width: 1 },
      ],
      (snapshot?.demandForecast?.rows || []).map((row) => ({
        time: row.time,
        demandLevel: row.demandLevel,
        expectedLitres: row.expectedLitres === null ? "N/A" : litres(row.expectedLitres),
      }))
    )
    drawParagraph(doc, toLabel(snapshot?.demandForecast?.recommendation, "No forecast recommendation available."), {
      size: 9,
    })

    drawSectionTitle(doc, "Fuel Reorder Recommendation")
    drawTable(
      doc,
      [
        { key: "fuelType", label: "Fuel Type", width: 1 },
        { key: "remaining", label: "Remaining", width: 1.1 },
        { key: "estimatedEmpty", label: "Estimated Empty", width: 1.1 },
        { key: "recommendedReorder", label: "Recommended Reorder", width: 1.3 },
      ],
      (snapshot?.inventoryPrediction?.reorder?.rows || []).map((row) => ({
        fuelType: row.fuelType,
        remaining: litres(row.remainingLitres),
        estimatedEmpty: row.estimatedEmpty,
        recommendedReorder: row.recommendedReorder,
      }))
    )
    drawParagraph(doc, toLabel(snapshot?.inventoryPrediction?.reorder?.reason, "No reorder recommendation available."), {
      size: 9,
    })

    drawSectionTitle(doc, "Operational Alerts")
    drawAlertList(doc, snapshot?.operationalAlerts?.alerts || [])

    drawSectionTitle(doc, "Sales Performance Summary")
    drawTable(
      doc,
      [
        { key: "metric", label: "Metric", width: 2.1 },
        { key: "value", label: "Value", width: 1.2 },
      ],
      [
        { metric: "Total Fuel Sold", value: litres(snapshot?.summary?.salesPerformance?.totalFuelSoldLitres) },
        { metric: "Petrol Transactions", value: n(snapshot?.summary?.salesPerformance?.petrolTransactions, 0) },
        { metric: "Diesel Transactions", value: n(snapshot?.summary?.salesPerformance?.dieselTransactions, 0) },
        {
          metric: "Average Fuel per Vehicle",
          value: litres(snapshot?.summary?.salesPerformance?.averageFuelPerVehicleLitres),
        },
      ]
    )

    drawSectionTitle(doc, "Demand Heatmap")
    drawTable(
      doc,
      [
        { key: "time", label: "Time", width: 1 },
        { key: "demandLevel", label: "Demand Level", width: 1.6 },
      ],
      snapshot?.demandForecast?.heatmap?.rows || []
    )
    drawParagraph(doc, toLabel(snapshot?.demandForecast?.heatmap?.purpose, "No heatmap guidance available."), {
      size: 9,
    })

    drawSectionTitle(doc, "Key Insight")
    drawParagraph(doc, toLabel(snapshot?.operationalAlerts?.keyInsight?.headline, "No key insight available."), {
      bold: true,
      size: 11,
      minHeight: 26,
    })
    drawParagraph(doc, toLabel(snapshot?.operationalAlerts?.keyInsight?.detail, "No detail available."), {
      size: 9,
    })
    drawParagraph(
      doc,
      `Recommended Action: ${toLabel(snapshot?.operationalAlerts?.keyInsight?.action, "No action available.")}`,
      {
        bold: true,
        size: 9,
      }
    )

    doc.end()
  })
}
