import { useEffect, useState } from 'react'
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from './ui/dialog'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Textarea } from './ui/textarea'
const select='h-9 rounded-[7px] border border-[#d8dee8] bg-white px-3 text-[12px] text-[#334155]'; const label='grid gap-1.5 text-[11px] font-bold uppercase tracking-[.08em] text-[#64748b]'
export function OperationalActionModal({open,onOpenChange,type,row,staff,api,token,onDone}:any){
 const [form,setForm]=useState<any>({}); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{if(!open)return; const teacher=staff.find((u:any)=>String(u.id)===String(row?.teacher_id))||staff.find((u:any)=>u.public_ref===row?.teacher_public_ref); const name=row?.student_name||row?.teacher_name||row?.subject_name||row?.assessment_name||row?.full_name||'this record'; setForm({recipient_user_ref:teacher?.public_ref||row?.staff_ref||'',title:type==='escalate'?`Escalation: ${name}`:`Reminder: ${name}`,message:type==='escalate'?`Please review and follow up on ${name}, then update the Director.`:`Please act on ${name} and update the assigned follow-up.`,priority:type==='escalate'?'high':'medium',channel:'in_app',due_date:'',create_follow_up:true,promised_amount:row?.balance||row?.outstanding_balance||'',promised_date:'',guardian_name:row?.guardian_name||'',guardian_phone:row?.guardian_contact||'',status:'present',check_in_time:new Date().toTimeString().slice(0,5),notes:''})},[open,type,row,staff])
 const submit=async()=>{setSaving(true);setError('');try{let result;if(type==='reminder')result=await api.sendOperationalReminder(token,{...form,category:'academics',linked_entity_type:row?.teacher_name?'teacher':'record',context_snapshot:row});else if(type==='escalate')result=await api.escalateToHeadteacher(token,{...form,category:'academics',context_snapshot:row});else if(type==='fee')result=await api.sendFeeReminder(token,{...form,student_ref:row?.student_public_ref,assigned_to_user_id:form.assigned_to_user_id||null});else if(type==='promise')result=await api.createPaymentPromise(token,{...form,student_ref:row?.student_public_ref});else if(type==='attendance')result=await api.recordStaffAttendance(token,{...form,staff_user_ref:row?.staff_ref||form.recipient_user_ref});onDone?.(result);onOpenChange(false)}catch(e:any){setError(e?.message||'Unable to complete action.')}finally{setSaving(false)}}
 const title=type==='reminder'?'Send reminder':type==='escalate'?'Escalate to Headteacher':type==='fee'?'Send fee reminder':type==='promise'?'Record promise to pay':'Record staff attendance'
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-[620px]"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>This action writes to the backend and creates the appropriate notification, outbox, task, or attendance record.</DialogDescription></DialogHeader><div className="grid gap-3 py-2">
  {type==='reminder'?<label className={label}>Recipient<select className={select} value={form.recipient_user_ref||''} onChange={e=>setForm({...form,recipient_user_ref:e.target.value})}><option value="">Select staff member</option>{staff.filter((u:any)=>['teacher','headteacher'].includes(u.role)).map((u:any)=><option key={u.public_ref} value={u.public_ref}>{u.full_name}</option>)}</select></label>:null}
  {['reminder','escalate','fee'].includes(type)?<><label className={label}>Title<Input value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className={label}>Message preview<Textarea rows={4} value={form.message||''} onChange={e=>setForm({...form,message:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-3"><label className={label}>Priority<select className={select} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['low','medium','high','urgent'].map(v=><option key={v}>{v}</option>)}</select></label>{type!=='escalate'?<label className={label}>Channel<select className={select} value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}><option value="in_app">In-app</option><option value="whatsapp">WhatsApp</option></select></label>:null}<label className={label}>Due date<Input type="date" value={form.due_date||''} onChange={e=>setForm({...form,due_date:e.target.value})}/></label></div>{type!=='escalate'?<label className="flex items-center gap-2 text-[12px] font-semibold text-[#475569]"><input type="checkbox" checked={Boolean(form.create_follow_up)} onChange={e=>setForm({...form,create_follow_up:e.target.checked})}/>Create assigned follow-up task</label>:null}</>:null}
  {type==='promise'?<><label className={label}>Guardian name<Input value={form.guardian_name||''} onChange={e=>setForm({...form,guardian_name:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-2"><label className={label}>Promised amount<Input type="number" value={form.promised_amount||''} onChange={e=>setForm({...form,promised_amount:e.target.value})}/></label><label className={label}>Promised date<Input type="date" value={form.promised_date||''} onChange={e=>setForm({...form,promised_date:e.target.value})}/></label></div><label className={label}>Note<Textarea value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label></>:null}
  {type==='attendance'?<><label className={label}>Status<select className={select} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['present','late','absent','excused','on_leave'].map(v=><option key={v} value={v}>{v.replace('_',' ')}</option>)}</select></label><label className={label}>Check-in time<Input type="time" value={form.check_in_time||''} onChange={e=>setForm({...form,check_in_time:e.target.value})}/></label><label className={label}>Notes<Textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label></>:null}
  {form.channel==='whatsapp'?<div className="rounded-[6px] border border-[#fed7aa] bg-[#fff7ed] px-3 py-2 text-[12px] text-[#9a3412]">If WhatsApp is not configured or the phone number is missing, the message is recorded as skipped and the in-app reminder still succeeds.</div>:null}{error?<div className="rounded-[6px] border border-[#fecaca] bg-[#fef2f2] px-3 py-2 text-[12px] text-[#b91c1c]">{error}</div>:null}</div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={saving} onClick={submit}>{saving?'Saving…':'Confirm action'}</Button></DialogFooter></DialogContent></Dialog>
}
