const defaultPrices = [
  { label: 'Petrol', value: 'MK 2,680/L' },
  { label: 'Diesel', value: 'MK 2,590/L' },
  { label: 'Premium', value: 'MK 2,760/L' },
  { label: 'Petrol 2', value: 'MK 2,700/L' },
  { label: 'Diesel 2', value: 'MK 2,610/L' },
  { label: 'Premium 2', value: 'MK 2,780/L' },
]

function createStation(station) {
  return {
    ...station,
    reviews: station.reviewsCount,
    prices: station.prices || defaultPrices,
    workingHours: station.workingHours || 'Mon - Sun 00:00 - 23:59',
    facilities: station.facilities || ['Cars', 'Car Repair'],
    phone: station.phone || '+265 1 000 000',
  }
}

export const stations = [
  createStation({
    id: 'bp-ginnery-corner',
    name: 'BP Ginnery Corner',
    chipLabel: 'BP Ginnery',
    address: 'Masauko Chipembere Hwy, Blantyre',
    lat: -15.7858,
    lng: 35.0036,
    distanceKm: 1.4,
    etaMin: 6,
    rating: 4.6,
    reviewsCount: 126,
    status: 'In Use',
    fuelLevel: 'medium',
    hoursLabel: 'Open 24h',
    pin: { x: 52, y: 36 },
    phone: '+265 999 111 120',
  }),
  createStation({
    id: 'total-chichiri',
    name: 'TotalEnergies Chichiri',
    chipLabel: 'Total Chichiri',
    address: 'M1, Chichiri, Blantyre',
    lat: -15.7953,
    lng: 35.0214,
    distanceKm: 2.8,
    etaMin: 10,
    rating: 4.5,
    reviewsCount: 98,
    status: 'Available',
    fuelLevel: 'medium',
    hoursLabel: 'Until 22:00',
    pin: { x: 67, y: 32 },
    prices: [
      { label: 'Petrol', value: 'MK 2,670/L' },
      { label: 'Diesel', value: 'MK 2,580/L' },
      { label: 'Premium', value: 'MK 2,745/L' },
      { label: 'Petrol 2', value: 'MK 2,695/L' },
      { label: 'Diesel 2', value: 'MK 2,605/L' },
      { label: 'Premium 2', value: 'MK 2,770/L' },
    ],
    workingHours: 'Mon - Sun 05:00 - 22:00',
    facilities: ['Car', 'Restaurant'],
    phone: '+265 999 311 901',
  }),
  createStation({
    id: 'puma-limbe',
    name: 'Puma Limbe Market',
    chipLabel: 'Puma Limbe',
    address: 'Limbe, Blantyre',
    lat: -15.8171,
    lng: 35.0482,
    distanceKm: 4.1,
    etaMin: 14,
    rating: 4.4,
    reviewsCount: 77,
    status: 'Available',
    fuelLevel: 'low',
    hoursLabel: 'Open 24h',
    pin: { x: 79, y: 47 },
    phone: '+265 888 450 120',
  }),
  createStation({
    id: 'engen-naperi',
    name: 'Engen Naperi',
    chipLabel: 'Engen Naperi',
    address: 'Naperi, Blantyre',
    lat: -15.7794,
    lng: 35.0028,
    distanceKm: 1.2,
    etaMin: 5,
    rating: 4.7,
    reviewsCount: 141,
    status: 'Available',
    fuelLevel: 'high',
    hoursLabel: 'Open 24h',
    pin: { x: 49, y: 30 },
    prices: [
      { label: 'Petrol', value: 'MK 2,660/L' },
      { label: 'Diesel', value: 'MK 2,575/L' },
      { label: 'Premium', value: 'MK 2,740/L' },
      { label: 'Petrol 2', value: 'MK 2,685/L' },
      { label: 'Diesel 2', value: 'MK 2,595/L' },
      { label: 'Premium 2', value: 'MK 2,760/L' },
    ],
    facilities: ['Car', 'Car Repair'],
    phone: '+265 999 020 881',
  }),
  createStation({
    id: 'chitawira-service',
    name: 'Chitawira Service Station',
    chipLabel: 'Chitawira',
    address: 'Chitawira, Blantyre',
    lat: -15.8079,
    lng: 35.0039,
    distanceKm: 2.6,
    etaMin: 9,
    rating: 4.3,
    reviewsCount: 64,
    status: 'In Use',
    fuelLevel: 'low',
    hoursLabel: 'Until 23:00',
    pin: { x: 54, y: 44 },
    prices: [
      { label: 'Petrol', value: 'MK 2,700/L' },
      { label: 'Diesel', value: 'MK 2,620/L' },
      { label: 'Premium', value: 'MK 2,790/L' },
      { label: 'Petrol 2', value: 'MK 2,725/L' },
      { label: 'Diesel 2', value: 'MK 2,640/L' },
      { label: 'Premium 2', value: 'MK 2,810/L' },
    ],
    workingHours: 'Mon - Sun 06:00 - 23:00',
    facilities: ['Car', 'Restaurant'],
    phone: '+265 999 441 331',
  }),
  createStation({
    id: 'kameza-fuel-stop',
    name: 'Kameza Fuel Stop',
    chipLabel: 'Kameza',
    address: 'Kameza Roundabout, Blantyre',
    lat: -15.8328,
    lng: 35.0241,
    distanceKm: 5.2,
    etaMin: 17,
    rating: 4.2,
    reviewsCount: 52,
    status: 'Available',
    fuelLevel: 'medium',
    hoursLabel: 'Until 22:30',
    pin: { x: 71, y: 60 },
    workingHours: 'Mon - Sun 05:00 - 22:30',
    facilities: ['Car', 'Restaurant'],
    phone: '+265 888 771 420',
  }),
  createStation({
    id: 'chileka-road-depot',
    name: 'Chileka Road Depot',
    chipLabel: 'Chileka Road',
    address: 'Chileka Rd, Blantyre',
    lat: -15.8072,
    lng: 34.9736,
    distanceKm: 4.9,
    etaMin: 16,
    rating: 4.1,
    reviewsCount: 46,
    status: 'Available',
    fuelLevel: 'low',
    hoursLabel: 'Open 24h',
    pin: { x: 34, y: 46 },
    facilities: ['Car', 'Car Repair'],
    phone: '+265 999 559 230',
  }),
]

export function getStationById(stationId) {
  return stations.find((station) => station.id === stationId) || null
}
