import test from "node:test"
import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"

const source = await readFile(new URL("../src/services/academicIntelligenceEngine.js", import.meta.url), "utf8")
const termScopeMigration = await readFile(new URL("../database/055_academic_intelligence_term_scoping.sql", import.meta.url), "utf8")
const evidenceScopeMigration = await readFile(new URL("../database/056_academic_evidence_session_scope.sql", import.meta.url), "utf8")
const masteryScopeMigration = await readFile(new URL("../database/060_learner_support_cases.sql", import.meta.url), "utf8")

test("teacher parent-insight reads and drafts follow the active learner class-subject assignment", () => {
  const studentStart = source.indexOf("export async function getStudentAcademicIntelligence")
  const createStart = source.indexOf("export async function createParentAcademicInsight")
  const updateStart = source.indexOf("export async function updateParentAcademicInsight")
  const reads = source.slice(studentStart, createStart)
  const creates = source.slice(createStart, updateStart)
  assert.match(reads, /tcsa\.academic_year_id=se\.academic_year_id/)
  assert.match(reads, /tcsa\.term_id=se\.term_id/)
  assert.doesNotMatch(reads, /tcsa\.academic_year_id IS NULL/)
  assert.doesNotMatch(reads, /tcsa\.term_id IS NULL/)
  assert.match(reads, /current_year\.is_active=1/)
  assert.match(reads, /current_term\.status IN \('open','marking'\)/)
  assert.match(reads, /subj\.public_ref subject_ref/)
  assert.match(reads, /subj\.id subject_id/)
  assert.match(reads, /available_subjects: availableSubjects/)
  assert.match(reads, /amr\.academic_year_id=\? AND amr\.term_id=\? AND amr\.subject_id IN/)
  assert.match(reads, /me\.academic_year_id=\? AND me\.term_id=\? AND me\.subject_id IN/)
  assert.match(reads, /ai\.term_id=\? AND ai\.subject_id IN/)
  assert.match(reads, /ar\.term_id=\? AND ar\.subject_id IN/)
  assert.match(reads, /ers\.academic_year_id=\? AND ers\.term_id=\? AND ers\.subject_id IN/)
  assert.match(reads, /pai\.subject_id IN/)
  assert.doesNotMatch(reads, /allowedSubjects/)
  assert.doesNotMatch(reads, /row\.subject_name&&allowedSubjects/)
  assert.match(creates, /Select one of your assigned subjects before preparing a parent update/)
  assert.match(creates, /assertAcademicActorWriteScope\(pool,schoolId,actor/)
  assert.match(creates, /SELECT id,public_ref FROM subjects/)
  assert.match(creates, /row\.subject_ref===subjectRef/)
  assert.doesNotMatch(creates, /row\.subject_name===subjectName/)
  assert.match(creates, /enrollment\.enrollment_status='active'/)
  assert.match(creates, /current_year\.is_active=1/)
  assert.match(creates, /current_term\.status IN \('open','marking'\)/)
  assert.match(creates, /ORDER BY current_term\.id IS NULL/)
})

test("canonical teacher evidence is limited to the exact active assignment session", () => {
  const start = source.indexOf("export async function getCanonicalAcademicEvidence")
  const end = source.indexOf("async function audit", start)
  const evidence = source.slice(start, end)
  assert.match(evidence, /requireActiveAcademicSession\(schoolId, pool\)/)
  assert.match(evidence, /me\.academic_year_id=\? AND me\.term_id=\?/)
  assert.match(evidence, /tcsa\.academic_year_id=me\.academic_year_id/)
  assert.match(evidence, /tcsa\.term_id=me\.term_id/)
  assert.doesNotMatch(evidence, /tcsa\.academic_year_id IS NULL/)
  assert.doesNotMatch(evidence, /tcsa\.term_id IS NULL/)
})

test("teacher intelligence session predicates are backed by schema migrations", () => {
  assert.match(termScopeMigration, /ALTER TABLE academic_recommendations[\s\S]*ADD COLUMN IF NOT EXISTS term_id/)
  assert.match(termScopeMigration, /ALTER TABLE academic_interventions[\s\S]*ADD COLUMN IF NOT EXISTS term_id/)
  assert.match(evidenceScopeMigration, /ALTER TABLE mastery_evidence[\s\S]*ADD COLUMN IF NOT EXISTS academic_year_id[\s\S]*ADD COLUMN IF NOT EXISTS term_id/)
  assert.match(masteryScopeMigration, /ALTER TABLE academic_mastery_records[\s\S]*ADD COLUMN IF NOT EXISTS academic_year_id[\s\S]*ADD COLUMN IF NOT EXISTS term_id/)
})

test("teachers cannot approve, publish, or edit another teacher's parent update", () => {
  const start = source.indexOf("export async function updateParentAcademicInsight")
  const end = source.indexOf("export async function getParentPortalAcademicInsights", start)
  const update = source.slice(start, end)
  assert.match(update, /Number\(before\.created_by\)!==Number\(actor\.id\)/)
  assert.match(update, /before\.status!=='draft'\|\|status!=='draft'/)
  assert.match(update, /approved and published by academic leadership/)
  assert.match(update, /assignment\.role='subject_teacher'/)
  assert.match(update, /assignment\.academic_year_id=\?/)
  assert.match(update, /assignment\.term_id=\?/)
  assert.doesNotMatch(update, /assignment\.academic_year_id IS NULL/)
  assert.doesNotMatch(update, /assignment\.term_id IS NULL/)
  assert.match(update, /ORDER BY current_term\.id IS NULL/)
})
