import { randomUUID } from "crypto"
import { pool } from "../config/db.js"
import { safeTeamRequestMetadata } from "../middleware/teamAuth.js"
import {
  TEAM_PERMISSIONS,
  assertTeamSchoolAccess,
  hasTeamPermission,
  isPlatformOwner,
} from "../services/teamAccessService.js"
import {
  REQUIRED_GO_LIVE_ITEMS,
  createTeamNotification,
  deriveSubscriptionStatus,
  enumValue,
  insertOnboardingChecklist,
  nullableDate,
  numberInRange,
  optionalText,
  paginationFrom,
  paginationMeta,
  recalculateOnboardingProgress,
  requiredText,
  writeTeamAudit,
} from "../services/teamSuiteService.js"
import { HttpError } from "../utils/http.js"

const PROPOSAL_STATUSES=["draft","awaiting_approval","approved","sent","viewed","accepted","rejected","expired","replaced"]
const ONBOARDING_STAGES=["contract_signed","initial_payment_pending","initial_payment_received","implementation_assigned","discovery_completed","school_configuration","data_templates_issued","data_received","migration_in_progress","migration_validation","user_accounts_created","administrator_training","bursar_training","teacher_training","pilot_testing","issues_being_resolved","go_live_approval","live","post_launch_monitoring","complete"]
const RISK_STATUSES=["on_track","watch","at_risk","blocked"]
const SUBSCRIPTION_STATUSES=["pending","active","renewal_approaching","payment_overdue","grace_period","expired","read_only","cancelled"]
const INVOICE_STATUSES=["not_issued","draft","issued","part_paid","paid","void"]
const PAYMENT_STATUSES=["pending","part_paid","paid","overdue","waived"]

function value(body,snake,camel=snake){return body?.[snake]??body?.[camel]}

async function userId(connection,ref,label){const [[user]]=await connection.query("SELECT id FROM team_users WHERE public_ref=? AND is_active=1 LIMIT 1",[requiredText(ref,label,36)]);if(!user)throw new HttpError(400,`${label} is invalid`);return Number(user.id)}

async function opportunityByRef(connection,ref,{lock=false}={}){
  const [[opportunity]]=await connection.query(`SELECT opportunity.*,school.public_ref school_ref,school.name school_name,owner.public_ref owner_ref,implementation.public_ref implementation_owner_ref FROM team_sales_opportunities opportunity JOIN team_school_prospects school ON school.id=opportunity.school_id JOIN team_users owner ON owner.id=opportunity.assigned_owner_id LEFT JOIN team_users implementation ON implementation.id=opportunity.implementation_owner_id WHERE opportunity.public_ref=? AND opportunity.archived_at IS NULL LIMIT 1 ${lock?"FOR UPDATE":""}`,[requiredText(ref,"Opportunity",36)])
  if(!opportunity)throw new HttpError(404,"Opportunity was not found")
  return opportunity
}

function proposalTotals(body){
  const setup=numberInRange(value(body,"setup_fee","setupFee"),"Setup fee",0,999999999999,0)
  const term=numberInRange(value(body,"term_subscription","termSubscription"),"Term subscription",0,999999999999,0)
  const training=numberInRange(value(body,"training_fee","trainingFee"),"Training fee",0,999999999999,0)
  const migration=numberInRange(value(body,"migration_fee","migrationFee"),"Migration fee",0,999999999999,0)
  const website=numberInRange(value(body,"website_fee","websiteFee"),"Website fee",0,999999999999,0)
  const optional=numberInRange(value(body,"optional_services_total","optionalServicesTotal"),"Optional services",0,999999999999,0)
  const original=Math.round((setup+term+training+migration+website+optional)*100)/100
  const discount=numberInRange(value(body,"requested_discount","requestedDiscount"),"Requested discount",0,original,0)
  return{setup,term,training,migration,website,optional,original,discount,final:Math.round((original-discount)*100)/100}
}

async function proposalWithRelations(connection,publicRef){
  const [[proposal]]=await connection.query(`SELECT proposal.*,school.public_ref school_ref,school.name school_name,opportunity.public_ref opportunity_ref,opportunity.title opportunity_title,recipient.public_ref recipient_ref,recipient.full_name recipient_name,preparer.public_ref prepared_by_ref,preparer.full_name prepared_by_name,approver.public_ref approved_by_ref,approver.full_name approved_by_name FROM team_proposals proposal JOIN team_school_prospects school ON school.id=proposal.school_id JOIN team_sales_opportunities opportunity ON opportunity.id=proposal.opportunity_id JOIN team_school_contacts recipient ON recipient.id=proposal.recipient_contact_id JOIN team_users preparer ON preparer.id=proposal.prepared_by LEFT JOIN team_users approver ON approver.id=proposal.approved_by WHERE proposal.public_ref=? LIMIT 1`,[publicRef])
  if(!proposal)throw new HttpError(404,"Proposal was not found")
  const [[modules],[approvals]]=await Promise.all([connection.query("SELECT module_code,module_name,amount FROM team_proposal_modules WHERE proposal_id=? ORDER BY module_name",[proposal.id]),connection.query(`SELECT approval.*,requester.full_name requested_by_name,decider.full_name decided_by_name FROM team_proposal_approvals approval JOIN team_users requester ON requester.id=approval.requested_by LEFT JOIN team_users decider ON decider.id=approval.decided_by WHERE approval.proposal_id=? ORDER BY approval.created_at DESC`,[proposal.id])])
  return{proposal,modules,approvals}
}

export async function listTeamProposals(req,res){
  const pagination=paginationFrom(req.query);const clauses=[];const params=[]
  if(!hasTeamPermission(req.teamUser,TEAM_PERMISSIONS.SCHOOLS_VIEW_ALL)){clauses.push("(proposal.prepared_by=? OR opportunity.assigned_owner_id=? OR opportunity.implementation_owner_id=?)");params.push(req.teamUser.id,req.teamUser.id,req.teamUser.id)}
  if(req.query.status){clauses.push("proposal.status=?");params.push(enumValue(req.query.status,PROPOSAL_STATUSES,"Proposal status"))}
  if(String(req.query.awaiting_approval||"")==="true")clauses.push("proposal.status='awaiting_approval'")
  const where=clauses.length?clauses.join(" AND "):"1=1"
  const [[count],[rows]]=await Promise.all([
    pool.query(`SELECT COUNT(*) total FROM team_proposals proposal JOIN team_sales_opportunities opportunity ON opportunity.id=proposal.opportunity_id WHERE ${where}`,params),
    pool.query(`SELECT proposal.public_ref,proposal.proposal_number,proposal.package_name,proposal.original_amount,proposal.requested_discount,proposal.approved_discount,proposal.final_amount,proposal.expires_at,proposal.status,proposal.created_at,school.public_ref school_ref,school.name school_name,opportunity.public_ref opportunity_ref,opportunity.title opportunity_title,preparer.full_name prepared_by_name,approver.full_name approved_by_name FROM team_proposals proposal JOIN team_school_prospects school ON school.id=proposal.school_id JOIN team_sales_opportunities opportunity ON opportunity.id=proposal.opportunity_id JOIN team_users preparer ON preparer.id=proposal.prepared_by LEFT JOIN team_users approver ON approver.id=proposal.approved_by WHERE ${where} ORDER BY FIELD(proposal.status,'awaiting_approval','approved','draft','sent','viewed','accepted','rejected','expired','replaced'),proposal.created_at DESC LIMIT ? OFFSET ?`,[...params,pagination.pageSize,pagination.offset]),
  ])
  res.json({items:rows,pagination:paginationMeta(count.total,pagination)})
}

export async function getTeamProposal(req,res){const data=await proposalWithRelations(pool,req.params.proposalRef);await assertTeamSchoolAccess(pool,req.teamUser,data.proposal.school_id);res.json(data)}

export async function createTeamProposal(req,res){
  const connection=await pool.getConnection()
  try{
    await connection.beginTransaction()
    const opportunity=await opportunityByRef(connection,value(req.body,"opportunity_ref","opportunityRef"),{lock:true});await assertTeamSchoolAccess(connection,req.teamUser,opportunity.school_id)
    const recipientRef=optionalText(value(req.body,"recipient_ref","recipientRef"),36)
    const [[recipient]]=recipientRef
      ? await connection.query("SELECT id FROM team_school_contacts WHERE public_ref=? AND school_id=? AND is_active=1 LIMIT 1",[recipientRef,opportunity.school_id])
      : await connection.query("SELECT id FROM team_school_contacts WHERE school_id=? AND is_active=1 ORDER BY decision_authority='final' DESC,last_contacted_at DESC,id LIMIT 1",[opportunity.school_id])
    if(!recipient)throw new HttpError(400,"Add an active school contact before creating a proposal")
    const modules=Array.isArray(req.body?.modules)?req.body.modules:[];if(!modules.length)throw new HttpError(400,"At least one proposal module is required")
    const totals=proposalTotals(req.body)
    const expiresAt=nullableDate(value(req.body,"expires_at","expiresAt"),"Proposal expiry date");if(!expiresAt)throw new HttpError(400,"Proposal expiry date is required")
    const proposalNumber=`SLP-${new Date().getFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`
    const [result]=await connection.query(`INSERT INTO team_proposals (public_ref,proposal_number,school_id,opportunity_id,package_name,campus_count,estimated_students,setup_fee,term_subscription,training_fee,migration_fee,website_fee,optional_services_total,original_amount,requested_discount,approved_discount,final_amount,payment_terms,expires_at,prepared_by,recipient_contact_id,status,attachment_ref,internal_notes) VALUES (UUID(),?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?,'draft',?,?)`,[proposalNumber,opportunity.school_id,opportunity.id,requiredText(value(req.body,"package_name","packageName"),"Package",160),numberInRange(value(req.body,"campus_count","campusCount"),"Campus count",1,1000,1),numberInRange(value(req.body,"estimated_students","estimatedStudents"),"Estimated students",0,1000000),totals.setup,totals.term,totals.training,totals.migration,totals.website,totals.optional,totals.original,totals.discount,totals.final,requiredText(value(req.body,"payment_terms","paymentTerms"),"Payment terms",5000),expiresAt,req.teamUser.id,recipient.id,optionalText(value(req.body,"attachment_ref","attachmentRef"),500),optionalText(value(req.body,"internal_notes","internalNotes"),10000)])
    for(const module of modules){const code=requiredText(module.code||module.module_code||module.name,"Module code",100).toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");await connection.query("INSERT INTO team_proposal_modules (proposal_id,module_code,module_name,amount) VALUES (?,?,?,?)",[result.insertId,code,requiredText(module.name||module.module_name,"Module name",180),numberInRange(module.amount,"Module amount",0,999999999999,0)])}
    const data=await proposalWithRelations(connection,(await connection.query("SELECT public_ref FROM team_proposals WHERE id=?",[result.insertId]))[0][0].public_ref)
    await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:"PROPOSAL_CREATED",entityType:"proposal",entityId:data.proposal.id,entityRef:data.proposal.public_ref,schoolId:opportunity.school_id,afterValue:{...data.proposal,modules:data.modules},...safeTeamRequestMetadata(req)})
    await connection.commit();res.status(201).json(data)
  }catch(error){await connection.rollback();throw error}finally{connection.release()}
}

export async function submitTeamProposal(req,res){
  const connection=await pool.getConnection()
  try{
    await connection.beginTransaction();const data=await proposalWithRelations(connection,req.params.proposalRef);const proposal=data.proposal;await assertTeamSchoolAccess(connection,req.teamUser,proposal.school_id)
    if(proposal.status!=="draft")throw new HttpError(409,"Only a draft proposal can be submitted")
    if(!data.modules.length||!proposal.payment_terms||!proposal.recipient_contact_id||!proposal.expires_at)throw new HttpError(400,"Complete modules, payment terms, recipient and expiry before submitting")
    const needsApproval=Number(proposal.requested_discount)>0
    const status=needsApproval?"awaiting_approval":"approved"
    await connection.query(`UPDATE team_proposals SET status=?,approved_discount=?,approved_by=?,approved_at=? WHERE id=?`,[status,0,needsApproval?null:req.teamUser.id,needsApproval?null:new Date(),proposal.id])
    if(needsApproval){
      const reason=requiredText(req.body?.reason,"Discount reason",5000)
      await connection.query("INSERT INTO team_proposal_approvals (public_ref,proposal_id,requested_by,requested_discount,reason) VALUES (UUID(),?,?,?,?)",[proposal.id,req.teamUser.id,proposal.requested_discount,reason])
      const [approvers]=await connection.query(`SELECT DISTINCT user_role.user_id FROM team_user_roles user_role JOIN team_role_permissions role_permission ON role_permission.role_id=user_role.role_id JOIN team_permissions permission ON permission.id=role_permission.permission_id JOIN team_users user ON user.id=user_role.user_id AND user.is_active=1 WHERE permission.code='DISCOUNTS_APPROVE'`)
      for(const approver of approvers)if(approver.user_id!==req.teamUser.id)await createTeamNotification(connection,{recipientUserId:approver.user_id,type:"discount_awaiting_approval",title:"Discount approval requested",message:`${proposal.proposal_number} requests a discount.`,entityType:"proposal",entityRef:proposal.public_ref,actionPath:"/team/proposals?status=awaiting_approval"})
    }
    await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:"PROPOSAL_SUBMITTED",entityType:"proposal",entityId:proposal.id,entityRef:proposal.public_ref,schoolId:proposal.school_id,beforeValue:{status:proposal.status},afterValue:{status,requested_discount:proposal.requested_discount},reason:req.body?.reason,...safeTeamRequestMetadata(req)})
    await connection.commit();res.json(await proposalWithRelations(pool,proposal.public_ref))
  }catch(error){await connection.rollback();throw error}finally{connection.release()}
}

export async function decideTeamProposal(req,res){
  const decision=enumValue(req.body?.decision,["approved","rejected"],"Decision")
  const connection=await pool.getConnection()
  try{
    await connection.beginTransaction();const data=await proposalWithRelations(connection,req.params.proposalRef);const proposal=data.proposal
    if(proposal.status!=="awaiting_approval")throw new HttpError(409,"This proposal is not awaiting approval")
    const [[approval]]=await connection.query("SELECT * FROM team_proposal_approvals WHERE proposal_id=? AND status='pending' ORDER BY created_at DESC LIMIT 1 FOR UPDATE",[proposal.id]);if(!approval)throw new HttpError(409,"No pending approval request was found")
    if(approval.requested_by===req.teamUser.id&&!isPlatformOwner(req.teamUser))throw new HttpError(403,"You cannot approve your own restricted discount request")
    const approvedDiscount=decision==="approved"?Number(approval.requested_discount):0
    const finalAmount=Math.max(0,Number(proposal.original_amount)-approvedDiscount)
    await connection.query("UPDATE team_proposal_approvals SET status=?,decided_by=?,decided_at=CURRENT_TIMESTAMP,decision_note=? WHERE id=?",[decision,req.teamUser.id,optionalText(req.body?.note,5000),approval.id])
    await connection.query("UPDATE team_proposals SET status=?,approved_discount=?,final_amount=?,approved_by=?,approved_at=CASE WHEN ?='approved' THEN CURRENT_TIMESTAMP ELSE NULL END,approval_reason=? WHERE id=?",[decision,approvedDiscount,finalAmount,decision==="approved"?req.teamUser.id:null,decision,optionalText(req.body?.note,5000),proposal.id])
    await createTeamNotification(connection,{recipientUserId:approval.requested_by,type:`proposal_${decision}`,title:`Proposal ${decision}`,message:proposal.proposal_number,entityType:"proposal",entityRef:proposal.public_ref,actionPath:"/team/proposals"})
    await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:decision==="approved"?"DISCOUNT_APPROVED":"DISCOUNT_REJECTED",entityType:"proposal",entityId:proposal.id,entityRef:proposal.public_ref,schoolId:proposal.school_id,beforeValue:{status:proposal.status,final_amount:proposal.final_amount},afterValue:{status:decision,approved_discount:approvedDiscount,final_amount:finalAmount},reason:req.body?.note,...safeTeamRequestMetadata(req)})
    await connection.commit();res.json(await proposalWithRelations(pool,proposal.public_ref))
  }catch(error){await connection.rollback();throw error}finally{connection.release()}
}

export async function markTeamProposalSent(req,res){
  const connection=await pool.getConnection()
  try{
    await connection.beginTransaction();const data=await proposalWithRelations(connection,req.params.proposalRef);const proposal=data.proposal;await assertTeamSchoolAccess(connection,req.teamUser,proposal.school_id)
    if(proposal.status!=="approved")throw new HttpError(409,"Only an approved proposal can be marked as sent")
    await connection.query("UPDATE team_proposals SET status='sent' WHERE id=?",[proposal.id]);await connection.query(`INSERT INTO team_school_activities (public_ref,school_id,opportunity_id,activity_type,occurred_at,team_user_id,summary,notes) VALUES (UUID(),?,?,'proposal_sent',CURRENT_TIMESTAMP,?,?,?)`,[proposal.school_id,proposal.opportunity_id,req.teamUser.id,`Proposal ${proposal.proposal_number} sent`,optionalText(req.body?.note,5000)]);await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:"PROPOSAL_SENT",entityType:"proposal",entityId:proposal.id,entityRef:proposal.public_ref,schoolId:proposal.school_id,beforeValue:{status:"approved"},afterValue:{status:"sent"},...safeTeamRequestMetadata(req)});await connection.commit();res.json(await proposalWithRelations(pool,proposal.public_ref))
  }catch(error){await connection.rollback();throw error}finally{connection.release()}
}

async function onboardingWithChecklist(connection,publicRef){const [[project]]=await connection.query(`SELECT project.*,school.public_ref school_ref,school.name school_name,opportunity.public_ref opportunity_ref,opportunity.title opportunity_title,owner.public_ref implementation_owner_ref,owner.full_name implementation_owner_name FROM team_onboarding_projects project JOIN team_school_prospects school ON school.id=project.school_id JOIN team_sales_opportunities opportunity ON opportunity.id=project.opportunity_id JOIN team_users owner ON owner.id=project.implementation_owner_id WHERE project.public_ref=? LIMIT 1`,[publicRef]);if(!project)throw new HttpError(404,"Onboarding project was not found");const [checklist]=await connection.query(`SELECT item.public_ref,item.item_code,item.label,item.sort_order,item.is_required,item.is_complete,item.completed_at,item.notes,assignee.full_name assigned_user_name,actor.full_name completed_by_name FROM team_onboarding_checklist_items item LEFT JOIN team_users assignee ON assignee.id=item.assigned_user_id LEFT JOIN team_users actor ON actor.id=item.completed_by WHERE item.project_id=? ORDER BY item.sort_order`,[project.id]);return{project,checklist}}

export async function listTeamOnboarding(req,res){const pagination=paginationFrom(req.query);const clauses=[];const params=[];if(!hasTeamPermission(req.teamUser,TEAM_PERMISSIONS.SCHOOLS_VIEW_ALL)){clauses.push("project.implementation_owner_id=?");params.push(req.teamUser.id)}if(req.query.stage){clauses.push("project.stage=?");params.push(enumValue(req.query.stage,ONBOARDING_STAGES,"Onboarding stage"))}const where=clauses.length?clauses.join(" AND "):"1=1";const [[count],[rows]]=await Promise.all([pool.query(`SELECT COUNT(*) total FROM team_onboarding_projects project WHERE ${where}`,params),pool.query(`SELECT project.public_ref,project.stage,project.completion_percentage,project.risk_status,project.main_blocker,project.start_date,project.expected_go_live_date,project.actual_go_live_date,project.updated_at,school.public_ref school_ref,school.name school_name,owner.public_ref implementation_owner_ref,owner.full_name implementation_owner_name FROM team_onboarding_projects project JOIN team_school_prospects school ON school.id=project.school_id JOIN team_users owner ON owner.id=project.implementation_owner_id WHERE ${where} ORDER BY FIELD(project.risk_status,'blocked','at_risk','watch','on_track'),project.expected_go_live_date LIMIT ? OFFSET ?`,[...params,pagination.pageSize,pagination.offset])]);res.json({items:rows,pagination:paginationMeta(count.total,pagination)})}
export async function getTeamOnboarding(req,res){const data=await onboardingWithChecklist(pool,req.params.projectRef);await assertTeamSchoolAccess(pool,req.teamUser,data.project.school_id);res.json(data)}

export async function createTeamOnboarding(req,res){
  const connection=await pool.getConnection()
  try{await connection.beginTransaction();const opportunity=await opportunityByRef(connection,value(req.body,"opportunity_ref","opportunityRef"),{lock:true});if(opportunity.stage!=="closed_won")throw new HttpError(409,"Onboarding can only be created for a Closed Won opportunity");await assertTeamSchoolAccess(connection,req.teamUser,opportunity.school_id);const ownerId=await userId(connection,value(req.body,"implementation_owner_ref","implementationOwnerRef")||opportunity.implementation_owner_ref,"Implementation owner");const startDate=nullableDate(value(req.body,"start_date","startDate"),"Start date")||new Date().toISOString().slice(0,10);const expected=nullableDate(value(req.body,"expected_go_live_date","expectedGoLiveDate")||opportunity.expected_go_live_date,"Expected go-live date");if(!expected)throw new HttpError(400,"Expected go-live date is required");const [result]=await connection.query(`INSERT INTO team_onboarding_projects (public_ref,school_id,opportunity_id,implementation_owner_id,start_date,expected_go_live_date,stage,risk_status,notes,created_by) VALUES (UUID(),?,?,?,?,?,'contract_signed','on_track',?,?)`,[opportunity.school_id,opportunity.id,ownerId,startDate,expected,optionalText(req.body?.notes,10000),req.teamUser.id]);await insertOnboardingChecklist(connection,result.insertId);const [[project]]=await connection.query("SELECT * FROM team_onboarding_projects WHERE id=?",[result.insertId]);await createTeamNotification(connection,{recipientUserId:ownerId,type:"onboarding_assigned",title:"Onboarding project assigned",message:opportunity.school_name,entityType:"onboarding",entityRef:project.public_ref,actionPath:`/team/onboarding?project=${project.public_ref}`});await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:"ONBOARDING_CREATED",entityType:"onboarding",entityId:project.id,entityRef:project.public_ref,schoolId:project.school_id,afterValue:project,...safeTeamRequestMetadata(req)});await connection.commit();res.status(201).json(await onboardingWithChecklist(pool,project.public_ref))}catch(error){await connection.rollback();if(error?.code==="ER_DUP_ENTRY")throw new HttpError(409,"An onboarding project already exists for this opportunity");throw error}finally{connection.release()}
}

export async function updateTeamOnboardingItem(req,res){const connection=await pool.getConnection();try{await connection.beginTransaction();const data=await onboardingWithChecklist(connection,req.params.projectRef);await assertTeamSchoolAccess(connection,req.teamUser,data.project.school_id);const [[item]]=await connection.query("SELECT * FROM team_onboarding_checklist_items WHERE project_id=? AND public_ref=? FOR UPDATE",[data.project.id,req.params.itemRef]);if(!item)throw new HttpError(404,"Checklist item was not found");const complete=Boolean(req.body?.is_complete??req.body?.complete);await connection.query("UPDATE team_onboarding_checklist_items SET is_complete=?,completed_by=?,completed_at=?,notes=? WHERE id=?",[complete?1:0,complete?req.teamUser.id:null,complete?new Date():null,value(req.body,"notes")===undefined?item.notes:optionalText(value(req.body,"notes"),10000),item.id]);const progress=await recalculateOnboardingProgress(connection,data.project.id);await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:"ONBOARDING_CHECKLIST_UPDATED",entityType:"onboarding",entityId:data.project.id,entityRef:data.project.public_ref,schoolId:data.project.school_id,beforeValue:{item:item.item_code,complete:Boolean(item.is_complete)},afterValue:{item:item.item_code,complete,progress},...safeTeamRequestMetadata(req)});await connection.commit();res.json(await onboardingWithChecklist(pool,data.project.public_ref))}catch(error){await connection.rollback();throw error}finally{connection.release()}}

export async function updateTeamOnboarding(req,res){const connection=await pool.getConnection();try{await connection.beginTransaction();const data=await onboardingWithChecklist(connection,req.params.projectRef);await assertTeamSchoolAccess(connection,req.teamUser,data.project.school_id);const stage=value(req.body,"stage")===undefined?data.project.stage:enumValue(value(req.body,"stage"),ONBOARDING_STAGES,"Onboarding stage");const risk=value(req.body,"risk_status","riskStatus")===undefined?data.project.risk_status:enumValue(value(req.body,"risk_status","riskStatus"),RISK_STATUSES,"Risk status");await connection.query("UPDATE team_onboarding_projects SET stage=?,risk_status=?,main_blocker=?,notes=? WHERE id=?",[stage,risk,value(req.body,"main_blocker","mainBlocker")===undefined?data.project.main_blocker:optionalText(value(req.body,"main_blocker","mainBlocker"),500),value(req.body,"notes")===undefined?data.project.notes:optionalText(value(req.body,"notes"),10000),data.project.id]);await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:"ONBOARDING_UPDATED",entityType:"onboarding",entityId:data.project.id,entityRef:data.project.public_ref,schoolId:data.project.school_id,beforeValue:{stage:data.project.stage,risk_status:data.project.risk_status},afterValue:{stage,risk_status:risk},...safeTeamRequestMetadata(req)});await connection.commit();res.json(await onboardingWithChecklist(pool,data.project.public_ref))}catch(error){await connection.rollback();throw error}finally{connection.release()}}

export async function approveTeamGoLive(req,res){const connection=await pool.getConnection();try{await connection.beginTransaction();const data=await onboardingWithChecklist(connection,req.params.projectRef);const missing=data.checklist.filter(item=>REQUIRED_GO_LIVE_ITEMS.includes(item.item_code)&&!item.is_complete).map(item=>item.label);const overrideReason=optionalText(value(req.body,"override_reason","overrideReason"),5000);if(missing.length&&!overrideReason)throw new HttpError(409,"Required onboarding checks are incomplete",{code:"TEAM_GO_LIVE_CHECKS_INCOMPLETE",details:{missing}});await connection.query("UPDATE team_onboarding_projects SET stage='live',actual_go_live_date=COALESCE(actual_go_live_date,CURRENT_DATE),go_live_approved_by=?,go_live_approved_at=CURRENT_TIMESTAMP,override_reason=? WHERE id=?",[req.teamUser.id,overrideReason,data.project.id]);await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:"ONBOARDING_GO_LIVE_APPROVED",entityType:"onboarding",entityId:data.project.id,entityRef:data.project.public_ref,schoolId:data.project.school_id,beforeValue:{stage:data.project.stage},afterValue:{stage:"live",missing_checks:missing},reason:overrideReason,...safeTeamRequestMetadata(req)});await connection.commit();res.json(await onboardingWithChecklist(pool,data.project.public_ref))}catch(error){await connection.rollback();throw error}finally{connection.release()}}

export async function listTeamSubscriptions(req,res){const pagination=paginationFrom(req.query);const clauses=[];const params=[];if(!hasTeamPermission(req.teamUser,TEAM_PERMISSIONS.SCHOOLS_VIEW_ALL)){clauses.push("(subscription.renewal_owner_id=? OR school.assigned_user_id=? OR EXISTS (SELECT 1 FROM team_onboarding_projects scoped_onboarding WHERE scoped_onboarding.school_id=school.id AND scoped_onboarding.implementation_owner_id=?))");params.push(req.teamUser.id,req.teamUser.id,req.teamUser.id)}if(req.query.status){clauses.push("subscription.status=?");params.push(enumValue(req.query.status,SUBSCRIPTION_STATUSES,"Subscription status"))}if(String(req.query.expiring||"")==="true")clauses.push("subscription.expires_on BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE,INTERVAL 30 DAY)");const where=clauses.length?clauses.join(" AND "):"1=1";const [[count],[rows]]=await Promise.all([pool.query(`SELECT COUNT(*) total FROM team_subscriptions subscription JOIN team_school_prospects school ON school.id=subscription.school_id WHERE ${where}`,params),pool.query(`SELECT subscription.*,school.public_ref school_ref,school.name school_name,owner.public_ref renewal_owner_ref,owner.full_name renewal_owner_name,DATEDIFF(subscription.expires_on,CURRENT_DATE) days_to_expiry FROM team_subscriptions subscription JOIN team_school_prospects school ON school.id=subscription.school_id JOIN team_users owner ON owner.id=subscription.renewal_owner_id WHERE ${where} ORDER BY subscription.expires_on LIMIT ? OFFSET ?`,[...params,pagination.pageSize,pagination.offset])]);res.json({items:rows,pagination:paginationMeta(count.total,pagination)})}

export async function createTeamSubscription(req,res){const connection=await pool.getConnection();try{await connection.beginTransaction();const schoolRef=requiredText(value(req.body,"school_ref","schoolRef"),"School",36);const [[school]]=await connection.query("SELECT id,name FROM team_school_prospects WHERE public_ref=? AND status='customer' AND archived_at IS NULL LIMIT 1",[schoolRef]);if(!school)throw new HttpError(400,"Subscriptions can only be created for an active customer record");const starts=nullableDate(value(req.body,"starts_on","startsOn"),"Start date"),expires=nullableDate(value(req.body,"expires_on","expiresOn"),"Expiry date");if(!starts||!expires)throw new HttpError(400,"Subscription start and expiry dates are required");const ownerId=await userId(connection,value(req.body,"renewal_owner_ref","renewalOwnerRef"),"Renewal owner");const draft={status:"active",expires_on:expires,payment_status:enumValue(value(req.body,"payment_status","paymentStatus"),PAYMENT_STATUSES,"Payment status","pending"),grace_period_days:numberInRange(value(req.body,"grace_period_days","gracePeriodDays"),"Grace period",0,365,0)};const status=deriveSubscriptionStatus(draft);const [result]=await connection.query(`INSERT INTO team_subscriptions (public_ref,school_id,package_name,starts_on,expires_on,academic_term,duration_months,amount,invoice_status,payment_status,grace_period_days,read_only_on,renewal_owner_id,status,notes,created_by) VALUES (UUID(),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[school.id,requiredText(value(req.body,"package_name","packageName"),"Package",160),starts,expires,optionalText(value(req.body,"academic_term","academicTerm"),120),numberInRange(value(req.body,"duration_months","durationMonths"),"Duration",1,120),numberInRange(value(req.body,"amount"),"Amount",0,999999999999,0),enumValue(value(req.body,"invoice_status","invoiceStatus"),INVOICE_STATUSES,"Invoice status","not_issued"),draft.payment_status,draft.grace_period_days,nullableDate(value(req.body,"read_only_on","readOnlyOn"),"Read-only date"),ownerId,status,optionalText(value(req.body,"notes"),10000),req.teamUser.id]);const [[subscription]]=await connection.query("SELECT * FROM team_subscriptions WHERE id=?",[result.insertId]);await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:"SUBSCRIPTION_CREATED",entityType:"subscription",entityId:subscription.id,entityRef:subscription.public_ref,schoolId:school.id,afterValue:subscription,...safeTeamRequestMetadata(req)});await connection.commit();res.status(201).json({subscription})}catch(error){await connection.rollback();throw error}finally{connection.release()}}

export async function updateTeamSubscription(req,res){const connection=await pool.getConnection();try{await connection.beginTransaction();const [[subscription]]=await connection.query("SELECT * FROM team_subscriptions WHERE public_ref=? FOR UPDATE",[req.params.subscriptionRef]);if(!subscription)throw new HttpError(404,"Subscription was not found");let paymentStatus=subscription.payment_status;if(value(req.body,"payment_status","paymentStatus")!==undefined){if(!hasTeamPermission(req.teamUser,TEAM_PERMISSIONS.PAYMENTS_CONFIRM))throw new HttpError(403,"You cannot confirm payment status");paymentStatus=enumValue(value(req.body,"payment_status","paymentStatus"),PAYMENT_STATUSES,"Payment status")}const expires=value(req.body,"expires_on","expiresOn")===undefined?subscription.expires_on:nullableDate(value(req.body,"expires_on","expiresOn"),"Expiry date");const next={...subscription,expires_on:expires,payment_status:paymentStatus,status:value(req.body,"status")===undefined?subscription.status:enumValue(value(req.body,"status"),SUBSCRIPTION_STATUSES,"Subscription status")};const status=deriveSubscriptionStatus(next);await connection.query("UPDATE team_subscriptions SET expires_on=?,invoice_status=?,payment_status=?,grace_period_days=?,status=?,notes=? WHERE id=?",[expires,value(req.body,"invoice_status","invoiceStatus")===undefined?subscription.invoice_status:enumValue(value(req.body,"invoice_status","invoiceStatus"),INVOICE_STATUSES,"Invoice status"),paymentStatus,value(req.body,"grace_period_days","gracePeriodDays")===undefined?subscription.grace_period_days:numberInRange(value(req.body,"grace_period_days","gracePeriodDays"),"Grace period",0,365,0),status,value(req.body,"notes")===undefined?subscription.notes:optionalText(value(req.body,"notes"),10000),subscription.id]);const [[updated]]=await connection.query("SELECT * FROM team_subscriptions WHERE id=?",[subscription.id]);await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:paymentStatus!==subscription.payment_status?"PAYMENT_STATUS_CONFIRMED":"SUBSCRIPTION_UPDATED",entityType:"subscription",entityId:subscription.id,entityRef:subscription.public_ref,schoolId:subscription.school_id,beforeValue:subscription,afterValue:updated,...safeTeamRequestMetadata(req)});await connection.commit();res.json({subscription:updated,suspension_applied:false})}catch(error){await connection.rollback();throw error}finally{connection.release()}}
