import bcrypt from "bcryptjs"
import { pool } from "../config/db.js"
import { safeTeamRequestMetadata } from "../middleware/teamAuth.js"
import { TEAM_PERMISSIONS, hasTeamPermission, isPlatformOwner, loadTeamPrincipal } from "../services/teamAccessService.js"
import { optionalText, paginationFrom, paginationMeta, requiredText, safeLike, writeTeamAudit } from "../services/teamSuiteService.js"
import { HttpError } from "../utils/http.js"

function schoolScope(user,alias="school"){
  if(hasTeamPermission(user,TEAM_PERMISSIONS.SCHOOLS_VIEW_ALL))return{sql:"1=1",params:[]}
  return{sql:`(${alias}.assigned_user_id=? OR EXISTS (SELECT 1 FROM team_sales_opportunities scoped_opportunity WHERE scoped_opportunity.school_id=${alias}.id AND scoped_opportunity.archived_at IS NULL AND (scoped_opportunity.assigned_owner_id=? OR scoped_opportunity.implementation_owner_id=?)) OR EXISTS (SELECT 1 FROM team_onboarding_projects scoped_onboarding WHERE scoped_onboarding.school_id=${alias}.id AND scoped_onboarding.implementation_owner_id=?) OR EXISTS (SELECT 1 FROM team_support_tickets scoped_ticket WHERE scoped_ticket.school_id=${alias}.id AND scoped_ticket.assigned_user_id=?))`,params:[user.id,user.id,user.id,user.id,user.id]}
}

export async function getTeamDashboard(req,res){
  const scope=schoolScope(req.teamUser)
  const taskScope=hasTeamPermission(req.teamUser,TEAM_PERMISSIONS.SCHOOLS_VIEW_ALL)?{sql:"1=1",params:[]}:{sql:"task.assigned_user_id=?",params:[req.teamUser.id]}
  const ticketScope=hasTeamPermission(req.teamUser,TEAM_PERMISSIONS.SUPPORT_VIEW_ALL)?{sql:"1=1",params:[]}:{sql:"ticket.assigned_user_id=?",params:[req.teamUser.id]}
  const [schoolCounts,opportunityCounts,onboardingCounts,subscriptionCounts,taskCounts,ticketCounts,todayTasks,upcomingMeetings,recentActivity,attention,workload,funnel,pipelineValue]=await Promise.all([
    pool.query(`SELECT COUNT(*) total,SUM(EXISTS(SELECT 1 FROM team_school_activities activity WHERE activity.school_id=school.id)) contacted,SUM(EXISTS(SELECT 1 FROM team_school_activities activity WHERE activity.school_id=school.id AND activity.activity_type IN ('whatsapp_reply','email_received'))) responses,SUM(school.next_action IS NULL OR school.next_action_at IS NULL) no_next_action,SUM(school.status='customer') customers FROM team_school_prospects school WHERE school.archived_at IS NULL AND ${scope.sql}`,scope.params),
    pool.query(`SELECT COUNT(*) total,SUM(opportunity.stage='proposal_sent') proposals_sent,SUM(opportunity.stage='negotiation') negotiation,SUM(opportunity.stage='closed_won') won,SUM(opportunity.stage='closed_lost') lost,SUM(opportunity.stage='demo_completed') demos_completed,SUM(opportunity.stage='meeting_scheduled') meetings_scheduled FROM team_sales_opportunities opportunity JOIN team_school_prospects school ON school.id=opportunity.school_id WHERE opportunity.archived_at IS NULL AND school.archived_at IS NULL AND ${scope.sql}`,scope.params),
    pool.query(`SELECT COUNT(*) total,SUM(project.stage IN ('live','post_launch_monitoring','complete')) live FROM team_onboarding_projects project JOIN team_school_prospects school ON school.id=project.school_id WHERE ${scope.sql}`,scope.params),
    pool.query(`SELECT SUM(subscription.expires_on BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE,INTERVAL 30 DAY)) renewals,SUM(subscription.payment_status IN ('pending','part_paid','overdue')) outstanding FROM team_subscriptions subscription JOIN team_school_prospects school ON school.id=subscription.school_id WHERE ${scope.sql}`,scope.params),
    pool.query(`SELECT SUM(task.due_at<CURRENT_TIMESTAMP AND task.status NOT IN ('completed','cancelled')) overdue FROM team_tasks task WHERE task.archived_at IS NULL AND ${taskScope.sql}`,taskScope.params),
    pool.query(`SELECT SUM(ticket.status NOT IN ('resolved','closed')) open_tickets,SUM(ticket.severity='critical' AND ticket.status NOT IN ('resolved','closed')) critical FROM team_support_tickets ticket WHERE ${ticketScope.sql}`,ticketScope.params),
    pool.query(`SELECT task.public_ref,task.title,task.due_at,task.priority,task.status,school.public_ref school_ref,school.name school_name FROM team_tasks task LEFT JOIN team_school_prospects school ON school.id=task.school_id WHERE task.archived_at IS NULL AND DATE(task.due_at)=CURRENT_DATE AND task.status NOT IN ('completed','cancelled') AND ${taskScope.sql} ORDER BY FIELD(task.priority,'critical','high','medium','low'),task.due_at LIMIT 8`,taskScope.params),
    pool.query(`SELECT meeting.public_ref,meeting.meeting_type,meeting.scheduled_at,meeting.location,school.public_ref school_ref,school.name school_name FROM team_meetings meeting JOIN team_school_prospects school ON school.id=meeting.school_id WHERE meeting.scheduled_at>=CURRENT_TIMESTAMP AND meeting.outcome='pending' AND ${scope.sql} ORDER BY meeting.scheduled_at LIMIT 8`,scope.params),
    pool.query(`SELECT activity.public_ref,activity.activity_type,activity.summary,activity.occurred_at,school.public_ref school_ref,school.name school_name,user.full_name team_user_name FROM team_school_activities activity JOIN team_school_prospects school ON school.id=activity.school_id JOIN team_users user ON user.id=activity.team_user_id WHERE ${scope.sql} ORDER BY activity.occurred_at DESC LIMIT 10`,scope.params),
    pool.query(`SELECT opportunity.public_ref,opportunity.title,opportunity.stage,opportunity.total_expected_value,opportunity.next_action_at,school.name school_name,owner.full_name owner_name FROM team_sales_opportunities opportunity JOIN team_school_prospects school ON school.id=opportunity.school_id JOIN team_users owner ON owner.id=opportunity.assigned_owner_id WHERE opportunity.archived_at IS NULL AND opportunity.stage NOT IN ('closed_won','closed_lost') AND ${scope.sql} AND (opportunity.next_action_at IS NULL OR opportunity.next_action_at<CURRENT_TIMESTAMP OR opportunity.updated_at<DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 10 DAY)) ORDER BY opportunity.updated_at LIMIT 8`,scope.params),
    pool.query(`SELECT user.public_ref,user.full_name,COUNT(task.id) open_tasks,SUM(task.due_at<CURRENT_TIMESTAMP) overdue_tasks FROM team_users user LEFT JOIN team_tasks task ON task.assigned_user_id=user.id AND task.status NOT IN ('completed','cancelled') AND task.archived_at IS NULL WHERE user.is_active=1 GROUP BY user.id ORDER BY open_tasks DESC,user.full_name LIMIT 12`),
    pool.query(`SELECT opportunity.stage,COUNT(*) total FROM team_sales_opportunities opportunity JOIN team_school_prospects school ON school.id=opportunity.school_id WHERE opportunity.archived_at IS NULL AND ${scope.sql} GROUP BY opportunity.stage ORDER BY MIN(opportunity.id)`,scope.params),
    pool.query(`SELECT COALESCE(SUM(opportunity.total_expected_value),0) total_value,COALESCE(SUM(opportunity.total_expected_value*opportunity.probability/100),0) weighted_value FROM team_sales_opportunities opportunity JOIN team_school_prospects school ON school.id=opportunity.school_id WHERE opportunity.archived_at IS NULL AND opportunity.stage NOT IN ('closed_won','closed_lost') AND ${scope.sql}`,scope.params),
  ])
  const schools=schoolCounts[0][0]||{},opportunities=opportunityCounts[0][0]||{},onboarding=onboardingCounts[0][0]||{},subscriptions=subscriptionCounts[0][0]||{},tasks=taskCounts[0][0]||{},tickets=ticketCounts[0][0]||{}
  const metrics=[
    ["prospects","School prospects",schools.total,"/team/schools"],["contacted","Schools contacted",schools.contacted,"/team/schools?contacted=true"],["responses","Responses received",schools.responses,"/team/schools?responded=true"],["meetings","Meetings scheduled",opportunities.meetings_scheduled,"/team/meetings?upcoming=true"],["demos","Demos completed",opportunities.demos_completed,"/team/pipeline?stage=demo_completed"],["proposals","Proposals sent",opportunities.proposals_sent,"/team/pipeline?stage=proposal_sent"],["negotiation","In negotiation",opportunities.negotiation,"/team/pipeline?stage=negotiation"],["won","Deals won",opportunities.won,"/team/pipeline?stage=closed_won"],["lost","Deals lost",opportunities.lost,"/team/pipeline?stage=closed_lost"],["onboarding","Schools onboarding",Number(onboarding.total||0)-Number(onboarding.live||0),"/team/onboarding"],["live","Live schools",onboarding.live,"/team/onboarding?stage=live"],["renewals","Renewals approaching",subscriptions.renewals,"/team/subscriptions?expiring=true"],["outstanding","Outstanding payments",subscriptions.outstanding,"/team/subscriptions?payment=outstanding"],["tickets","Open support tickets",tickets.open_tickets,"/team/support"],["overdue","Overdue tasks",tasks.overdue,"/team/tasks?overdue=true"],["no_action","Schools with no next action",schools.no_next_action,"/team/schools?no_next_action=true"],
  ].map(([key,label,count,path])=>({key,label,value:Number(count||0),path}))
  res.json({metrics,today_tasks:todayTasks[0],upcoming_meetings:upcomingMeetings[0],recent_activity:recentActivity[0],opportunities_requiring_attention:attention[0],team_workload:workload[0],conversion_funnel:funnel[0],pipeline_value:pipelineValue[0][0]||{total_value:0,weighted_value:0},recent_support:{open:Number(tickets.open_tickets||0),critical:Number(tickets.critical||0)}})
}

export async function teamGlobalSearch(req,res){
  const query=safeLike(req.query.q);if(query.length<2)return res.json({items:[],query:req.query.q||"",pagination:{page:1,page_size:20,total:0,total_pages:1}})
  const pagination=paginationFrom(req.query,50);const pattern=`%${query}%`;const scope=schoolScope(req.teamUser)
  const sql=`SELECT results.*,COUNT(*) OVER() result_total FROM (
    SELECT 'school' entity_type,school.public_ref entity_ref,school.name title,CONCAT_WS(' · ',school.district,REPLACE(school.status,'_',' ')) subtitle,CONCAT('/team/schools/',school.public_ref) path,school.updated_at sort_at FROM team_school_prospects school WHERE school.archived_at IS NULL AND ${scope.sql} AND (school.name LIKE ? ESCAPE '\\\\' OR school.email LIKE ? ESCAPE '\\\\' OR school.main_phone LIKE ? ESCAPE '\\\\')
    UNION ALL SELECT 'contact',contact.public_ref,contact.full_name,CONCAT_WS(' · ',contact.position,school.name),CONCAT('/team/schools/',school.public_ref),contact.updated_at FROM team_school_contacts contact JOIN team_school_prospects school ON school.id=contact.school_id WHERE ${scope.sql} AND (contact.full_name LIKE ? ESCAPE '\\\\' OR contact.email LIKE ? ESCAPE '\\\\' OR contact.phone LIKE ? ESCAPE '\\\\')
    UNION ALL SELECT 'opportunity',opportunity.public_ref,opportunity.title,CONCAT_WS(' · ',school.name,REPLACE(opportunity.stage,'_',' ')),'/team/pipeline',opportunity.updated_at FROM team_sales_opportunities opportunity JOIN team_school_prospects school ON school.id=opportunity.school_id WHERE opportunity.archived_at IS NULL AND ${scope.sql} AND (opportunity.title LIKE ? ESCAPE '\\\\' OR school.name LIKE ? ESCAPE '\\\\')
    UNION ALL SELECT 'task',task.public_ref,task.title,CONCAT_WS(' · ',school.name,REPLACE(task.status,'_',' ')),'/team/tasks',task.updated_at FROM team_tasks task LEFT JOIN team_school_prospects school ON school.id=task.school_id WHERE task.archived_at IS NULL AND ${hasTeamPermission(req.teamUser,TEAM_PERMISSIONS.SCHOOLS_VIEW_ALL)?"1=1":"task.assigned_user_id=?"} AND task.title LIKE ? ESCAPE '\\\\'
    UNION ALL SELECT 'meeting',meeting.public_ref,CONCAT(REPLACE(meeting.meeting_type,'_',' '),' · ',school.name),DATE_FORMAT(meeting.scheduled_at,'%d %b %Y %H:%i'),'/team/meetings',meeting.updated_at FROM team_meetings meeting JOIN team_school_prospects school ON school.id=meeting.school_id WHERE ${scope.sql} AND school.name LIKE ? ESCAPE '\\\\'
    UNION ALL SELECT 'proposal',proposal.public_ref,proposal.proposal_number,CONCAT_WS(' · ',school.name,proposal.package_name),'/team/proposals',proposal.updated_at FROM team_proposals proposal JOIN team_school_prospects school ON school.id=proposal.school_id WHERE ${scope.sql} AND (proposal.proposal_number LIKE ? ESCAPE '\\\\' OR school.name LIKE ? ESCAPE '\\\\')
    UNION ALL SELECT 'onboarding',project.public_ref,CONCAT('Onboarding · ',school.name),REPLACE(project.stage,'_',' '),'/team/onboarding',project.updated_at FROM team_onboarding_projects project JOIN team_school_prospects school ON school.id=project.school_id WHERE ${scope.sql} AND school.name LIKE ? ESCAPE '\\\\'
    UNION ALL SELECT 'subscription',subscription.public_ref,CONCAT('Subscription · ',school.name),CONCAT_WS(' · ',subscription.package_name,subscription.status),'/team/subscriptions',subscription.updated_at FROM team_subscriptions subscription JOIN team_school_prospects school ON school.id=subscription.school_id WHERE ${scope.sql} AND (school.name LIKE ? ESCAPE '\\\\' OR subscription.package_name LIKE ? ESCAPE '\\\\')
    UNION ALL SELECT 'support_ticket',ticket.public_ref,ticket.ticket_number,CONCAT_WS(' · ',school.name,REPLACE(ticket.category,'_',' ')),'/team/support',ticket.updated_at FROM team_support_tickets ticket JOIN team_school_prospects school ON school.id=ticket.school_id WHERE ${hasTeamPermission(req.teamUser,TEAM_PERMISSIONS.SUPPORT_VIEW_ALL)?"1=1":"ticket.assigned_user_id=?"} AND (ticket.ticket_number LIKE ? ESCAPE '\\\\' OR school.name LIKE ? ESCAPE '\\\\' OR ticket.description LIKE ? ESCAPE '\\\\')
    UNION ALL SELECT 'team_user',user.public_ref,user.full_name,CONCAT_WS(' · ',user.job_title,user.email),'/team/team-members',user.updated_at FROM team_users user WHERE user.is_active=1 AND (user.full_name LIKE ? ESCAPE '\\\\' OR user.email LIKE ? ESCAPE '\\\\')
  ) results ORDER BY sort_at DESC LIMIT ? OFFSET ?`
  const params=[]
  params.push(...scope.params,pattern,pattern,pattern,...scope.params,pattern,pattern,pattern,...scope.params,pattern,pattern)
  if(!hasTeamPermission(req.teamUser,TEAM_PERMISSIONS.SCHOOLS_VIEW_ALL))params.push(req.teamUser.id)
  params.push(pattern,...scope.params,pattern,...scope.params,pattern,pattern,...scope.params,pattern,...scope.params,pattern,pattern)
  if(!hasTeamPermission(req.teamUser,TEAM_PERMISSIONS.SUPPORT_VIEW_ALL))params.push(req.teamUser.id)
  params.push(pattern,pattern,pattern,pattern,pattern,pagination.pageSize,pagination.offset)
  const [rows]=await pool.query(sql,params)
  const total=Number(rows[0]?.result_total||0)
  res.json({items:rows.map(({result_total,...item})=>item),query:req.query.q,pagination:paginationMeta(total,pagination)})
}

export async function listTeamMembers(_req,res){const [rows]=await pool.query(`SELECT user.public_ref,user.full_name,user.email,user.job_title,user.phone,user.must_change_password,user.is_active,user.last_login_at,user.created_at,GROUP_CONCAT(role.code ORDER BY role.name) roles,GROUP_CONCAT(role.name ORDER BY role.name SEPARATOR ' · ') role_labels FROM team_users user LEFT JOIN team_user_roles user_role ON user_role.user_id=user.id LEFT JOIN team_roles role ON role.id=user_role.role_id GROUP BY user.id ORDER BY user.is_active DESC,user.full_name`);res.json({items:rows.map(row=>({...row,roles:row.roles?row.roles.split(","):[]}))})}

export async function teamRoleMatrix(_req,res){const [[roles],[permissions],[assignments]]=await Promise.all([pool.query("SELECT code,name,description FROM team_roles ORDER BY id"),pool.query("SELECT code,name,description FROM team_permissions ORDER BY name"),pool.query(`SELECT role.code role_code,permission.code permission_code FROM team_role_permissions link JOIN team_roles role ON role.id=link.role_id JOIN team_permissions permission ON permission.id=link.permission_id ORDER BY role.id,permission.name`)]);res.json({roles,permissions,assignments})}

export async function createTeamMember(req,res){
  const roles=[...new Set(Array.isArray(req.body?.roles)?req.body.roles.map(role=>String(role).trim().toLowerCase()):[])];if(!roles.length)throw new HttpError(400,"At least one role is required");if(roles.includes("platform_owner")&&!isPlatformOwner(req.teamUser))throw new HttpError(403,"Only a Platform Owner can create another Platform Owner")
  const email=requiredText(req.body?.email,"Email",190).toLowerCase(),temporaryPassword=String(req.body?.temporary_password||req.body?.temporaryPassword||"");if(temporaryPassword.length<10)throw new HttpError(400,"Temporary password must be at least 10 characters")
  const connection=await pool.getConnection();try{await connection.beginTransaction();const [roleRows]=await connection.query(`SELECT id,code FROM team_roles WHERE code IN (${roles.map(()=>"?").join(",")})`,roles);if(roleRows.length!==roles.length)throw new HttpError(400,"One or more team roles are invalid");const hash=await bcrypt.hash(temporaryPassword,12);const [result]=await connection.query("INSERT INTO team_users (public_ref,full_name,email,password_hash,job_title,phone,must_change_password,is_active,created_by) VALUES (UUID(),?,?,?,?,?,1,1,?)",[requiredText(req.body?.full_name||req.body?.fullName,"Full name",180),email,hash,optionalText(req.body?.job_title||req.body?.jobTitle,160),optionalText(req.body?.phone,50),req.teamUser.id]);for(const role of roleRows)await connection.query("INSERT INTO team_user_roles (user_id,role_id,assigned_by) VALUES (?,?,?)",[result.insertId,role.id,req.teamUser.id]);const principal=await loadTeamPrincipal(result.insertId,connection);await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:"TEAM_USER_CREATED",entityType:"team_user",entityId:result.insertId,entityRef:principal.publicRef,afterValue:{email,roles},...safeTeamRequestMetadata(req)});await connection.commit();res.status(201).json({user:principal})}catch(error){await connection.rollback();if(error?.code==="ER_DUP_ENTRY")throw new HttpError(409,"A Team Suite user already exists with this email");throw error}finally{connection.release()}
}

export async function updateTeamMember(req,res){const connection=await pool.getConnection();try{await connection.beginTransaction();const [[target]]=await connection.query("SELECT * FROM team_users WHERE public_ref=? FOR UPDATE",[req.params.userRef]);if(!target)throw new HttpError(404,"Team member was not found");const [currentRoles]=await connection.query(`SELECT role.code FROM team_user_roles link JOIN team_roles role ON role.id=link.role_id WHERE link.user_id=?`,[target.id]);if(currentRoles.some(role=>role.code==="platform_owner")&&!isPlatformOwner(req.teamUser))throw new HttpError(403,"Only a Platform Owner can change a Platform Owner account");const roles=req.body?.roles===undefined?currentRoles.map(role=>role.code):[...new Set(req.body.roles.map(role=>String(role).trim().toLowerCase()))];if(!roles.length)throw new HttpError(400,"At least one role is required");if(roles.includes("platform_owner")&&!isPlatformOwner(req.teamUser))throw new HttpError(403,"Only a Platform Owner can assign Platform Owner");const [roleRows]=await connection.query(`SELECT id,code FROM team_roles WHERE code IN (${roles.map(()=>"?").join(",")})`,roles);if(roleRows.length!==roles.length)throw new HttpError(400,"One or more roles are invalid");const active=req.body?.is_active===undefined?Boolean(target.is_active):Boolean(req.body.is_active);if(target.id===req.teamUser.id&&!active)throw new HttpError(400,"You cannot disable your own account");await connection.query("UPDATE team_users SET full_name=?,job_title=?,phone=?,is_active=? WHERE id=?",[req.body?.full_name===undefined?target.full_name:requiredText(req.body.full_name,"Full name",180),req.body?.job_title===undefined?target.job_title:optionalText(req.body.job_title,160),req.body?.phone===undefined?target.phone:optionalText(req.body.phone,50),active?1:0,target.id]);await connection.query("DELETE FROM team_user_roles WHERE user_id=?",[target.id]);for(const role of roleRows)await connection.query("INSERT INTO team_user_roles (user_id,role_id,assigned_by) VALUES (?,?,?)",[target.id,role.id,req.teamUser.id]);const principal=await loadTeamPrincipal(target.id,connection).catch(error=>{if(!active&&error.status===401)return{publicRef:target.public_ref,email:target.email,roles,isActive:false};throw error});await writeTeamAudit(connection,{actorUserId:req.teamUser.id,action:"TEAM_USER_ROLES_UPDATED",entityType:"team_user",entityId:target.id,entityRef:target.public_ref,beforeValue:{roles:currentRoles.map(role=>role.code),is_active:Boolean(target.is_active)},afterValue:{roles,is_active:active},...safeTeamRequestMetadata(req)});await connection.commit();res.json({user:principal})}catch(error){await connection.rollback();throw error}finally{connection.release()}}

export async function listTeamAudit(req,res){const pagination=paginationFrom(req.query,100);const clauses=[];const params=[];if(req.query.action){clauses.push("audit.action=?");params.push(String(req.query.action).slice(0,120))}if(req.query.entity_type){clauses.push("audit.entity_type=?");params.push(String(req.query.entity_type).slice(0,80))}const where=clauses.length?clauses.join(" AND "):"1=1";const [[count],[rows]]=await Promise.all([pool.query(`SELECT COUNT(*) total FROM team_audit_logs audit WHERE ${where}`,params),pool.query(`SELECT audit.public_ref,audit.action,audit.entity_type,audit.entity_ref,audit.before_value,audit.after_value,audit.reason,audit.ip_address,audit.user_agent,audit.created_at,user.public_ref actor_ref,user.full_name actor_name,school.public_ref school_ref,school.name school_name FROM team_audit_logs audit LEFT JOIN team_users user ON user.id=audit.actor_user_id LEFT JOIN team_school_prospects school ON school.id=audit.school_id WHERE ${where} ORDER BY audit.created_at DESC LIMIT ? OFFSET ?`,[...params,pagination.pageSize,pagination.offset])]);res.json({items:rows,pagination:paginationMeta(count.total,pagination),immutable:true})}

export async function getTeamReports(req,res){const scope=schoolScope(req.teamUser);const [[pipeline],[conversion],[tasks],[support],[subscriptions]]=await Promise.all([pool.query(`SELECT opportunity.stage,COUNT(*) opportunities,SUM(opportunity.total_expected_value) value FROM team_sales_opportunities opportunity JOIN team_school_prospects school ON school.id=opportunity.school_id WHERE opportunity.archived_at IS NULL AND ${scope.sql} GROUP BY opportunity.stage`,scope.params),pool.query(`SELECT SUM(opportunity.stage='closed_won') won,SUM(opportunity.stage='closed_lost') lost,COUNT(*) total FROM team_sales_opportunities opportunity JOIN team_school_prospects school ON school.id=opportunity.school_id WHERE opportunity.archived_at IS NULL AND ${scope.sql}`,scope.params),pool.query("SELECT assigned.full_name,SUM(task.status NOT IN ('completed','cancelled')) open_tasks,SUM(task.due_at<CURRENT_TIMESTAMP AND task.status NOT IN ('completed','cancelled')) overdue_tasks FROM team_users assigned LEFT JOIN team_tasks task ON task.assigned_user_id=assigned.id GROUP BY assigned.id ORDER BY open_tasks DESC"),pool.query("SELECT severity,status,COUNT(*) total FROM team_support_tickets GROUP BY severity,status"),pool.query("SELECT status,payment_status,COUNT(*) total,SUM(amount) amount FROM team_subscriptions GROUP BY status,payment_status")]);res.json({pipeline,conversion,task_workload:tasks,support,subscriptions,generated_at:new Date().toISOString()})}
