USE smartlink_schools;

ALTER TABLE terms
  ADD COLUMN IF NOT EXISTS revision_start_date DATE NULL AFTER end_date,
  ADD COLUMN IF NOT EXISTS revision_end_date DATE NULL AFTER revision_start_date,
  ADD COLUMN IF NOT EXISTS exam_start_date DATE NULL AFTER revision_end_date,
  ADD COLUMN IF NOT EXISTS exam_end_date DATE NULL AFTER exam_start_date,
  ADD COLUMN IF NOT EXISTS marking_start_date DATE NULL AFTER exam_end_date,
  ADD COLUMN IF NOT EXISTS marking_end_date DATE NULL AFTER marking_start_date,
  ADD COLUMN IF NOT EXISTS closing_date DATE NULL AFTER marking_end_date;

CREATE TABLE IF NOT EXISTS school_events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NULL,
  term_id BIGINT UNSIGNED NULL,
  title VARCHAR(180) NOT NULL,
  description TEXT NULL,
  event_type ENUM('school_event', 'academic_deadline', 'holiday', 'closure', 'meeting', 'sports', 'exam_session', 'exam_paper', 'recurring_assessment', 'weekly_test', 'revision_week', 'exam_week', 'marking_week', 'term_closing_week', 'custom') NOT NULL DEFAULT 'school_event',
  start_datetime DATETIME NOT NULL,
  end_datetime DATETIME NULL,
  all_day TINYINT(1) NOT NULL DEFAULT 0,
  class_id BIGINT UNSIGNED NULL,
  stream_section VARCHAR(80) NULL,
  subject_id BIGINT UNSIGNED NULL,
  teacher_id BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  visibility ENUM('whole_school', 'teachers_only', 'students', 'parents', 'class_only', 'staff_only') NOT NULL DEFAULT 'whole_school',
  recurrence_rule VARCHAR(255) NULL,
  recurrence_end_date DATE NULL,
  source_type ENUM('manual', 'recurring_template', 'exam_session', 'exam_timetable', 'academic_timeline') NULL DEFAULT 'manual',
  source_id BIGINT UNSIGNED NULL,
  status ENUM('draft', 'scheduled', 'active', 'completed', 'cancelled', 'archived') NOT NULL DEFAULT 'scheduled',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_school_events_scope (school_id, academic_year_id, term_id, status),
  KEY idx_school_events_date (school_id, start_datetime, status),
  KEY idx_school_events_class_subject (school_id, class_id, subject_id, teacher_id),
  KEY idx_school_events_type (school_id, event_type, status),
  CONSTRAINT fk_school_events_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_school_events_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_school_events_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_school_events_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_school_events_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_school_events_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
  CONSTRAINT fk_school_events_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS recurring_assessment_templates (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NOT NULL,
  term_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(180) NOT NULL,
  description TEXT NULL,
  assessment_type ENUM('weekly_spelling_test', 'weekly_test', 'quiz', 'reading_check', 'mental_maths', 'vocabulary_test', 'custom') NOT NULL DEFAULT 'weekly_test',
  class_id BIGINT UNSIGNED NOT NULL,
  stream_section VARCHAR(80) NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  teacher_id BIGINT UNSIGNED NOT NULL,
  total_marks DECIMAL(8,2) NOT NULL DEFAULT 10,
  frequency ENUM('weekly', 'biweekly', 'monthly', 'custom') NOT NULL DEFAULT 'weekly',
  day_of_week TINYINT UNSIGNED NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  default_start_time TIME NULL,
  default_duration_minutes INT NULL,
  status ENUM('draft', 'active', 'paused', 'completed', 'archived') NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_recurring_templates_scope (school_id, academic_year_id, term_id, status),
  KEY idx_recurring_templates_class_subject (school_id, class_id, subject_id, teacher_id),
  CONSTRAINT fk_recurring_templates_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_recurring_templates_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_recurring_templates_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_recurring_templates_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_recurring_templates_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_recurring_templates_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
  CONSTRAINT fk_recurring_templates_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS assessment_instances (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  template_id BIGINT UNSIGNED NULL,
  academic_year_id BIGINT UNSIGNED NOT NULL,
  term_id BIGINT UNSIGNED NOT NULL,
  class_id BIGINT UNSIGNED NOT NULL,
  stream_section VARCHAR(80) NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  teacher_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(180) NOT NULL,
  instance_date DATE NOT NULL,
  start_time TIME NULL,
  duration_minutes INT NULL,
  total_marks DECIMAL(8,2) NOT NULL DEFAULT 10,
  status ENUM('upcoming', 'draft', 'in_progress', 'completed', 'cancelled', 'archived') NOT NULL DEFAULT 'upcoming',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_assessment_instance_template (school_id, template_id, instance_date, class_id, subject_id),
  KEY idx_assessment_instances_scope (school_id, academic_year_id, term_id, status),
  KEY idx_assessment_instances_date (school_id, instance_date, class_id, subject_id),
  KEY idx_assessment_instances_teacher (school_id, teacher_id, academic_year_id, term_id),
  CONSTRAINT fk_assessment_instances_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_assessment_instances_template FOREIGN KEY (template_id) REFERENCES recurring_assessment_templates(id),
  CONSTRAINT fk_assessment_instances_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_assessment_instances_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_assessment_instances_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_assessment_instances_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_assessment_instances_teacher FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS assessment_instance_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  assessment_instance_id BIGINT UNSIGNED NOT NULL,
  item_text VARCHAR(255) NOT NULL,
  item_type ENUM('word', 'question', 'instruction') NOT NULL DEFAULT 'word',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_assessment_instance_items (school_id, assessment_instance_id, sort_order),
  CONSTRAINT fk_assessment_instance_items_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_assessment_instance_items_instance FOREIGN KEY (assessment_instance_id) REFERENCES assessment_instances(id)
);

CREATE TABLE IF NOT EXISTS assessment_instance_results (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  assessment_instance_id BIGINT UNSIGNED NOT NULL,
  student_id BIGINT UNSIGNED NOT NULL,
  enrollment_id BIGINT UNSIGNED NULL,
  score DECIMAL(8,2) NULL,
  comment VARCHAR(255) NULL,
  status ENUM('draft', 'submitted', 'completed', 'locked') NOT NULL DEFAULT 'draft',
  last_saved_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_assessment_instance_result_student (school_id, assessment_instance_id, student_id),
  KEY idx_assessment_instance_results_student (school_id, student_id),
  KEY idx_assessment_instance_results_enrollment (school_id, enrollment_id),
  CONSTRAINT fk_assessment_instance_results_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_assessment_instance_results_instance FOREIGN KEY (assessment_instance_id) REFERENCES assessment_instances(id),
  CONSTRAINT fk_assessment_instance_results_student FOREIGN KEY (student_id) REFERENCES students(id),
  CONSTRAINT fk_assessment_instance_results_enrollment FOREIGN KEY (enrollment_id) REFERENCES student_enrollments(id)
);

CREATE TABLE IF NOT EXISTS term_timeline_markers (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NOT NULL,
  term_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(180) NOT NULL,
  marker_type ENUM('normal_week', 'revision_week', 'exam_week', 'marking_week', 'closing_week', 'holiday', 'custom') NOT NULL DEFAULT 'custom',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status ENUM('draft', 'scheduled', 'active', 'completed', 'cancelled', 'archived') NOT NULL DEFAULT 'scheduled',
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_term_marker_range (school_id, term_id, marker_type, start_date, end_date),
  KEY idx_term_markers_scope (school_id, academic_year_id, term_id, status),
  CONSTRAINT fk_term_markers_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_term_markers_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_term_markers_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_term_markers_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);
