CREATE TABLE IF NOT EXISTS manual_syllabus_entries (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  submitted_by BIGINT UNSIGNED NOT NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  curriculum_id BIGINT UNSIGNED NULL,
  grade_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  term VARCHAR(80) NULL,
  suggested_week INT NULL,
  topic_name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  objectives_json JSON NULL,
  status ENUM('draft', 'pending_review', 'approved', 'revision_requested', 'rejected') NOT NULL DEFAULT 'pending_review',
  review_notes TEXT NULL,
  approved_topic_id BIGINT UNSIGNED NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_manual_syllabus_school_status (school_id, status, submitted_at),
  KEY idx_manual_syllabus_teacher (school_id, submitted_by, status),
  KEY idx_manual_syllabus_scope (school_id, grade_id, subject_id, status),
  CONSTRAINT fk_manual_syllabus_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_manual_syllabus_submitted_by FOREIGN KEY (submitted_by) REFERENCES users(id),
  CONSTRAINT fk_manual_syllabus_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id),
  CONSTRAINT fk_manual_syllabus_curriculum FOREIGN KEY (curriculum_id) REFERENCES curricula(id),
  CONSTRAINT fk_manual_syllabus_grade FOREIGN KEY (grade_id) REFERENCES grade_levels(id),
  CONSTRAINT fk_manual_syllabus_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_manual_syllabus_approved_topic FOREIGN KEY (approved_topic_id) REFERENCES syllabus_topics(id)
);
