USE smartlink_schools;

CREATE TABLE IF NOT EXISTS timetable_rooms (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(60) NOT NULL,
  name VARCHAR(160) NOT NULL,
  room_type ENUM('ordinary_classroom', 'laboratory', 'computer_lab', 'library', 'workshop', 'art_room', 'music_room', 'sports_ground', 'hall', 'special_needs', 'office', 'custom') NOT NULL DEFAULT 'ordinary_classroom',
  capacity INT UNSIGNED NULL,
  exam_capacity INT UNSIGNED NULL,
  building VARCHAR(120) NULL,
  floor_label VARCHAR(60) NULL,
  accessibility JSON NULL,
  equipment JSON NULL,
  home_class_id BIGINT UNSIGNED NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_timetable_rooms_school_code (school_id, code),
  KEY idx_timetable_rooms_school_type (school_id, room_type, active),
  CONSTRAINT fk_timetable_rooms_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_timetable_rooms_home_class FOREIGN KEY (home_class_id) REFERENCES classes(id),
  CONSTRAINT fk_timetable_rooms_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS timetable_resources (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(60) NOT NULL,
  name VARCHAR(160) NOT NULL,
  resource_type ENUM('projector', 'computer', 'laboratory_kit', 'workshop_equipment', 'sports_equipment', 'music_equipment', 'vehicle', 'custom') NOT NULL DEFAULT 'custom',
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  metadata JSON NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_timetable_resources_school_code (school_id, code),
  KEY idx_timetable_resources_school_type (school_id, resource_type, active),
  CONSTRAINT fk_timetable_resources_school FOREIGN KEY (school_id) REFERENCES schools(id)
);

CREATE TABLE IF NOT EXISTS timetables (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  timetable_type ENUM('SCHOOL_TIMETABLE', 'EXAM_TIMETABLE') NOT NULL,
  name VARCHAR(180) NOT NULL,
  academic_year_id BIGINT UNSIGNED NOT NULL,
  term_id BIGINT UNSIGNED NULL,
  cycle_type ENUM('NORMAL_WEEK', 'WEEK_A_WEEK_B', 'ROTATING_CYCLE', 'DATED_EXAM_SESSIONS', 'CUSTOM') NOT NULL DEFAULT 'NORMAL_WEEK',
  effective_from DATE NOT NULL,
  effective_to DATE NOT NULL,
  status ENUM('SETUP', 'VALIDATION_REQUIRED', 'READY', 'GENERATING', 'DRAFT', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', 'SUPERSEDED', 'ARCHIVED') NOT NULL DEFAULT 'SETUP',
  current_published_version_id BIGINT UNSIGNED NULL,
  setup_progress JSON NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_timetables_school_context_name (school_id, timetable_type, academic_year_id, term_id, name),
  KEY idx_timetables_school_type_status (school_id, timetable_type, status),
  KEY idx_timetables_context (school_id, academic_year_id, term_id),
  CONSTRAINT fk_timetables_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_timetables_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_timetables_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_timetables_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS timetable_versions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  timetable_id BIGINT UNSIGNED NOT NULL,
  version_number INT UNSIGNED NOT NULL,
  parent_version_id BIGINT UNSIGNED NULL,
  status ENUM('SETUP', 'VALIDATION_REQUIRED', 'READY', 'GENERATING', 'DRAFT', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', 'SUPERSEDED', 'ARCHIVED') NOT NULL DEFAULT 'SETUP',
  creation_method ENUM('MANUAL', 'ASSISTED', 'AUTOMATIC', 'CLONED', 'IMPORTED') NOT NULL DEFAULT 'MANUAL',
  generation_strategy ENUM('BALANCED', 'TEACHER_FRIENDLY', 'STUDENT_LEARNING_OPTIMIZED', 'CANDIDATE_FRIENDLY', 'OPERATIONALLY_EFFICIENT', 'CUSTOM') NULL,
  solver_status ENUM('OPTIMAL', 'FEASIBLE', 'INFEASIBLE', 'MODEL_INVALID', 'TIME_LIMIT_REACHED_WITH_SOLUTION', 'TIME_LIMIT_REACHED_WITHOUT_SOLUTION', 'CANCELLED', 'FAILED') NULL,
  solver_score DECIMAL(12,2) NULL,
  hard_conflict_count INT UNSIGNED NOT NULL DEFAULT 0,
  soft_penalty_score DECIMAL(12,2) NOT NULL DEFAULT 0,
  configuration_snapshot JSON NULL,
  constraint_snapshot JSON NULL,
  source_snapshot_hash VARCHAR(128) NULL,
  change_summary TEXT NULL,
  internal_notes TEXT NULL,
  publication_notes TEXT NULL,
  solver_configuration_snapshot JSON NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  approved_by BIGINT UNSIGNED NULL,
  published_by BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  reviewed_at TIMESTAMP NULL,
  approved_at TIMESTAMP NULL,
  published_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_timetable_version_number (timetable_id, version_number),
  KEY idx_timetable_versions_status (timetable_id, status),
  KEY idx_timetable_versions_parent (parent_version_id),
  CONSTRAINT fk_timetable_versions_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_timetable_versions_parent FOREIGN KEY (parent_version_id) REFERENCES timetable_versions(id),
  CONSTRAINT fk_timetable_versions_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_timetable_versions_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id),
  CONSTRAINT fk_timetable_versions_approved_by FOREIGN KEY (approved_by) REFERENCES users(id),
  CONSTRAINT fk_timetable_versions_published_by FOREIGN KEY (published_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS timetable_cycle_days (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  timetable_id BIGINT UNSIGNED NOT NULL,
  cycle_day_number INT UNSIGNED NOT NULL,
  code VARCHAR(40) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  weekday TINYINT UNSIGNED NULL,
  sort_order INT NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_timetable_cycle_day_number (timetable_id, cycle_day_number),
  UNIQUE KEY uq_timetable_cycle_day_code (timetable_id, code),
  KEY idx_timetable_cycle_days_active (timetable_id, active, sort_order),
  CONSTRAINT fk_timetable_cycle_days_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id)
);

CREATE TABLE IF NOT EXISTS bell_schedule_templates (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  timetable_id BIGINT UNSIGNED NULL,
  name VARCHAR(160) NOT NULL,
  description TEXT NULL,
  shift_id VARCHAR(80) NULL,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_bell_templates_school (school_id, active, is_default),
  KEY idx_bell_templates_timetable (timetable_id, active),
  CONSTRAINT fk_bell_templates_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_bell_templates_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_bell_templates_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bell_schedule_slots (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  template_id BIGINT UNSIGNED NOT NULL,
  slot_number INT UNSIGNED NOT NULL,
  code VARCHAR(40) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  slot_type ENUM('TEACHING_PERIOD', 'BREAK', 'LUNCH', 'ASSEMBLY', 'CHAPEL', 'CLUB', 'SPORTS', 'STAFF_MEETING', 'STUDY', 'CUSTOM', 'CLOSED') NOT NULL DEFAULT 'TEACHING_PERIOD',
  teaching_allowed TINYINT(1) NOT NULL DEFAULT 1,
  can_span TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_bell_slot_number (template_id, slot_number),
  UNIQUE KEY uq_bell_slot_code (template_id, code),
  KEY idx_bell_slots_template_sort (template_id, sort_order),
  CONSTRAINT fk_bell_slots_template FOREIGN KEY (template_id) REFERENCES bell_schedule_templates(id)
);

CREATE TABLE IF NOT EXISTS timetable_day_templates (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  timetable_id BIGINT UNSIGNED NOT NULL,
  cycle_day_id BIGINT UNSIGNED NOT NULL,
  bell_template_id BIGINT UNSIGNED NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_timetable_day_template (timetable_id, cycle_day_id),
  CONSTRAINT fk_day_templates_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_day_templates_cycle_day FOREIGN KEY (cycle_day_id) REFERENCES timetable_cycle_days(id),
  CONSTRAINT fk_day_templates_bell_template FOREIGN KEY (bell_template_id) REFERENCES bell_schedule_templates(id)
);

CREATE TABLE IF NOT EXISTS timetable_requirements (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  timetable_id BIGINT UNSIGNED NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  requirement_type ENUM('CLASS_SUBJECT', 'STUDENT_GROUP_SUBJECT', 'FIXED_ACTIVITY', 'EXAM_PAPER') NOT NULL DEFAULT 'CLASS_SUBJECT',
  class_id BIGINT UNSIGNED NULL,
  stream_section VARCHAR(80) NULL,
  subject_id BIGINT UNSIGNED NULL,
  teacher_id BIGINT UNSIGNED NULL,
  eligible_teacher_ids JSON NULL,
  room_type VARCHAR(80) NULL,
  required_room_id BIGINT UNSIGNED NULL,
  periods_per_cycle INT UNSIGNED NOT NULL DEFAULT 0,
  min_periods_per_day INT UNSIGNED NULL,
  max_periods_per_day INT UNSIGNED NULL,
  allowed_block_lengths JSON NULL,
  preferred_slots JSON NULL,
  avoided_slots JSON NULL,
  fixed_assignments JSON NULL,
  intensity_weight INT NOT NULL DEFAULT 1,
  metadata JSON NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_timetable_requirements_scope (school_id, timetable_id, requirement_type, active),
  KEY idx_timetable_requirements_class_subject (school_id, class_id, subject_id, teacher_id),
  CONSTRAINT fk_timetable_requirements_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_timetable_requirements_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_timetable_requirements_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_timetable_requirements_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_timetable_requirements_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
  CONSTRAINT fk_timetable_requirements_room FOREIGN KEY (required_room_id) REFERENCES timetable_rooms(id),
  CONSTRAINT fk_timetable_requirements_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS timetable_entries (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  timetable_version_id BIGINT UNSIGNED NOT NULL,
  cycle_day_id BIGINT UNSIGNED NULL,
  calendar_date DATE NULL,
  slot_start_id BIGINT UNSIGNED NOT NULL,
  slot_end_id BIGINT UNSIGNED NOT NULL,
  entry_type ENUM('LESSON', 'ASSEMBLY', 'CHAPEL', 'SPORTS', 'CLUB', 'STUDY', 'STAFF_MEETING', 'EXAM_PAPER', 'INVIGILATION', 'ROOM_HOLD', 'CUSTOM') NOT NULL DEFAULT 'LESSON',
  subject_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  stream_section VARCHAR(80) NULL,
  student_group_id BIGINT UNSIGNED NULL,
  teacher_id BIGINT UNSIGNED NULL,
  room_id BIGINT UNSIGNED NULL,
  source_requirement_id BIGINT UNSIGNED NULL,
  assessment_id BIGINT UNSIGNED NULL,
  exam_session_id BIGINT UNSIGNED NULL,
  title VARCHAR(180) NULL,
  locked TINYINT(1) NOT NULL DEFAULT 0,
  lock_reason VARCHAR(255) NULL,
  manually_modified TINYINT(1) NOT NULL DEFAULT 0,
  modification_reason VARCHAR(255) NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_timetable_entries_version_day_slot (timetable_version_id, cycle_day_id, calendar_date, slot_start_id, slot_end_id),
  KEY idx_timetable_entries_teacher (timetable_version_id, teacher_id, cycle_day_id, calendar_date),
  KEY idx_timetable_entries_class (timetable_version_id, class_id, cycle_day_id, calendar_date),
  KEY idx_timetable_entries_room (timetable_version_id, room_id, cycle_day_id, calendar_date),
  KEY idx_timetable_entries_subject (timetable_version_id, subject_id),
  CONSTRAINT fk_timetable_entries_version FOREIGN KEY (timetable_version_id) REFERENCES timetable_versions(id),
  CONSTRAINT fk_timetable_entries_cycle_day FOREIGN KEY (cycle_day_id) REFERENCES timetable_cycle_days(id),
  CONSTRAINT fk_timetable_entries_slot_start FOREIGN KEY (slot_start_id) REFERENCES bell_schedule_slots(id),
  CONSTRAINT fk_timetable_entries_slot_end FOREIGN KEY (slot_end_id) REFERENCES bell_schedule_slots(id),
  CONSTRAINT fk_timetable_entries_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_timetable_entries_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_timetable_entries_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
  CONSTRAINT fk_timetable_entries_room FOREIGN KEY (room_id) REFERENCES timetable_rooms(id),
  CONSTRAINT fk_timetable_entries_requirement FOREIGN KEY (source_requirement_id) REFERENCES timetable_requirements(id),
  CONSTRAINT fk_timetable_entries_assessment FOREIGN KEY (assessment_id) REFERENCES assessments(id),
  CONSTRAINT fk_timetable_entries_exam_session FOREIGN KEY (exam_session_id) REFERENCES exam_sessions(id),
  CONSTRAINT fk_timetable_entries_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_timetable_entries_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS timetable_entry_resources (
  entry_id BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (entry_id, resource_id),
  CONSTRAINT fk_entry_resources_entry FOREIGN KEY (entry_id) REFERENCES timetable_entries(id),
  CONSTRAINT fk_entry_resources_resource FOREIGN KEY (resource_id) REFERENCES timetable_resources(id)
);

CREATE TABLE IF NOT EXISTS timetable_constraints (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  timetable_id BIGINT UNSIGNED NULL,
  timetable_version_id BIGINT UNSIGNED NULL,
  timetable_type ENUM('SCHOOL_TIMETABLE', 'EXAM_TIMETABLE') NOT NULL,
  constraint_code VARCHAR(120) NOT NULL,
  constraint_category VARCHAR(80) NOT NULL,
  severity ENUM('HARD', 'SOFT') NOT NULL DEFAULT 'HARD',
  weight INT NOT NULL DEFAULT 1000,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  scope_type VARCHAR(80) NOT NULL DEFAULT 'SCHOOL',
  scope_reference_id BIGINT UNSIGNED NULL,
  configuration JSON NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_timetable_constraints_scope (school_id, timetable_type, enabled, severity),
  KEY idx_timetable_constraints_timetable (timetable_id, enabled),
  KEY idx_timetable_constraints_version (timetable_version_id, enabled),
  CONSTRAINT fk_timetable_constraints_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_timetable_constraints_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_timetable_constraints_version FOREIGN KEY (timetable_version_id) REFERENCES timetable_versions(id),
  CONSTRAINT fk_timetable_constraints_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_timetable_constraints_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS teacher_availability_rules (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  teacher_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NOT NULL,
  term_id BIGINT UNSIGNED NULL,
  timetable_id BIGINT UNSIGNED NULL,
  cycle_day_id BIGINT UNSIGNED NULL,
  weekday TINYINT UNSIGNED NULL,
  slot_start_id BIGINT UNSIGNED NULL,
  slot_end_id BIGINT UNSIGNED NULL,
  availability_status ENUM('AVAILABLE', 'PREFERRED', 'AVOID', 'UNAVAILABLE') NOT NULL DEFAULT 'AVAILABLE',
  reason VARCHAR(255) NULL,
  effective_from DATE NULL,
  effective_to DATE NULL,
  preference_weight INT NOT NULL DEFAULT 0,
  approved_status ENUM('DRAFT', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'APPROVED',
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_teacher_availability_teacher (school_id, teacher_id, academic_year_id, term_id),
  CONSTRAINT fk_teacher_availability_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_teacher_availability_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
  CONSTRAINT fk_teacher_availability_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_teacher_availability_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_teacher_availability_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_teacher_availability_cycle_day FOREIGN KEY (cycle_day_id) REFERENCES timetable_cycle_days(id),
  CONSTRAINT fk_teacher_availability_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS room_availability_rules (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  room_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NOT NULL,
  term_id BIGINT UNSIGNED NULL,
  timetable_id BIGINT UNSIGNED NULL,
  cycle_day_id BIGINT UNSIGNED NULL,
  weekday TINYINT UNSIGNED NULL,
  slot_start_id BIGINT UNSIGNED NULL,
  slot_end_id BIGINT UNSIGNED NULL,
  availability_status ENUM('AVAILABLE', 'PREFERRED', 'AVOID', 'UNAVAILABLE') NOT NULL DEFAULT 'AVAILABLE',
  reason VARCHAR(255) NULL,
  effective_from DATE NULL,
  effective_to DATE NULL,
  approved_status ENUM('DRAFT', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'APPROVED',
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_room_availability_room (school_id, room_id, academic_year_id, term_id),
  CONSTRAINT fk_room_availability_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_room_availability_room FOREIGN KEY (room_id) REFERENCES timetable_rooms(id),
  CONSTRAINT fk_room_availability_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_room_availability_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_room_availability_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_room_availability_cycle_day FOREIGN KEY (cycle_day_id) REFERENCES timetable_cycle_days(id),
  CONSTRAINT fk_room_availability_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS resource_availability_rules (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NOT NULL,
  term_id BIGINT UNSIGNED NULL,
  timetable_id BIGINT UNSIGNED NULL,
  cycle_day_id BIGINT UNSIGNED NULL,
  weekday TINYINT UNSIGNED NULL,
  slot_start_id BIGINT UNSIGNED NULL,
  slot_end_id BIGINT UNSIGNED NULL,
  availability_status ENUM('AVAILABLE', 'PREFERRED', 'AVOID', 'UNAVAILABLE') NOT NULL DEFAULT 'AVAILABLE',
  reason VARCHAR(255) NULL,
  effective_from DATE NULL,
  effective_to DATE NULL,
  approved_status ENUM('DRAFT', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'APPROVED',
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_resource_availability_resource (school_id, resource_id, academic_year_id, term_id),
  CONSTRAINT fk_resource_availability_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_resource_availability_resource FOREIGN KEY (resource_id) REFERENCES timetable_resources(id),
  CONSTRAINT fk_resource_availability_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_resource_availability_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_resource_availability_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_resource_availability_cycle_day FOREIGN KEY (cycle_day_id) REFERENCES timetable_cycle_days(id),
  CONSTRAINT fk_resource_availability_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS timetable_generation_jobs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  timetable_id BIGINT UNSIGNED NOT NULL,
  timetable_version_id BIGINT UNSIGNED NOT NULL,
  job_status ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'QUEUED',
  progress_stage ENUM('PREPARING_INPUT', 'RUNNING_FEASIBILITY_AUDIT', 'CONSTRUCTING_SOLVER_MODEL', 'SEARCHING_FOR_SOLUTION', 'VALIDATING_RESULT', 'SAVING_DRAFT', 'COMPLETE') NOT NULL DEFAULT 'PREPARING_INPUT',
  requested_by BIGINT UNSIGNED NOT NULL,
  generation_strategy VARCHAR(80) NULL,
  solver_status VARCHAR(80) NULL,
  error_code VARCHAR(80) NULL,
  user_message VARCHAR(255) NULL,
  internal_diagnostics JSON NULL,
  solver_metrics JSON NULL,
  started_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_generation_jobs_school_status (school_id, job_status, created_at),
  KEY idx_generation_jobs_version (timetable_version_id, job_status),
  CONSTRAINT fk_generation_jobs_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_generation_jobs_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_generation_jobs_version FOREIGN KEY (timetable_version_id) REFERENCES timetable_versions(id),
  CONSTRAINT fk_generation_jobs_requested_by FOREIGN KEY (requested_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS timetable_conflicts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  timetable_version_id BIGINT UNSIGNED NOT NULL,
  conflict_code VARCHAR(120) NOT NULL,
  severity ENUM('HARD', 'SOFT') NOT NULL DEFAULT 'HARD',
  affected_entity_type VARCHAR(80) NOT NULL,
  affected_entity_ids JSON NULL,
  entry_ids JSON NULL,
  human_message VARCHAR(255) NOT NULL,
  resolution_suggestions JSON NULL,
  resolved TINYINT(1) NOT NULL DEFAULT 0,
  resolved_by BIGINT UNSIGNED NULL,
  resolved_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_timetable_conflicts_version (timetable_version_id, resolved, severity),
  KEY idx_timetable_conflicts_school (school_id, conflict_code, resolved),
  CONSTRAINT fk_timetable_conflicts_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_timetable_conflicts_version FOREIGN KEY (timetable_version_id) REFERENCES timetable_versions(id),
  CONSTRAINT fk_timetable_conflicts_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS timetable_review_comments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  timetable_version_id BIGINT UNSIGNED NOT NULL,
  comment_type ENUM('COMMENT', 'CHANGE_REQUEST', 'APPROVAL_NOTE', 'PUBLICATION_NOTE') NOT NULL DEFAULT 'COMMENT',
  body TEXT NOT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_review_comments_version (timetable_version_id, created_at),
  CONSTRAINT fk_review_comments_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_review_comments_version FOREIGN KEY (timetable_version_id) REFERENCES timetable_versions(id),
  CONSTRAINT fk_review_comments_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS timetable_audit_events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  timetable_id BIGINT UNSIGNED NULL,
  timetable_version_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  action VARCHAR(120) NOT NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id BIGINT UNSIGNED NULL,
  previous_values JSON NULL,
  new_values JSON NULL,
  reason VARCHAR(255) NULL,
  correlation_id VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_timetable_audit_scope (school_id, timetable_id, timetable_version_id, created_at),
  KEY idx_timetable_audit_actor (school_id, actor_user_id, created_at),
  CONSTRAINT fk_timetable_audit_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_timetable_audit_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_timetable_audit_version FOREIGN KEY (timetable_version_id) REFERENCES timetable_versions(id),
  CONSTRAINT fk_timetable_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS timetable_publications (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  timetable_id BIGINT UNSIGNED NOT NULL,
  timetable_version_id BIGINT UNSIGNED NOT NULL,
  publication_status ENUM('ACTIVE', 'SUPERSEDED', 'REVOKED') NOT NULL DEFAULT 'ACTIVE',
  audience_scope JSON NULL,
  snapshot JSON NOT NULL,
  published_by BIGINT UNSIGNED NOT NULL,
  published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  superseded_at TIMESTAMP NULL,
  UNIQUE KEY uq_active_publication_version (timetable_version_id),
  KEY idx_timetable_publications_scope (school_id, timetable_id, publication_status, published_at),
  CONSTRAINT fk_timetable_publications_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_timetable_publications_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id),
  CONSTRAINT fk_timetable_publications_version FOREIGN KEY (timetable_version_id) REFERENCES timetable_versions(id),
  CONSTRAINT fk_timetable_publications_published_by FOREIGN KEY (published_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS daily_schedule_adjustments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  timetable_entry_id BIGINT UNSIGNED NULL,
  timetable_version_id BIGINT UNSIGNED NULL,
  adjustment_date DATE NOT NULL,
  adjustment_type ENUM('TEACHER_SUBSTITUTION', 'ROOM_CHANGE', 'TIME_CHANGE', 'CANCELLED_LESSON', 'EXTRA_LESSON', 'SCHOOL_EVENT', 'EMERGENCY_CLOSURE', 'CUSTOM') NOT NULL,
  replacement_teacher_id BIGINT UNSIGNED NULL,
  replacement_room_id BIGINT UNSIGNED NULL,
  replacement_slot_start_id BIGINT UNSIGNED NULL,
  replacement_slot_end_id BIGINT UNSIGNED NULL,
  reason VARCHAR(255) NOT NULL,
  status ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
  approved_by BIGINT UNSIGNED NULL,
  approved_at TIMESTAMP NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_daily_adjustments_date (school_id, adjustment_date, status),
  KEY idx_daily_adjustments_entry (timetable_entry_id, adjustment_date),
  CONSTRAINT fk_daily_adjustments_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_daily_adjustments_entry FOREIGN KEY (timetable_entry_id) REFERENCES timetable_entries(id),
  CONSTRAINT fk_daily_adjustments_version FOREIGN KEY (timetable_version_id) REFERENCES timetable_versions(id),
  CONSTRAINT fk_daily_adjustments_teacher FOREIGN KEY (replacement_teacher_id) REFERENCES users(id),
  CONSTRAINT fk_daily_adjustments_room FOREIGN KEY (replacement_room_id) REFERENCES timetable_rooms(id),
  CONSTRAINT fk_daily_adjustments_slot_start FOREIGN KEY (replacement_slot_start_id) REFERENCES bell_schedule_slots(id),
  CONSTRAINT fk_daily_adjustments_slot_end FOREIGN KEY (replacement_slot_end_id) REFERENCES bell_schedule_slots(id),
  CONSTRAINT fk_daily_adjustments_approved_by FOREIGN KEY (approved_by) REFERENCES users(id),
  CONSTRAINT fk_daily_adjustments_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);
