CREATE TABLE IF NOT EXISTS exam_lab_diagrams (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  paper_id BIGINT UNSIGNED NOT NULL,
  version_id BIGINT UNSIGNED NOT NULL,
  candidate_id BIGINT UNSIGNED NULL,
  question_id BIGINT UNSIGNED NULL,
  page_number INT NULL,
  diagram_kind ENUM('diagram', 'graph', 'table', 'formula', 'image', 'unknown') NOT NULL DEFAULT 'unknown',
  source_type ENUM('pdf_image', 'uploaded_image', 'ai_description', 'text_signal') NOT NULL DEFAULT 'text_signal',
  file_path VARCHAR(500) NULL,
  image_hash CHAR(64) NULL,
  metadata_hash CHAR(64) NULL,
  perceptual_hash CHAR(64) NULL,
  width_px INT UNSIGNED NULL,
  height_px INT UNSIGNED NULL,
  x_ppi INT UNSIGNED NULL,
  y_ppi INT UNSIGNED NULL,
  color_space VARCHAR(80) NULL,
  component_count INT UNSIGNED NULL,
  bits_per_component INT UNSIGNED NULL,
  pdf_object_id VARCHAR(80) NULL,
  description TEXT NULL,
  formulas_json JSON NULL,
  tables_json JSON NULL,
  metadata_json JSON NULL,
  duplicate_of_diagram_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_exam_lab_diagrams_paper (paper_id, diagram_kind),
  KEY idx_exam_lab_diagrams_version (version_id, source_type),
  KEY idx_exam_lab_diagrams_candidate (candidate_id),
  KEY idx_exam_lab_diagrams_question (question_id),
  KEY idx_exam_lab_diagrams_image_hash (image_hash),
  KEY idx_exam_lab_diagrams_metadata_hash (metadata_hash),
  KEY idx_exam_lab_diagrams_duplicate (duplicate_of_diagram_id),
  CONSTRAINT fk_exam_lab_diagrams_paper FOREIGN KEY (paper_id) REFERENCES exam_lab_papers(id),
  CONSTRAINT fk_exam_lab_diagrams_version FOREIGN KEY (version_id) REFERENCES exam_lab_paper_versions(id),
  CONSTRAINT fk_exam_lab_diagrams_candidate FOREIGN KEY (candidate_id) REFERENCES exam_lab_question_candidates(id),
  CONSTRAINT fk_exam_lab_diagrams_question FOREIGN KEY (question_id) REFERENCES exam_lab_questions(id),
  CONSTRAINT fk_exam_lab_diagrams_duplicate FOREIGN KEY (duplicate_of_diagram_id) REFERENCES exam_lab_diagrams(id)
);
