USE smartlink_schools;

-- SmartLink Academic Intelligence, institutional resources, library operations and
-- teacher-operated Classroom Mode. Existing syllabus, assessment, attendance,
-- lesson-log, notification and term records remain the system of record.

ALTER TABLE users
  MODIFY COLUMN role ENUM('super_admin','school_owner','director','owner','headteacher','bursar','librarian','teacher','parent','student') NOT NULL;

ALTER TABLE attendance_records
  MODIFY COLUMN status ENUM('present','absent','late','sick','excused','left_early') NOT NULL;

ALTER TABLE notifications
  MODIFY COLUMN category ENUM('finance','academics','library','staff','admissions','operations','system') NOT NULL DEFAULT 'system';

ALTER TABLE learning_objectives
  ADD COLUMN IF NOT EXISTS public_ref CHAR(36) NULL,
  ADD COLUMN IF NOT EXISTS school_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS subject_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS class_level VARCHAR(80) NULL,
  ADD COLUMN IF NOT EXISTS expected_competency TEXT NULL,
  ADD COLUMN IF NOT EXISTS recommended_lesson_count INT NULL,
  ADD COLUMN IF NOT EXISTS expected_difficulty ENUM('easy','medium','hard') NULL,
  ADD COLUMN IF NOT EXISTS curriculum_order INT NULL,
  ADD COLUMN IF NOT EXISTS is_mandatory TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1;

UPDATE learning_objectives lo
JOIN syllabus_topics st ON st.id = lo.topic_id
SET lo.school_id = st.school_id,
    lo.subject_id = st.subject_id,
    lo.public_ref = COALESCE(lo.public_ref, UUID())
WHERE lo.school_id IS NULL OR lo.subject_id IS NULL OR lo.public_ref IS NULL;

ALTER TABLE learning_objectives
  MODIFY COLUMN public_ref CHAR(36) NOT NULL,
  MODIFY COLUMN school_id BIGINT UNSIGNED NOT NULL,
  ADD UNIQUE KEY IF NOT EXISTS uq_learning_objective_ref (public_ref),
  ADD KEY IF NOT EXISTS idx_learning_objective_scope (school_id, subject_id, topic_id, is_active),
  ADD CONSTRAINT fk_learning_objective_school FOREIGN KEY (school_id) REFERENCES schools(id),
  ADD CONSTRAINT fk_learning_objective_subject FOREIGN KEY (subject_id) REFERENCES subjects(id);

CREATE TABLE IF NOT EXISTS learning_objective_prerequisites (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  learning_objective_id BIGINT UNSIGNED NOT NULL,
  prerequisite_objective_id BIGINT UNSIGNED NOT NULL,
  strength ENUM('required','recommended') NOT NULL DEFAULT 'required',
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_objective_prerequisite (school_id, learning_objective_id, prerequisite_objective_id),
  UNIQUE KEY uq_objective_prerequisite_ref (public_ref),
  KEY idx_objective_prerequisite_reverse (school_id, prerequisite_objective_id),
  CONSTRAINT fk_objective_prerequisite_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_objective_prerequisite_objective FOREIGN KEY (learning_objective_id) REFERENCES learning_objectives(id),
  CONSTRAINT fk_objective_prerequisite_required FOREIGN KEY (prerequisite_objective_id) REFERENCES learning_objectives(id),
  CONSTRAINT fk_objective_prerequisite_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS curriculum_delivery_records (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NOT NULL,
  term_id BIGINT UNSIGNED NOT NULL,
  class_id BIGINT UNSIGNED NOT NULL,
  stream_section VARCHAR(80) NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  teacher_id BIGINT UNSIGNED NULL,
  curriculum_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NOT NULL,
  subtopic_id BIGINT UNSIGNED NULL,
  learning_objective_id BIGINT UNSIGNED NULL,
  planned_start_date DATE NULL,
  planned_completion_date DATE NULL,
  actual_start_date DATE NULL,
  actual_completion_date DATE NULL,
  planned_lesson_count INT NOT NULL DEFAULT 0,
  completed_lesson_count INT NOT NULL DEFAULT 0,
  periods_spent DECIMAL(8,2) NOT NULL DEFAULT 0,
  lifecycle_status ENUM('NOT_STARTED','PLANNED','IN_PROGRESS','TAUGHT','ASSESSED','PARTIALLY_MASTERED','MASTERED','REQUIRES_REVISION','DELAYED','SKIPPED') NOT NULL DEFAULT 'NOT_STARTED',
  teacher_confidence ENUM('low','medium','high') NULL,
  teacher_notes TEXT NULL,
  assessed_status TINYINT(1) NOT NULL DEFAULT 0,
  class_mastery_score DECIMAL(5,2) NULL,
  mastery_confidence_score DECIMAL(5,2) NULL,
  students_assessed INT NOT NULL DEFAULT 0,
  students_below_threshold INT NOT NULL DEFAULT 0,
  revision_required TINYINT(1) NOT NULL DEFAULT 0,
  delay_reason TEXT NULL,
  skipped_reason TEXT NULL,
  evidence_source VARCHAR(80) NULL,
  last_recalculated_at TIMESTAMP NULL,
  manually_overridden TINYINT(1) NOT NULL DEFAULT 0,
  override_author_id BIGINT UNSIGNED NULL,
  override_reason TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_curriculum_delivery_ref (public_ref),
  UNIQUE KEY uq_curriculum_delivery_scope (school_id, academic_year_id, term_id, class_id, subject_id, topic_id, subtopic_id, learning_objective_id),
  KEY idx_curriculum_delivery_dashboard (school_id, academic_year_id, term_id, lifecycle_status, subject_id, class_id),
  CONSTRAINT fk_curriculum_delivery_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_curriculum_delivery_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_curriculum_delivery_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_curriculum_delivery_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_curriculum_delivery_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_curriculum_delivery_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
  CONSTRAINT fk_curriculum_delivery_curriculum FOREIGN KEY (curriculum_id) REFERENCES curricula(id),
  CONSTRAINT fk_curriculum_delivery_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_curriculum_delivery_subtopic FOREIGN KEY (subtopic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_curriculum_delivery_objective FOREIGN KEY (learning_objective_id) REFERENCES learning_objectives(id),
  CONSTRAINT fk_curriculum_delivery_override FOREIGN KEY (override_author_id) REFERENCES users(id)
);

ALTER TABLE question_bank
  ADD COLUMN IF NOT EXISTS public_ref CHAR(36) NULL,
  ADD COLUMN IF NOT EXISTS learning_objective_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS scope_type ENUM('school_private','global_approved') NOT NULL DEFAULT 'school_private',
  ADD COLUMN IF NOT EXISTS response_format VARCHAR(80) NULL,
  ADD COLUMN IF NOT EXISTS cognitive_level VARCHAR(80) NULL,
  ADD COLUMN IF NOT EXISTS measured_difficulty DECIMAL(5,2) NULL,
  ADD COLUMN IF NOT EXISTS estimated_completion_seconds INT NULL,
  ADD COLUMN IF NOT EXISTS source_year YEAR NULL,
  ADD COLUMN IF NOT EXISTS source_paper VARCHAR(180) NULL,
  ADD COLUMN IF NOT EXISTS examination_board VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS worked_solution TEXT NULL,
  ADD COLUMN IF NOT EXISTS common_misconceptions_json JSON NULL,
  ADD COLUMN IF NOT EXISTS moderation_status ENUM('unreviewed','reviewed','approved','flagged') NOT NULL DEFAULT 'unreviewed',
  ADD COLUMN IF NOT EXISTS version_number INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP NULL;

UPDATE question_bank SET public_ref = UUID() WHERE public_ref IS NULL;

ALTER TABLE question_bank
  MODIFY COLUMN public_ref CHAR(36) NOT NULL,
  ADD UNIQUE KEY IF NOT EXISTS uq_question_bank_public_ref (public_ref),
  ADD KEY IF NOT EXISTS idx_question_objective_scope (school_id, learning_objective_id, approval_status),
  ADD CONSTRAINT fk_question_learning_objective FOREIGN KEY (learning_objective_id) REFERENCES learning_objectives(id);

CREATE TABLE IF NOT EXISTS question_attempt_analytics (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  question_id BIGINT UNSIGNED NOT NULL,
  total_attempts INT NOT NULL DEFAULT 0,
  correct_attempts INT NOT NULL DEFAULT 0,
  partially_correct_attempts INT NOT NULL DEFAULT 0,
  incorrect_attempts INT NOT NULL DEFAULT 0,
  omitted_attempts INT NOT NULL DEFAULT 0,
  success_rate DECIMAL(5,2) NULL,
  average_marks DECIMAL(8,2) NULL,
  average_completion_seconds DECIMAL(10,2) NULL,
  discrimination_value DECIMAL(7,4) NULL,
  reliability_score DECIMAL(5,2) NULL,
  confidence_score DECIMAL(5,2) NOT NULL DEFAULT 0,
  common_wrong_answers_json JSON NULL,
  misconception_patterns_json JSON NULL,
  flags_json JSON NULL,
  last_calculated_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_question_analytics_scope (school_id, question_id),
  UNIQUE KEY uq_question_analytics_ref (public_ref),
  CONSTRAINT fk_question_analytics_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_question_analytics_question FOREIGN KEY (question_id) REFERENCES question_bank(id)
);

CREATE TABLE IF NOT EXISTS mastery_evidence (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  student_id BIGINT UNSIGNED NOT NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  topic_id BIGINT UNSIGNED NULL,
  subtopic_id BIGINT UNSIGNED NULL,
  learning_objective_id BIGINT UNSIGNED NULL,
  evidence_type ENUM('assessment_question','assessment_total','daily_drill','reassessment','teacher_confirmed','classroom_formative','legacy_result') NOT NULL,
  source_entity_type VARCHAR(80) NOT NULL,
  source_entity_id BIGINT UNSIGNED NULL,
  score_percentage DECIMAL(5,2) NULL,
  marks_awarded DECIMAL(8,2) NULL,
  marks_available DECIMAL(8,2) NULL,
  difficulty_weight DECIMAL(6,3) NOT NULL DEFAULT 1,
  assessment_weight DECIMAL(6,3) NOT NULL DEFAULT 1,
  independence_weight DECIMAL(6,3) NOT NULL DEFAULT 1,
  evidence_granularity ENUM('objective','subtopic','topic','subject_total','limited') NOT NULL DEFAULT 'topic',
  evidence_at TIMESTAMP NOT NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_mastery_evidence_ref (public_ref),
  UNIQUE KEY uq_mastery_evidence_source (school_id, student_id, source_entity_type, source_entity_id, learning_objective_id, topic_id),
  KEY idx_mastery_evidence_student (school_id, student_id, subject_id, evidence_at),
  KEY idx_mastery_evidence_objective (school_id, learning_objective_id, evidence_at),
  CONSTRAINT fk_mastery_evidence_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_mastery_evidence_student FOREIGN KEY (student_id) REFERENCES students(id),
  CONSTRAINT fk_mastery_evidence_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_mastery_evidence_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_mastery_evidence_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_mastery_evidence_subtopic FOREIGN KEY (subtopic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_mastery_evidence_objective FOREIGN KEY (learning_objective_id) REFERENCES learning_objectives(id)
);

CREATE TABLE IF NOT EXISTS academic_mastery_records (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  student_id BIGINT UNSIGNED NOT NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  topic_id BIGINT UNSIGNED NULL,
  subtopic_id BIGINT UNSIGNED NULL,
  learning_objective_id BIGINT UNSIGNED NULL,
  mastery_level ENUM('subject','topic','subtopic','objective') NOT NULL,
  mastery_score DECIMAL(5,2) NULL,
  confidence_score DECIMAL(5,2) NOT NULL DEFAULT 0,
  mastery_status ENUM('NOT_ASSESSED','INSUFFICIENT_EVIDENCE','EMERGING','DEVELOPING','PARTIALLY_MASTERED','MASTERED','ADVANCED','DECLINING','REQUIRES_INTERVENTION') NOT NULL DEFAULT 'NOT_ASSESSED',
  trend ENUM('IMPROVING','STEADY','DECLINING','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  evidence_count INT NOT NULL DEFAULT 0,
  calculation_explanation_json JSON NULL,
  primary_weaknesses_json JSON NULL,
  last_evidence_at TIMESTAMP NULL,
  last_recalculated_at TIMESTAMP NULL,
  manually_overridden TINYINT(1) NOT NULL DEFAULT 0,
  override_author_id BIGINT UNSIGNED NULL,
  override_reason TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_academic_mastery_ref (public_ref),
  UNIQUE KEY uq_academic_mastery_scope (school_id, student_id, subject_id, mastery_level, topic_id, subtopic_id, learning_objective_id),
  KEY idx_academic_mastery_risk (school_id, subject_id, mastery_status, confidence_score),
  CONSTRAINT fk_academic_mastery_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_academic_mastery_student FOREIGN KEY (student_id) REFERENCES students(id),
  CONSTRAINT fk_academic_mastery_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_academic_mastery_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_academic_mastery_subtopic FOREIGN KEY (subtopic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_academic_mastery_objective FOREIGN KEY (learning_objective_id) REFERENCES learning_objectives(id),
  CONSTRAINT fk_academic_mastery_override FOREIGN KEY (override_author_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS academic_engine_config (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT UNSIGNED NOT NULL,
  mastery_threshold DECIMAL(5,2) NOT NULL DEFAULT 70,
  intervention_threshold DECIMAL(5,2) NOT NULL DEFAULT 45,
  exam_readiness_threshold DECIMAL(5,2) NOT NULL DEFAULT 65,
  curriculum_delay_tolerance_days INT NOT NULL DEFAULT 5,
  minimum_evidence_count INT NOT NULL DEFAULT 3,
  recency_half_life_days INT NOT NULL DEFAULT 60,
  formative_weight DECIMAL(6,3) NOT NULL DEFAULT 0.7,
  summative_weight DECIMAL(6,3) NOT NULL DEFAULT 1,
  examination_weight DECIMAL(6,3) NOT NULL DEFAULT 1.2,
  drill_weight DECIMAL(6,3) NOT NULL DEFAULT 0.5,
  teacher_evidence_weight DECIMAL(6,3) NOT NULL DEFAULT 0.25,
  parent_visibility_json JSON NULL,
  terminology_json JSON NULL,
  alert_rules_json JSON NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_academic_engine_config_school (school_id),
  CONSTRAINT fk_academic_engine_config_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_academic_engine_config_user FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS academic_recommendations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  recommendation_type VARCHAR(80) NOT NULL,
  audience_role VARCHAR(60) NOT NULL,
  assigned_user_id BIGINT UNSIGNED NULL,
  student_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  title VARCHAR(200) NOT NULL,
  reason TEXT NOT NULL,
  evidence_json JSON NOT NULL,
  suggested_action TEXT NOT NULL,
  priority ENUM('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
  confidence_score DECIMAL(5,2) NULL,
  estimated_effort_minutes INT NULL,
  due_at TIMESTAMP NULL,
  status ENUM('NEW','REVIEWED','ACCEPTED','IN_PROGRESS','COMPLETED','DISMISSED','EXPIRED') NOT NULL DEFAULT 'NEW',
  dismissal_reason TEXT NULL,
  completion_notes TEXT NULL,
  rule_key VARCHAR(120) NULL,
  dedupe_window VARCHAR(80) NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_academic_recommendation_ref (public_ref),
  UNIQUE KEY uq_academic_recommendation_dedupe (school_id, rule_key, dedupe_window, assigned_user_id, student_id, class_id, topic_id),
  KEY idx_academic_recommendation_inbox (school_id, assigned_user_id, status, priority, due_at),
  CONSTRAINT fk_academic_recommendation_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_academic_recommendation_assignee FOREIGN KEY (assigned_user_id) REFERENCES users(id),
  CONSTRAINT fk_academic_recommendation_student FOREIGN KEY (student_id) REFERENCES students(id),
  CONSTRAINT fk_academic_recommendation_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_academic_recommendation_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_academic_recommendation_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_academic_recommendation_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS academic_interventions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  student_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  topic_id BIGINT UNSIGNED NULL,
  intervention_type ENUM('individual_remediation','small_group_support','whole_class_revision','attendance_intervention','prerequisite_recovery','enrichment','teacher_coaching','assessment_correction') NOT NULL,
  issue TEXT NOT NULL,
  evidence_json JSON NOT NULL,
  assigned_teacher_id BIGINT UNSIGNED NULL,
  priority ENUM('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
  start_date DATE NOT NULL,
  review_date DATE NULL,
  action_plan TEXT NOT NULL,
  parent_notification_status ENUM('not_required','pending','approved','sent') NOT NULL DEFAULT 'not_required',
  reassessment_summary_json JSON NULL,
  outcome ENUM('pending','improved','unchanged','declined','inconclusive') NOT NULL DEFAULT 'pending',
  status ENUM('draft','active','review_due','completed','cancelled') NOT NULL DEFAULT 'draft',
  created_by BIGINT UNSIGNED NOT NULL,
  completed_by BIGINT UNSIGNED NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_academic_intervention_ref (public_ref),
  KEY idx_academic_intervention_scope (school_id, status, review_date, subject_id, class_id),
  CONSTRAINT fk_academic_intervention_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_academic_intervention_student FOREIGN KEY (student_id) REFERENCES students(id),
  CONSTRAINT fk_academic_intervention_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_academic_intervention_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_academic_intervention_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_academic_intervention_teacher FOREIGN KEY (assigned_teacher_id) REFERENCES users(id),
  CONSTRAINT fk_academic_intervention_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_academic_intervention_completer FOREIGN KEY (completed_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS academic_intervention_updates (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  intervention_id BIGINT UNSIGNED NOT NULL,
  update_type ENUM('note','activity','reassessment','parent_contact','status_change') NOT NULL DEFAULT 'note',
  note TEXT NOT NULL,
  evidence_json JSON NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_academic_intervention_update_ref (public_ref),
  KEY idx_intervention_update_scope (school_id, intervention_id, created_at),
  CONSTRAINT fk_intervention_update_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_intervention_update_intervention FOREIGN KEY (intervention_id) REFERENCES academic_interventions(id) ON DELETE CASCADE,
  CONSTRAINT fk_intervention_update_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS exam_readiness_snapshots (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NULL,
  term_id BIGINT UNSIGNED NULL,
  student_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  scope_type ENUM('student','class','subject','school') NOT NULL,
  readiness_score DECIMAL(5,2) NOT NULL,
  confidence_score DECIMAL(5,2) NOT NULL,
  factors_json JSON NOT NULL,
  strengths_json JSON NULL,
  risks_json JSON NULL,
  missing_data_json JSON NULL,
  recommendations_json JSON NULL,
  calculated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_exam_readiness_ref (public_ref),
  KEY idx_exam_readiness_scope (school_id, academic_year_id, term_id, scope_type, subject_id, class_id),
  CONSTRAINT fk_exam_readiness_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_exam_readiness_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_exam_readiness_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_exam_readiness_student FOREIGN KEY (student_id) REFERENCES students(id),
  CONSTRAINT fk_exam_readiness_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_exam_readiness_subject FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

CREATE TABLE IF NOT EXISTS curriculum_pacing_snapshots (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NOT NULL,
  term_id BIGINT UNSIGNED NOT NULL,
  class_id BIGINT UNSIGNED NOT NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  planned_percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
  taught_percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
  assessed_percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
  mastered_percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
  teaching_days_variance INT NOT NULL DEFAULT 0,
  projected_completion_date DATE NULL,
  required_topics_per_week DECIMAL(8,2) NULL,
  topics_at_risk_json JSON NULL,
  explanation_json JSON NOT NULL,
  calculated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_curriculum_pacing_ref (public_ref),
  KEY idx_curriculum_pacing_scope (school_id, academic_year_id, term_id, class_id, subject_id, calculated_at),
  CONSTRAINT fk_curriculum_pacing_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_curriculum_pacing_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_curriculum_pacing_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_curriculum_pacing_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_curriculum_pacing_subject FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

CREATE TABLE IF NOT EXISTS academic_alerts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  alert_type VARCHAR(100) NOT NULL,
  severity ENUM('low','medium','high','urgent') NOT NULL,
  class_id BIGINT UNSIGNED NULL,
  student_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  title VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  evidence_json JSON NOT NULL,
  status ENUM('open','acknowledged','resolved','dismissed') NOT NULL DEFAULT 'open',
  assigned_user_id BIGINT UNSIGNED NULL,
  rule_key VARCHAR(120) NOT NULL,
  dedupe_window VARCHAR(80) NOT NULL,
  grace_expires_at TIMESTAMP NULL,
  escalated_at TIMESTAMP NULL,
  resolved_by BIGINT UNSIGNED NULL,
  resolved_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_academic_alert_ref (public_ref),
  UNIQUE KEY uq_academic_alert_dedupe (school_id, rule_key, dedupe_window, class_id, student_id, subject_id, topic_id),
  KEY idx_academic_alert_inbox (school_id, status, severity, assigned_user_id),
  CONSTRAINT fk_academic_alert_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_academic_alert_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_academic_alert_student FOREIGN KEY (student_id) REFERENCES students(id),
  CONSTRAINT fk_academic_alert_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_academic_alert_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_academic_alert_assignee FOREIGN KEY (assigned_user_id) REFERENCES users(id),
  CONSTRAINT fk_academic_alert_resolver FOREIGN KEY (resolved_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS academic_calculation_runs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  calculation_type ENUM('mastery','class_mastery','pacing','readiness','question_analytics','recommendations','reconciliation') NOT NULL,
  trigger_type VARCHAR(80) NOT NULL,
  trigger_entity_type VARCHAR(80) NULL,
  trigger_entity_id BIGINT UNSIGNED NULL,
  status ENUM('queued','running','completed','failed') NOT NULL DEFAULT 'queued',
  input_summary_json JSON NULL,
  output_summary_json JSON NULL,
  error_message TEXT NULL,
  started_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_academic_calculation_ref (public_ref),
  KEY idx_academic_calculation_queue (school_id, status, calculation_type, created_at),
  CONSTRAINT fk_academic_calculation_school FOREIGN KEY (school_id) REFERENCES schools(id)
);

CREATE TABLE IF NOT EXISTS teaching_resources (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(240) NOT NULL,
  description TEXT NULL,
  resource_type VARCHAR(80) NOT NULL,
  subject_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  stream_section VARCHAR(80) NULL,
  curriculum_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  subtopic_id BIGINT UNSIGNED NULL,
  learning_objective_id BIGINT UNSIGNED NULL,
  academic_year_id BIGINT UNSIGNED NULL,
  term_id BIGINT UNSIGNED NULL,
  language VARCHAR(60) NOT NULL DEFAULT 'English',
  estimated_duration_minutes INT NULL,
  source VARCHAR(180) NULL,
  copyright_status ENUM('school_owned','licensed','public_domain','permission_granted','unknown','review_required') NOT NULL DEFAULT 'unknown',
  confidentiality ENUM('normal','staff_only','restricted_assessment','marking_scheme','confidential') NOT NULL DEFAULT 'normal',
  approval_status ENUM('DRAFT','SUBMITTED','UNDER_REVIEW','CHANGES_REQUESTED','APPROVED','REJECTED','ARCHIVED','UNCLASSIFIED') NOT NULL DEFAULT 'DRAFT',
  current_version_id BIGINT UNSIGNED NULL,
  original_creator_id BIGINT UNSIGNED NULL,
  uploader_id BIGINT UNSIGNED NOT NULL,
  reviewing_librarian_id BIGINT UNSIGNED NULL,
  approving_user_id BIGINT UNSIGNED NULL,
  printable TINYINT(1) NOT NULL DEFAULT 1,
  download_allowed TINYINT(1) NOT NULL DEFAULT 1,
  archived_at TIMESTAMP NULL,
  last_used_at TIMESTAMP NULL,
  usage_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_teaching_resource_ref (public_ref),
  KEY idx_teaching_resource_search (school_id, approval_status, subject_id, class_id, topic_id, resource_type),
  KEY idx_teaching_resource_review (school_id, approval_status, updated_at),
  CONSTRAINT fk_teaching_resource_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_teaching_resource_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_teaching_resource_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_teaching_resource_curriculum FOREIGN KEY (curriculum_id) REFERENCES curricula(id),
  CONSTRAINT fk_teaching_resource_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_teaching_resource_subtopic FOREIGN KEY (subtopic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_teaching_resource_objective FOREIGN KEY (learning_objective_id) REFERENCES learning_objectives(id),
  CONSTRAINT fk_teaching_resource_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_teaching_resource_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_teaching_resource_creator FOREIGN KEY (original_creator_id) REFERENCES users(id),
  CONSTRAINT fk_teaching_resource_uploader FOREIGN KEY (uploader_id) REFERENCES users(id),
  CONSTRAINT fk_teaching_resource_librarian FOREIGN KEY (reviewing_librarian_id) REFERENCES users(id),
  CONSTRAINT fk_teaching_resource_approver FOREIGN KEY (approving_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS teaching_resource_versions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  version_number INT NOT NULL,
  change_description TEXT NULL,
  original_filename VARCHAR(255) NOT NULL,
  stored_filename VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  file_size BIGINT UNSIGNED NOT NULL,
  checksum CHAR(64) NOT NULL,
  page_count INT NULL,
  approval_status ENUM('DRAFT','SUBMITTED','UNDER_REVIEW','CHANGES_REQUESTED','APPROVED','REJECTED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
  created_by BIGINT UNSIGNED NOT NULL,
  approved_by BIGINT UNSIGNED NULL,
  approved_at TIMESTAMP NULL,
  supersedes_version_id BIGINT UNSIGNED NULL,
  is_current TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_teaching_resource_version_ref (public_ref),
  UNIQUE KEY uq_teaching_resource_version_number (school_id, resource_id, version_number),
  KEY idx_teaching_resource_version_current (school_id, resource_id, is_current),
  CONSTRAINT fk_teaching_resource_version_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_teaching_resource_version_resource FOREIGN KEY (resource_id) REFERENCES teaching_resources(id) ON DELETE CASCADE,
  CONSTRAINT fk_teaching_resource_version_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_teaching_resource_version_approver FOREIGN KEY (approved_by) REFERENCES users(id),
  CONSTRAINT fk_teaching_resource_version_supersedes FOREIGN KEY (supersedes_version_id) REFERENCES teaching_resource_versions(id)
);

ALTER TABLE teaching_resources
  ADD CONSTRAINT fk_teaching_resource_current_version FOREIGN KEY (current_version_id) REFERENCES teaching_resource_versions(id);

CREATE TABLE IF NOT EXISTS teaching_resource_reviews (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  version_id BIGINT UNSIGNED NOT NULL,
  review_type ENUM('file_quality','academic_content') NOT NULL,
  decision ENUM('pending','approved','changes_requested','rejected') NOT NULL DEFAULT 'pending',
  quality_flags_json JSON NULL,
  notes TEXT NULL,
  reviewer_id BIGINT UNSIGNED NOT NULL,
  reviewed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_teaching_resource_review_ref (public_ref),
  KEY idx_teaching_resource_review_queue (school_id, review_type, decision, created_at),
  CONSTRAINT fk_teaching_resource_review_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_teaching_resource_review_resource FOREIGN KEY (resource_id) REFERENCES teaching_resources(id) ON DELETE CASCADE,
  CONSTRAINT fk_teaching_resource_review_version FOREIGN KEY (version_id) REFERENCES teaching_resource_versions(id) ON DELETE CASCADE,
  CONSTRAINT fk_teaching_resource_review_user FOREIGN KEY (reviewer_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS teaching_resource_usage (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  version_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  class_id BIGINT UNSIGNED NULL,
  lesson_log_id BIGINT UNSIGNED NULL,
  usage_type ENUM('open','download','print_request','lesson_attachment','favourite','error_report','archive_restore') NOT NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_teaching_resource_usage_ref (public_ref),
  KEY idx_teaching_resource_usage_scope (school_id, resource_id, usage_type, created_at),
  CONSTRAINT fk_teaching_resource_usage_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_teaching_resource_usage_resource FOREIGN KEY (resource_id) REFERENCES teaching_resources(id),
  CONSTRAINT fk_teaching_resource_usage_version FOREIGN KEY (version_id) REFERENCES teaching_resource_versions(id),
  CONSTRAINT fk_teaching_resource_usage_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_teaching_resource_usage_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_teaching_resource_usage_lesson FOREIGN KEY (lesson_log_id) REFERENCES teacher_lesson_logs(id)
);

CREATE TABLE IF NOT EXISTS library_resources (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(240) NOT NULL,
  author VARCHAR(180) NULL,
  publisher VARCHAR(180) NULL,
  edition VARCHAR(80) NULL,
  publication_year YEAR NULL,
  isbn VARCHAR(40) NULL,
  category VARCHAR(100) NULL,
  subject_id BIGINT UNSIGNED NULL,
  class_level VARCHAR(80) NULL,
  curriculum_id BIGINT UNSIGNED NULL,
  topic_tags_json JSON NULL,
  shelf_location VARCHAR(100) NULL,
  acquisition_source VARCHAR(160) NULL,
  acquisition_date DATE NULL,
  replacement_cost DECIMAL(14,2) NULL,
  status ENUM('active','archived') NOT NULL DEFAULT 'active',
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_library_resource_ref (public_ref),
  KEY idx_library_resource_catalogue (school_id, status, category, subject_id, title),
  CONSTRAINT fk_library_resource_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_library_resource_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_library_resource_curriculum FOREIGN KEY (curriculum_id) REFERENCES curricula(id),
  CONSTRAINT fk_library_resource_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS library_resource_copies (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  barcode VARCHAR(100) NULL,
  condition_status ENUM('new','good','fair','damaged','lost','withdrawn') NOT NULL DEFAULT 'good',
  availability_status ENUM('available','borrowed','reserved','lost','repair','archived') NOT NULL DEFAULT 'available',
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_library_copy_ref (public_ref),
  UNIQUE KEY uq_library_copy_barcode (school_id, barcode),
  KEY idx_library_copy_availability (school_id, resource_id, availability_status),
  CONSTRAINT fk_library_copy_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_library_copy_resource FOREIGN KEY (resource_id) REFERENCES library_resources(id)
);

CREATE TABLE IF NOT EXISTS library_loans (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  resource_copy_id BIGINT UNSIGNED NOT NULL,
  borrower_type ENUM('student','teacher','staff') NOT NULL,
  borrower_student_id BIGINT UNSIGNED NULL,
  borrower_user_id BIGINT UNSIGNED NULL,
  issue_date DATE NOT NULL,
  expected_return_date DATE NOT NULL,
  actual_return_date DATE NULL,
  issued_by BIGINT UNSIGNED NOT NULL,
  received_by BIGINT UNSIGNED NULL,
  condition_on_issue VARCHAR(80) NULL,
  condition_on_return VARCHAR(80) NULL,
  status ENUM('borrowed','returned','overdue','lost','damaged') NOT NULL DEFAULT 'borrowed',
  penalty_note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_library_loan_ref (public_ref),
  KEY idx_library_loan_queue (school_id, status, expected_return_date),
  CONSTRAINT fk_library_loan_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_library_loan_copy FOREIGN KEY (resource_copy_id) REFERENCES library_resource_copies(id),
  CONSTRAINT fk_library_loan_student FOREIGN KEY (borrower_student_id) REFERENCES students(id),
  CONSTRAINT fk_library_loan_user FOREIGN KEY (borrower_user_id) REFERENCES users(id),
  CONSTRAINT fk_library_loan_issuer FOREIGN KEY (issued_by) REFERENCES users(id),
  CONSTRAINT fk_library_loan_receiver FOREIGN KEY (received_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS print_requests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  requested_by BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  version_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  copies INT NOT NULL,
  paper_size ENUM('A4','A3','LETTER','OTHER') NOT NULL DEFAULT 'A4',
  print_sides ENUM('single','double') NOT NULL DEFAULT 'single',
  colour_mode ENUM('black_white','colour') NOT NULL DEFAULT 'black_white',
  required_at TIMESTAMP NULL,
  confidentiality ENUM('normal','staff_only','restricted_assessment','marking_scheme','confidential') NOT NULL DEFAULT 'normal',
  assessment_security TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  status ENUM('DRAFT','SUBMITTED','APPROVED','QUEUED','PRINTING','READY','COLLECTED','CANCELLED','REJECTED') NOT NULL DEFAULT 'SUBMITTED',
  approved_by BIGINT UNSIGNED NULL,
  processed_by BIGINT UNSIGNED NULL,
  completed_at TIMESTAMP NULL,
  damaged_copy_count INT NOT NULL DEFAULT 0,
  cancelled_copy_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_print_request_ref (public_ref),
  KEY idx_print_request_queue (school_id, status, required_at, assessment_security),
  CONSTRAINT fk_print_request_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_print_request_requester FOREIGN KEY (requested_by) REFERENCES users(id),
  CONSTRAINT fk_print_request_resource FOREIGN KEY (resource_id) REFERENCES teaching_resources(id),
  CONSTRAINT fk_print_request_version FOREIGN KEY (version_id) REFERENCES teaching_resource_versions(id),
  CONSTRAINT fk_print_request_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_print_request_approver FOREIGN KEY (approved_by) REFERENCES users(id),
  CONSTRAINT fk_print_request_processor FOREIGN KEY (processed_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS print_request_events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  print_request_id BIGINT UNSIGNED NOT NULL,
  previous_status VARCHAR(40) NULL,
  next_status VARCHAR(40) NOT NULL,
  note TEXT NULL,
  actor_user_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_print_request_event_ref (public_ref),
  KEY idx_print_request_event_scope (school_id, print_request_id, created_at),
  CONSTRAINT fk_print_request_event_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_print_request_event_request FOREIGN KEY (print_request_id) REFERENCES print_requests(id) ON DELETE CASCADE,
  CONSTRAINT fk_print_request_event_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS library_computers (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  device_name VARCHAR(160) NOT NULL,
  library_location VARCHAR(160) NULL,
  device_type VARCHAR(80) NULL,
  operating_system VARCHAR(120) NULL,
  serial_number VARCHAR(120) NULL,
  working_status ENUM('active','unavailable','maintenance','retired') NOT NULL DEFAULT 'active',
  internet_available TINYINT(1) NOT NULL DEFAULT 0,
  printer_connected TINYINT(1) NOT NULL DEFAULT 0,
  assigned_purpose VARCHAR(120) NULL,
  last_maintenance_date DATE NULL,
  issue_notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_library_computer_ref (public_ref),
  UNIQUE KEY uq_library_computer_serial (school_id, serial_number),
  KEY idx_library_computer_status (school_id, working_status),
  CONSTRAINT fk_library_computer_school FOREIGN KEY (school_id) REFERENCES schools(id)
);

CREATE TABLE IF NOT EXISTS institutional_archive_records (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NULL,
  term_id BIGINT UNSIGNED NULL,
  record_type VARCHAR(100) NOT NULL,
  source_entity_type VARCHAR(80) NOT NULL,
  source_entity_id BIGINT UNSIGNED NULL,
  title VARCHAR(240) NOT NULL,
  metadata_json JSON NOT NULL,
  confidentiality ENUM('normal','anonymous_statistics','named_results','confidential_staff','financial') NOT NULL DEFAULT 'normal',
  archive_status ENUM('PREPARATION','READY','ARCHIVED','MISSING','METADATA_WARNING','RESTORED') NOT NULL DEFAULT 'PREPARATION',
  immutable_at TIMESTAMP NULL,
  archived_by BIGINT UNSIGNED NULL,
  archived_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_archive_record_ref (public_ref),
  UNIQUE KEY uq_archive_record_source (school_id, academic_year_id, term_id, source_entity_type, source_entity_id),
  KEY idx_archive_browser (school_id, academic_year_id, term_id, record_type, archive_status),
  CONSTRAINT fk_archive_record_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_archive_record_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_archive_record_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_archive_record_archiver FOREIGN KEY (archived_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS archive_access_logs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  archive_record_id BIGINT UNSIGNED NOT NULL,
  actor_user_id BIGINT UNSIGNED NOT NULL,
  access_level ENUM('metadata','file','anonymous_statistics','named_results','restore') NOT NULL,
  reason TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_archive_access_ref (public_ref),
  KEY idx_archive_access_scope (school_id, archive_record_id, created_at),
  CONSTRAINT fk_archive_access_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_archive_access_record FOREIGN KEY (archive_record_id) REFERENCES institutional_archive_records(id),
  CONSTRAINT fk_archive_access_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS classroom_sessions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  lesson_log_id BIGINT UNSIGNED NOT NULL,
  teacher_id BIGINT UNSIGNED NOT NULL,
  class_id BIGINT UNSIGNED NOT NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  timetable_entry_id BIGINT UNSIGNED NULL,
  status ENUM('active','draft','completed','cancelled') NOT NULL DEFAULT 'active',
  sync_token CHAR(36) NOT NULL,
  understanding_estimate ENUM('STRONG','SATISFACTORY','MIXED','WEAK','NOT_ASSESSED') NOT NULL DEFAULT 'NOT_ASSESSED',
  understanding_confidence ENUM('low','medium','high') NULL,
  observation_note TEXT NULL,
  formal_check_used TINYINT(1) NOT NULL DEFAULT 0,
  formative_activity_type ENUM('oral_questions','written_class_exercise','exercise_book','printed_worksheet','exit_ticket','homework','board_work','paper_quiz','none') NOT NULL DEFAULT 'none',
  formative_summary_json JSON NULL,
  offline_client_id VARCHAR(120) NULL,
  last_synced_at TIMESTAMP NULL,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_classroom_session_ref (public_ref),
  UNIQUE KEY uq_classroom_lesson_log (school_id, lesson_log_id),
  UNIQUE KEY uq_classroom_offline_submission (school_id, teacher_id, offline_client_id),
  KEY idx_classroom_teacher_active (school_id, teacher_id, status, started_at),
  CONSTRAINT fk_classroom_session_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_classroom_session_lesson FOREIGN KEY (lesson_log_id) REFERENCES teacher_lesson_logs(id),
  CONSTRAINT fk_classroom_session_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
  CONSTRAINT fk_classroom_session_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_classroom_session_subject FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

CREATE TABLE IF NOT EXISTS classroom_session_resources (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  classroom_session_id BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  resource_version_id BIGINT UNSIGNED NULL,
  usage_note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_classroom_resource_ref (public_ref),
  UNIQUE KEY uq_classroom_resource (school_id, classroom_session_id, resource_id),
  CONSTRAINT fk_classroom_resource_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_classroom_resource_session FOREIGN KEY (classroom_session_id) REFERENCES classroom_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_classroom_resource_resource FOREIGN KEY (resource_id) REFERENCES teaching_resources(id),
  CONSTRAINT fk_classroom_resource_version FOREIGN KEY (resource_version_id) REFERENCES teaching_resource_versions(id)
);

CREATE TABLE IF NOT EXISTS classroom_observations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  classroom_session_id BIGINT UNSIGNED NOT NULL,
  observation_code VARCHAR(80) NOT NULL,
  note TEXT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_classroom_observation_ref (public_ref),
  KEY idx_classroom_observation_session (school_id, classroom_session_id, created_at),
  CONSTRAINT fk_classroom_observation_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_classroom_observation_session FOREIGN KEY (classroom_session_id) REFERENCES classroom_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_classroom_observation_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS classroom_follow_up_actions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  classroom_session_id BIGINT UNSIGNED NOT NULL,
  recommendation_id BIGINT UNSIGNED NULL,
  action_type VARCHAR(80) NOT NULL,
  description TEXT NOT NULL,
  due_date DATE NULL,
  status ENUM('open','in_progress','completed','dismissed') NOT NULL DEFAULT 'open',
  created_by BIGINT UNSIGNED NOT NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_classroom_follow_up_ref (public_ref),
  KEY idx_classroom_follow_up_scope (school_id, status, due_date),
  CONSTRAINT fk_classroom_follow_up_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_classroom_follow_up_session FOREIGN KEY (classroom_session_id) REFERENCES classroom_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_classroom_follow_up_recommendation FOREIGN KEY (recommendation_id) REFERENCES academic_recommendations(id),
  CONSTRAINT fk_classroom_follow_up_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

-- Preserve existing drill mastery as low-confidence topic evidence without
-- pretending it contains objective-level detail.
INSERT INTO academic_mastery_records (
  public_ref, school_id, student_id, subject_id, topic_id, mastery_level,
  mastery_score, confidence_score, mastery_status, trend, evidence_count,
  calculation_explanation_json, last_evidence_at, last_recalculated_at
)
SELECT UUID(), stm.school_id, stm.student_id, stm.subject_id, stm.topic_id, 'topic',
  stm.mastery_score,
  CASE stm.confidence_label WHEN 'high' THEN 80 WHEN 'medium' THEN 55 ELSE 30 END,
  CASE
    WHEN stm.attempts = 0 THEN 'NOT_ASSESSED'
    WHEN stm.attempts < 3 THEN 'INSUFFICIENT_EVIDENCE'
    WHEN stm.intervention_needed = 1 THEN 'REQUIRES_INTERVENTION'
    WHEN stm.mastery_score >= 85 THEN 'ADVANCED'
    WHEN stm.mastery_score >= 70 THEN 'MASTERED'
    WHEN stm.mastery_score >= 50 THEN 'PARTIALLY_MASTERED'
    WHEN stm.mastery_score >= 35 THEN 'DEVELOPING'
    ELSE 'EMERGING'
  END,
  UPPER(stm.trend), stm.attempts,
  JSON_OBJECT('source','student_topic_mastery','migration','046','granularity','topic'),
  stm.last_practised_at, CURRENT_TIMESTAMP
FROM student_topic_mastery stm
ON DUPLICATE KEY UPDATE
  mastery_score = VALUES(mastery_score),
  confidence_score = VALUES(confidence_score),
  evidence_count = VALUES(evidence_count),
  last_evidence_at = VALUES(last_evidence_at),
  last_recalculated_at = CURRENT_TIMESTAMP;

INSERT INTO academic_engine_config (school_id)
SELECT id FROM schools
ON DUPLICATE KEY UPDATE school_id = VALUES(school_id);

