USE smartlink_schools;

ALTER TABLE teaching_resources
  ADD COLUMN IF NOT EXISTS tags_json JSON NULL,
  ADD COLUMN IF NOT EXISTS examination_board VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS assessment_type VARCHAR(80) NULL,
  ADD COLUMN IF NOT EXISTS licence_notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS archive_metadata_status ENUM('complete','incomplete','duplicate_review','copyright_review') NOT NULL DEFAULT 'incomplete';

CREATE TABLE IF NOT EXISTS question_attempts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  student_id BIGINT UNSIGNED NOT NULL,
  question_id BIGINT UNSIGNED NOT NULL,
  assessment_id BIGINT UNSIGNED NULL,
  drill_session_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  topic_id BIGINT UNSIGNED NULL,
  subtopic_id BIGINT UNSIGNED NULL,
  learning_objective_id BIGINT UNSIGNED NULL,
  response_text TEXT NULL,
  response_status ENUM('correct','partially_correct','incorrect','omitted','unmarked') NOT NULL DEFAULT 'unmarked',
  marks_awarded DECIMAL(8,2) NULL,
  marks_available DECIMAL(8,2) NOT NULL,
  completion_seconds INT NULL,
  attempt_context ENUM('independent','guided','homework','classwork','examination','daily_drill','reassessment') NOT NULL DEFAULT 'independent',
  misconception_code VARCHAR(120) NULL,
  attempted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_question_attempt_ref (public_ref),
  KEY idx_question_attempt_question (school_id, question_id, attempted_at),
  KEY idx_question_attempt_student (school_id, student_id, subject_id, attempted_at),
  KEY idx_question_attempt_objective (school_id, learning_objective_id, attempted_at),
  CONSTRAINT fk_question_attempt_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_question_attempt_student FOREIGN KEY (student_id) REFERENCES students(id),
  CONSTRAINT fk_question_attempt_question FOREIGN KEY (question_id) REFERENCES question_bank(id),
  CONSTRAINT fk_question_attempt_assessment FOREIGN KEY (assessment_id) REFERENCES assessments(id),
  CONSTRAINT fk_question_attempt_drill FOREIGN KEY (drill_session_id) REFERENCES drill_sessions(id),
  CONSTRAINT fk_question_attempt_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_question_attempt_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_question_attempt_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_question_attempt_subtopic FOREIGN KEY (subtopic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_question_attempt_objective FOREIGN KEY (learning_objective_id) REFERENCES learning_objectives(id)
);

CREATE TABLE IF NOT EXISTS class_mastery_snapshots (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  academic_year_id BIGINT UNSIGNED NULL,
  term_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NOT NULL,
  stream_section VARCHAR(80) NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  topic_id BIGINT UNSIGNED NULL,
  subtopic_id BIGINT UNSIGNED NULL,
  learning_objective_id BIGINT UNSIGNED NULL,
  average_mastery DECIMAL(5,2) NULL,
  median_mastery DECIMAL(5,2) NULL,
  confidence_score DECIMAL(5,2) NOT NULL DEFAULT 0,
  students_assessed INT NOT NULL DEFAULT 0,
  students_below_threshold INT NOT NULL DEFAULT 0,
  students_with_insufficient_evidence INT NOT NULL DEFAULT 0,
  distribution_json JSON NOT NULL,
  trend ENUM('IMPROVING','STEADY','DECLINING','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  calculated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_class_mastery_ref (public_ref),
  KEY idx_class_mastery_scope (school_id, academic_year_id, term_id, class_id, subject_id, topic_id, calculated_at),
  CONSTRAINT fk_class_mastery_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_class_mastery_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_class_mastery_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_class_mastery_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_class_mastery_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_class_mastery_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_class_mastery_subtopic FOREIGN KEY (subtopic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_class_mastery_objective FOREIGN KEY (learning_objective_id) REFERENCES learning_objectives(id)
);

CREATE TABLE IF NOT EXISTS assessment_blueprints (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  assessment_id BIGINT UNSIGNED NULL,
  academic_year_id BIGINT UNSIGNED NULL,
  term_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NOT NULL,
  stream_section VARCHAR(80) NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(220) NOT NULL,
  total_marks DECIMAL(8,2) NOT NULL,
  duration_minutes INT NOT NULL,
  topics_json JSON NOT NULL,
  difficulty_distribution_json JSON NOT NULL,
  cognitive_distribution_json JSON NOT NULL,
  question_types_json JSON NOT NULL,
  section_configuration_json JSON NULL,
  taught_topic_restriction TINYINT(1) NOT NULL DEFAULT 1,
  mastery_focused TINYINT(1) NOT NULL DEFAULT 0,
  examination_board_style VARCHAR(120) NULL,
  validation_warnings_json JSON NULL,
  status ENUM('draft','validated','used','archived') NOT NULL DEFAULT 'draft',
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_assessment_blueprint_ref (public_ref),
  KEY idx_assessment_blueprint_scope (school_id, class_id, subject_id, status, created_at),
  CONSTRAINT fk_assessment_blueprint_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_assessment_blueprint_assessment FOREIGN KEY (assessment_id) REFERENCES assessments(id),
  CONSTRAINT fk_assessment_blueprint_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id),
  CONSTRAINT fk_assessment_blueprint_term FOREIGN KEY (term_id) REFERENCES terms(id),
  CONSTRAINT fk_assessment_blueprint_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_assessment_blueprint_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_assessment_blueprint_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS remediation_packs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  recommendation_id BIGINT UNSIGNED NULL,
  intervention_id BIGINT UNSIGNED NULL,
  student_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  topic_id BIGINT UNSIGNED NULL,
  title VARCHAR(220) NOT NULL,
  prerequisite_review_json JSON NULL,
  explanation_text TEXT NULL,
  worked_examples_json JSON NULL,
  guided_practice_json JSON NULL,
  independent_practice_json JSON NULL,
  exit_ticket_json JSON NULL,
  marking_guide_json JSON NULL,
  teacher_strategy TEXT NULL,
  parent_summary TEXT NULL,
  generation_source ENUM('teacher','ai_draft','template') NOT NULL DEFAULT 'teacher',
  ai_metadata_json JSON NULL,
  approval_status ENUM('draft','pending_teacher_review','approved','rejected','archived') NOT NULL DEFAULT 'draft',
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at TIMESTAMP NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_remediation_pack_ref (public_ref),
  KEY idx_remediation_pack_scope (school_id, subject_id, class_id, student_id, approval_status),
  CONSTRAINT fk_remediation_pack_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_remediation_pack_recommendation FOREIGN KEY (recommendation_id) REFERENCES academic_recommendations(id),
  CONSTRAINT fk_remediation_pack_intervention FOREIGN KEY (intervention_id) REFERENCES academic_interventions(id),
  CONSTRAINT fk_remediation_pack_student FOREIGN KEY (student_id) REFERENCES students(id),
  CONSTRAINT fk_remediation_pack_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_remediation_pack_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_remediation_pack_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_remediation_pack_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id),
  CONSTRAINT fk_remediation_pack_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS teaching_resource_requests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  requested_by BIGINT UNSIGNED NOT NULL,
  assigned_librarian_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  request_text TEXT NOT NULL,
  required_at TIMESTAMP NULL,
  priority ENUM('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
  status ENUM('submitted','accepted','locating','fulfilled','not_available','cancelled') NOT NULL DEFAULT 'submitted',
  response_note TEXT NULL,
  fulfilled_resource_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_resource_request_ref (public_ref),
  KEY idx_resource_request_queue (school_id, status, priority, required_at),
  CONSTRAINT fk_resource_request_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_resource_request_requester FOREIGN KEY (requested_by) REFERENCES users(id),
  CONSTRAINT fk_resource_request_librarian FOREIGN KEY (assigned_librarian_id) REFERENCES users(id),
  CONSTRAINT fk_resource_request_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
  CONSTRAINT fk_resource_request_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_resource_request_topic FOREIGN KEY (topic_id) REFERENCES syllabus_topics(id),
  CONSTRAINT fk_resource_request_resource FOREIGN KEY (fulfilled_resource_id) REFERENCES teaching_resources(id)
);

CREATE TABLE IF NOT EXISTS archive_correction_requests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_ref CHAR(36) NOT NULL,
  school_id BIGINT UNSIGNED NOT NULL,
  archive_record_id BIGINT UNSIGNED NOT NULL,
  request_type ENUM('metadata_correction','duplicate_review','missing_file','official_record_correction','restore_resource') NOT NULL,
  reason TEXT NOT NULL,
  proposed_change_json JSON NULL,
  status ENUM('submitted','under_review','approved','rejected','completed') NOT NULL DEFAULT 'submitted',
  requested_by BIGINT UNSIGNED NOT NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at TIMESTAMP NULL,
  decision_note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_archive_correction_ref (public_ref),
  KEY idx_archive_correction_queue (school_id, status, request_type, created_at),
  CONSTRAINT fk_archive_correction_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_archive_correction_record FOREIGN KEY (archive_record_id) REFERENCES institutional_archive_records(id),
  CONSTRAINT fk_archive_correction_requester FOREIGN KEY (requested_by) REFERENCES users(id),
  CONSTRAINT fk_archive_correction_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

