# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
android.useAndroidX=true
android.enableJetifier=true

# Mapbox Secret Token for downloading the SDK (starts with sk.)
# Get it from https://account.mapbox.com/ (Tokens -> Create a token -> Scopes: DOWNLOADS:READ)
MAPBOX_DOWNLOADS_TOKEN=YOUR_SECRET_MAPBOX_TOKEN_HERE
