import fs from "fs/promises"
import path from "path"
import { createHash, randomUUID } from "crypto"
import { pool } from "../config/db.js"
import { HttpError } from "../utils/http.js"

const leadershipRoles=new Set(["school_owner","headteacher","admin","super_admin"])
const categories=new Set(["exam","test","quiz","homework","worksheet","daily_drill","general"])
const sources=new Set(["school_created","imported_pdf","duplicated"])
const json=(value,fallback={})=>{if(value===null||value===undefined)return fallback;if(typeof value==="object")return value;try{return JSON.parse(value)}catch{return fallback}}
const clean=(value,max=500)=>String(value??"").trim().slice(0,max)
const bool=(value)=>value===true||value===1||value==="1"||value==="true"

function templatePayload(row){return {...row,id:undefined,school_id:undefined,source_import_job_id:undefined,source_assessment_id:undefined,created_by:undefined,approved_by:undefined,layout_json:json(row.layout_json,{}),style_json:json(row.style_json,{}),signature_json:json(row.signature_json,{}),is_default:Boolean(row.is_default),is_active:Boolean(row.is_active),is_global:Boolean(row.is_global)}}
function signatureForCover(cover={}){const fields=(cover.detectedFields||[]).map((field)=>clean(field.label||field.type,80).toLowerCase()).filter(Boolean).sort();const layout=cover.layout||{};const signature={fields,candidate_fields:(layout.candidateFields||[]).map((v)=>clean(v,80).toLowerCase()).sort(),title_alignment:clean(layout.titleAlignment,40).toLowerCase(),metadata_columns:Number(layout.metadataColumns)||0,header_style:clean(layout.headerStyle,80).toLowerCase(),footer_style:clean(layout.footerStyle,80).toLowerCase()};return {signature,hash:createHash("sha256").update(JSON.stringify(signature)).digest("hex")}}
function jaccard(left=[],right=[]){const a=new Set(left),b=new Set(right),union=new Set([...a,...b]);if(!union.size)return 0;let overlap=0;a.forEach((value)=>{if(b.has(value))overlap+=1});return overlap/union.size}
function matchScore(left={},right={}){let score=.15;score+=jaccard(left.fields,right.fields)*.4;score+=jaccard(left.candidate_fields,right.candidate_fields)*.2;if(left.title_alignment&&left.title_alignment===right.title_alignment)score+=.1;if(left.metadata_columns&&left.metadata_columns===right.metadata_columns)score+=.1;if(left.header_style&&left.header_style===right.header_style)score+=.025;if(left.footer_style&&left.footer_style===right.footer_style)score+=.025;return Math.max(0,Math.min(.99,score))}
async function settingsFor(schoolId){await pool.query("INSERT IGNORE INTO assessment_template_settings (school_id) VALUES (?)",[schoolId]);const [[settings]]=await pool.query("SELECT * FROM assessment_template_settings WHERE school_id=?",[schoolId]);return settings}
async function assertCanCreate(schoolId,user){if(leadershipRoles.has(String(user.role)))return;const settings=await settingsFor(schoolId);if(String(user.role)!=="teacher"||!Number(settings.allow_teachers_to_create_templates))throw new HttpError(403,"You do not have permission to create assessment templates")}
async function byRef(connection,schoolId,ref,{approvedOnly=false}={}){const [[row]]=await connection.query(`SELECT * FROM assessment_cover_templates WHERE public_ref=? AND is_active=1 AND (school_id=? OR (school_id IS NULL AND is_global=1))${approvedOnly?" AND review_status='approved'":""} LIMIT 1`,[ref,schoolId]);if(!row)throw new HttpError(404,"Assessment cover template was not found");return row}
async function importByRef(connection,schoolId,ref){const [[job]]=await connection.query("SELECT * FROM assessment_import_jobs WHERE school_id=? AND public_ref=? LIMIT 1",[schoolId,ref]);if(!job)throw new HttpError(404,"Assessment import was not found");return job}

export async function listAssessmentTemplates(schoolId,filters={}){const clauses=["(school_id=? OR (school_id IS NULL AND is_global=1))"],params=[schoolId];if(filters.source_type){clauses.push("source_type=?");params.push(filters.source_type)}if(filters.category){clauses.push("template_category=?");params.push(filters.category)}if(filters.include_archived!=="true")clauses.push("review_status<>'archived' AND is_active=1");if(filters.q){clauses.push("(template_name LIKE ? OR template_description LIKE ?)");params.push(`%${filters.q}%`,`%${filters.q}%`)}const [rows]=await pool.query(`SELECT * FROM assessment_cover_templates WHERE ${clauses.join(" AND ")} ORDER BY is_default DESC,is_global ASC,usage_count DESC,updated_at DESC`,params);return {templates:rows.map(templatePayload),...(await getAssessmentTemplateSettings(schoolId))}}
export async function getAssessmentTemplate(schoolId,ref){return {template:templatePayload(await byRef(pool,schoolId,ref))}}

export async function createAssessmentTemplate(schoolId,user,body={}){await assertCanCreate(schoolId,user);const name=clean(body.template_name||body.name,180);if(!name)throw new HttpError(400,"Template name is required");const source=sources.has(body.source_type)?body.source_type:"school_created";const category=categories.has(body.template_category)?body.template_category:"general";const layout=body.layout_json||body.layout;if(!layout||typeof layout!=="object")throw new HttpError(400,"Template layout is required");const settings=await settingsFor(schoolId);const approved=leadershipRoles.has(String(user.role))&&!Number(settings.require_template_approval);const ref=randomUUID();await pool.query(`INSERT INTO assessment_cover_templates (public_ref,school_id,template_name,template_description,source_type,source_assessment_id,subject_id,class_id,assessment_type,template_category,layout_json,style_json,confidence,is_global,review_status,created_by,approved_by,approved_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?)`,[ref,schoolId,name,clean(body.template_description,500)||null,source,Number(body.source_assessment_id)||null,Number(body.subject_id)||null,Number(body.class_id)||null,clean(body.assessment_type,40)||null,category,JSON.stringify(layout),JSON.stringify(body.style_json||body.style||{}),Number(body.confidence)||null,approved?"approved":"pending",user.id,approved?user.id:null,approved?new Date():null]);return getAssessmentTemplate(schoolId,ref)}
export async function updateAssessmentTemplate(schoolId,user,ref,body={}){const template=await byRef(pool,schoolId,ref);if(!template.school_id)throw new HttpError(409,"Duplicate a built-in template before editing it");if(!leadershipRoles.has(String(user.role))&&Number(template.created_by)!==Number(user.id))throw new HttpError(403,"You can only edit templates you created");const category=body.template_category===undefined?template.template_category:(categories.has(body.template_category)?body.template_category:"general");await pool.query(`UPDATE assessment_cover_templates SET template_name=COALESCE(?,template_name),template_description=?,template_category=?,layout_json=COALESCE(?,layout_json),style_json=COALESCE(?,style_json),subject_id=?,class_id=?,assessment_type=? WHERE id=? AND school_id=?`,[clean(body.template_name||body.name,180)||null,body.template_description===undefined?template.template_description:clean(body.template_description,500)||null,category,body.layout_json||body.layout?JSON.stringify(body.layout_json||body.layout):null,body.style_json||body.style?JSON.stringify(body.style_json||body.style):null,body.subject_id===undefined?template.subject_id:Number(body.subject_id)||null,body.class_id===undefined?template.class_id:Number(body.class_id)||null,body.assessment_type===undefined?template.assessment_type:clean(body.assessment_type,40)||null,template.id,schoolId]);return getAssessmentTemplate(schoolId,ref)}
export async function archiveAssessmentTemplate(schoolId,user,ref){if(!leadershipRoles.has(String(user.role)))throw new HttpError(403,"Only school leadership can archive templates");const template=await byRef(pool,schoolId,ref);if(!template.school_id)throw new HttpError(409,"Built-in templates cannot be archived");await pool.query("UPDATE assessment_cover_templates SET review_status='archived',is_active=0,is_default=0 WHERE id=? AND school_id=?",[template.id,schoolId]);return {ok:true}}
export async function approveAssessmentTemplate(schoolId,user,ref){if(!leadershipRoles.has(String(user.role)))throw new HttpError(403,"Only school leadership can approve extracted templates");const template=await byRef(pool,schoolId,ref);if(!template.school_id)throw new HttpError(409,"Built-in templates are already approved");await pool.query("UPDATE assessment_cover_templates SET review_status='approved',approved_by=?,approved_at=CURRENT_TIMESTAMP WHERE id=? AND school_id=?",[user.id,template.id,schoolId]);return getAssessmentTemplate(schoolId,ref)}
export async function duplicateAssessmentTemplate(schoolId,user,ref,body={}){await assertCanCreate(schoolId,user);const source=await byRef(pool,schoolId,ref);return createAssessmentTemplate(schoolId,user,{template_name:clean(body.template_name||`${source.template_name} Copy`,180),template_description:source.template_description,source_type:"duplicated",template_category:source.template_category,layout_json:json(source.layout_json,{}),style_json:json(source.style_json,{})})}

export async function extractCoverTemplateFromImport(schoolId,user,importRef){await assertCanCreate(schoolId,user);const job=await importByRef(pool,schoolId,importRef);const cover=json(job.cover_json,{});const [[page]]=await pool.query("SELECT preview_image_path FROM assessment_import_pages WHERE school_id=? AND import_job_id=? AND document_type='student_paper' AND page_number=1 LIMIT 1",[schoolId,job.id]);if(!page?.preview_image_path)throw new HttpError(409,"The original cover preview is unavailable. Reprocess this import first.");const {signature,hash}=signatureForCover(cover);const [[repeated]]=await pool.query("SELECT COUNT(*) total FROM assessment_cover_templates WHERE school_id=? AND signature_hash=? AND source_type='imported_pdf'",[schoolId,hash]);const appearanceCount=Number(repeated?.total||0)+1;const [[existing]]=await pool.query("SELECT * FROM assessment_cover_templates WHERE school_id=? AND source_import_job_id=? LIMIT 1",[schoolId,job.id]);const layout={version:1,paper_size:cover.layout?.pageSize||"A4",cover_style:"original_imported",original_cover_path:page.preview_image_path,source_import_ref:job.public_ref,sections:["original_page_reference","editable_extracted_fields"],extracted_cover:cover};if(existing){await pool.query("UPDATE assessment_cover_templates SET layout_json=?,preview_image_path=?,confidence=?,signature_hash=?,signature_json=?,appearance_count=GREATEST(appearance_count,?),updated_at=CURRENT_TIMESTAMP WHERE id=?",[JSON.stringify(layout),page.preview_image_path,Number(cover.confidence)||.5,hash,JSON.stringify(signature),Math.max(1,appearanceCount-1),existing.id]);return getAssessmentTemplate(schoolId,existing.public_ref)}const ref=randomUUID();await pool.query(`INSERT INTO assessment_cover_templates (public_ref,school_id,template_name,template_description,source_type,source_import_job_id,subject_id,class_id,assessment_type,template_category,layout_json,preview_image_path,thumbnail_image_path,extracted_from_page_number,confidence,signature_hash,signature_json,appearance_count,review_status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?,?,?, 'pending',?)`,[ref,schoolId,`${job.title} – Extracted Cover`,"Original first-page cover extracted from this school's uploaded PDF. Review before reuse.","imported_pdf",job.id,job.subject_id,job.class_id,job.assessment_type,job.assessment_type==="exam"?"exam":"general",JSON.stringify(layout),page.preview_image_path,page.preview_image_path,Number(cover.confidence)||.5,hash,JSON.stringify(signature),appearanceCount,user.id]);await pool.query("UPDATE assessment_cover_templates SET appearance_count=? WHERE school_id=? AND signature_hash=? AND source_type='imported_pdf'",[appearanceCount,schoolId,hash]);return getAssessmentTemplate(schoolId,ref)}

export async function detectRepeatedCoverTemplates(schoolId){const [rows]=await pool.query("SELECT signature_hash,MAX(appearance_count) appearance_count,COUNT(*) imports,MAX(updated_at) last_seen_at FROM assessment_cover_templates WHERE school_id=? AND source_type='imported_pdf' AND signature_hash IS NOT NULL GROUP BY signature_hash HAVING COUNT(*)>1 OR MAX(appearance_count)>1 ORDER BY appearance_count DESC,last_seen_at DESC",[schoolId]);return {repeated_covers:rows.map((row)=>({signature:row.signature_hash,appearance_count:Number(row.appearance_count||row.imports),last_seen_at:row.last_seen_at,message:`This cover design has appeared in ${Number(row.appearance_count||row.imports)} imports.`}))}}

export async function matchCoverTemplateFromImport(schoolId,user,importRef){const job=await importByRef(pool,schoolId,importRef);let extracted=(await pool.query("SELECT * FROM assessment_cover_templates WHERE school_id=? AND source_import_job_id=? LIMIT 1",[schoolId,job.id]))[0][0];if(!extracted)extracted=(await extractCoverTemplateFromImport(schoolId,user,importRef)).template;const signature=json(extracted.signature_json,{});const [candidates]=await pool.query("SELECT * FROM assessment_cover_templates WHERE (school_id=? OR (school_id IS NULL AND is_global=1)) AND review_status='approved' AND is_active=1 AND (source_import_job_id IS NULL OR source_import_job_id<>?)",[schoolId,job.id]);const matches=candidates.map((candidate)=>({candidate,score:matchScore(signature,json(candidate.signature_json,{}))})).sort((a,b)=>b.score-a.score);await pool.query("DELETE FROM assessment_template_matches WHERE school_id=? AND import_job_id=?",[schoolId,job.id]);for(const match of matches.slice(0,5)){await pool.query("INSERT INTO assessment_template_matches (school_id,import_job_id,extracted_template_id,matched_template_id,match_score,match_reasons_json) VALUES (?,?,?,?,?,?)",[schoolId,job.id,extracted.id||null,match.candidate.id,match.score,JSON.stringify({field_similarity:true,threshold:.85})])}return {extracted_template:templatePayload(extracted),matches:matches.slice(0,5).map((match)=>({template:templatePayload(match.candidate),match_score:match.score,confident:match.score>=.85})),recommendation:matches[0]?.score>=.85?"use_existing":"save_as_new"}}

async function copyTemplatePreview(connection,{schoolId,userId,assessmentId,template}){const source=template.preview_image_path||json(template.layout_json,{}).original_cover_path;if(!source)return null;const sourcePath=path.resolve(process.cwd(),source);const uploadsRoot=path.resolve(process.cwd(),"uploads");if(!sourcePath.startsWith(`${uploadsRoot}${path.sep}`))return null;const folder=path.resolve(process.cwd(),"uploads","assessment-media",String(schoolId),String(assessmentId));await fs.mkdir(folder,{recursive:true});const target=path.join(folder,`cover-template-${template.public_ref}.png`);await fs.copyFile(sourcePath,target);const stat=await fs.stat(target);const [media]=await connection.query("INSERT INTO assessment_media (school_id,assessment_id,uploaded_by,file_name,file_type,file_size,storage_path,alt_text) VALUES (?,?,?,?,?,?,?,?)",[schoolId,assessmentId,userId,path.basename(target),"image/png",stat.size,path.relative(process.cwd(),target),`Cover template: ${template.template_name}`]);return media.insertId}
export async function applyAssessmentTemplate(schoolId,user,ref,assessmentId){const connection=await pool.getConnection();try{await connection.beginTransaction();const template=await byRef(connection,schoolId,ref);const [[assessment]]=await connection.query("SELECT * FROM assessments WHERE school_id=? AND id=? FOR UPDATE",[schoolId,Number(assessmentId)]);if(!assessment)throw new HttpError(404,"Assessment was not found");if(["locked","archived"].includes(assessment.status))throw new HttpError(409,"This assessment cover is locked");if(String(user.role)==="teacher"&&Number(assessment.teacher_id)!==Number(user.id))throw new HttpError(403,"You cannot edit this assessment");const layout=json(template.layout_json,{});const mediaId=layout.cover_style==="original_imported"?await copyTemplatePreview(connection,{schoolId,userId:user.id,assessmentId:assessment.id,template}):null;const paperLayout={...layout,original_cover_media_id:mediaId||layout.original_cover_media_id||null,cover_template_ref:template.public_ref};const [[layoutBlock]]=await connection.query("SELECT id FROM assessment_blocks WHERE school_id=? AND assessment_id=? AND JSON_UNQUOTE(JSON_EXTRACT(metadata_json,'$.system_block'))='paper_layout' LIMIT 1",[schoolId,assessment.id]);if(layoutBlock)await connection.query("UPDATE assessment_blocks SET content_json=? WHERE id=? AND school_id=?",[JSON.stringify({paper_layout:paperLayout}),layoutBlock.id,schoolId]);else await connection.query("INSERT INTO assessment_blocks (school_id,assessment_id,block_type,content_json,style_json,metadata_json,sort_order,is_printable) VALUES (?,?,'cover_field',?,?,?,0,1)",[schoolId,assessment.id,JSON.stringify({paper_layout:paperLayout}),JSON.stringify({}),JSON.stringify({system_block:"paper_layout"})]);await connection.query("UPDATE assessments SET cover_template_id=? WHERE id=? AND school_id=?",[template.id,assessment.id,schoolId]);await connection.query("UPDATE assessment_cover_templates SET usage_count=usage_count+1,last_used_at=CURRENT_TIMESTAMP WHERE id=?",[template.id]);await connection.query("INSERT INTO assessment_template_usage (school_id,template_id,assessment_id,used_by,context_json) VALUES (?,?,?,?,?)",[schoolId,template.id,assessment.id,user.id,JSON.stringify({source:"assessment_builder"})]);await connection.commit();return {ok:true,assessment_id:assessment.id,template:templatePayload(template)}}catch(error){await connection.rollback();throw error}finally{connection.release()}}
export async function setDefaultAssessmentTemplate(schoolId,user,ref,category){if(!leadershipRoles.has(String(user.role)))throw new HttpError(403,"Only school leadership can set default templates");const template=await byRef(pool,schoolId,ref,{approvedOnly:true});const key={exam:"default_exam_template_id",test:"default_test_template_id",quiz:"default_quiz_template_id",worksheet:"default_worksheet_template_id",daily_drill:"default_daily_drill_template_id"}[category||template.template_category];if(!key)throw new HttpError(400,"Choose exam, test, quiz, worksheet, or daily drill as the default category");await settingsFor(schoolId);await pool.query(`UPDATE assessment_template_settings SET ${key}=? WHERE school_id=?`,[template.id,schoolId]);await pool.query("UPDATE assessment_cover_templates SET is_default=CASE WHEN id=? THEN 1 ELSE 0 END WHERE school_id=? AND template_category=?",[template.id,schoolId,category||template.template_category]);return {ok:true,category:category||template.template_category,template:templatePayload(template)}}
export async function getAssessmentTemplateSettings(schoolId){await settingsFor(schoolId);const [[row]]=await pool.query(`SELECT s.auto_suggest_templates,s.auto_apply_default_template,s.allow_teachers_to_create_templates,s.require_template_approval,exam.public_ref default_exam_template_ref,test.public_ref default_test_template_ref,quiz.public_ref default_quiz_template_ref,worksheet.public_ref default_worksheet_template_ref,drill.public_ref default_daily_drill_template_ref FROM assessment_template_settings s LEFT JOIN assessment_cover_templates exam ON exam.id=s.default_exam_template_id LEFT JOIN assessment_cover_templates test ON test.id=s.default_test_template_id LEFT JOIN assessment_cover_templates quiz ON quiz.id=s.default_quiz_template_id LEFT JOIN assessment_cover_templates worksheet ON worksheet.id=s.default_worksheet_template_id LEFT JOIN assessment_cover_templates drill ON drill.id=s.default_daily_drill_template_id WHERE s.school_id=?`,[schoolId]);return {settings:{...row,auto_suggest_templates:Boolean(row.auto_suggest_templates),auto_apply_default_template:Boolean(row.auto_apply_default_template),allow_teachers_to_create_templates:Boolean(row.allow_teachers_to_create_templates),require_template_approval:Boolean(row.require_template_approval)}}}
export async function updateAssessmentTemplateSettings(schoolId,user,body={}){if(!leadershipRoles.has(String(user.role)))throw new HttpError(403,"Only school leadership can change assessment template settings");await settingsFor(schoolId);await pool.query(`UPDATE assessment_template_settings SET auto_suggest_templates=COALESCE(?,auto_suggest_templates),auto_apply_default_template=COALESCE(?,auto_apply_default_template),allow_teachers_to_create_templates=COALESCE(?,allow_teachers_to_create_templates),require_template_approval=COALESCE(?,require_template_approval) WHERE school_id=?`,[body.auto_suggest_templates===undefined?null:bool(body.auto_suggest_templates),body.auto_apply_default_template===undefined?null:bool(body.auto_apply_default_template),body.allow_teachers_to_create_templates===undefined?null:bool(body.allow_teachers_to_create_templates),body.require_template_approval===undefined?null:bool(body.require_template_approval),schoolId]);return getAssessmentTemplateSettings(schoolId)}
export async function getAssessmentTemplatePreviewPath(schoolId,ref){const template=await byRef(pool,schoolId,ref);const source=template.preview_image_path||template.thumbnail_image_path;if(!source)throw new HttpError(404,"Template preview is unavailable");const resolved=path.resolve(process.cwd(),source);const uploads=path.resolve(process.cwd(),"uploads");if(!resolved.startsWith(`${uploads}${path.sep}`))throw new HttpError(404,"Template preview is unavailable");return resolved}
