import { parseAssessmentImportDocument } from "./ai/aiClient.js"

export const ASSESSMENT_VISION_PROMPT_VERSION="assessment-vision-v6-tables"
const numberKey=(value)=>String(value||"").toLowerCase().replace(/question|answer|\s|[().]/g,"")
const confidence=(value,fallback=.5)=>Math.max(.05,Math.min(.99,Number(value)||fallback))
const visualInstructions=`Read the attached PDF visually, page by page. Inspect both the printed text layer and the actual page image. Transcribe legible handwritten text, handwritten corrections, annotations, labels, calculations, and answers. Preserve spelling and wording as seen; never invent unreadable content. Mark uncertain handwriting with [unclear] and lower confidence. Preserve question hierarchy, marks, formulas, tables, diagrams, and page numbers. The PDF's printed question references are authoritative: copy each number exactly as printed, including letters, brackets, roman numerals, punctuation, and parent relationships (examples: 2, 2(a), 2(a)(i), 3.b(ii)). Return the full contextual reference for each extracted question. Repeated or apparently incorrect references in the source are intentional source data: preserve duplicates exactly and never silently "correct" a repeated (i) into (ii). Never replace source references with a new sequential numbering system and never use an array position as a question reference. For every semantic table needed to understand or answer a question, return its caption, header row, actual column headings, and every visible data row as structured cell text. Preserve blank cells and the original row/column order. Do not flatten a table into prose, and do not treat answer-line grids or decorative boxes as tables. For every diagram, figure, graph, map, photograph, apparatus drawing, or other visual stimulus needed to answer a question, return its page number and a tight normalized bounding box measured from the page's top-left corner, where x, y, width, and height are decimals from 0 to 1. Also return PDF-point coordinates when reliable. Link it using the exact printed question number. A semantic table already returned in tables should not also be returned as a table image unless it contains essential visual information that cannot be represented by rows and columns. Do not classify answer lines, table borders, decorative rules, or the cover logo as question diagrams. For every question inspect the physical area where a learner is expected to answer. Record whether it uses ruled lines, underscore lines, a completely blank open space, a bordered blank box, a graph grid, or no answer area. Count visible answer lines and estimate the answer area's height in PDF points (A4 page height is about 842 points). Do not infer answer space from marks alone when the original page shows none. Treat extracted PDF text below only as a secondary aid because it can omit handwriting, scanned content, rules, blank regions, and diagrams.`

function withAiDiagnostic(result, label) {
  if (result?.ok) return result
  const reason=String(result?.message||"The configured AI provider did not return a usable response.").replace(/\s+/g," ").slice(0,500)
  const warning=`${label} visual extraction could not complete: ${reason} SmartLink used embedded PDF text as a fallback; scanned or handwritten content may require manual review.`
  result.data=result.data||{}
  result.data.warnings=[warning,...(result.data.warnings||[])]
  return result
}

function studentQuestions(payload={}){return (payload.sections||[]).flatMap((section)=>Array.isArray(section?.questions)?section.questions:[])}
function validateStudentExtraction(payload){const questions=studentQuestions(payload);if(!payload||typeof payload!=="object")throw new Error("Visual analysis did not return an object");if(!questions.length)throw new Error("Visual analysis did not find any questions");for(const [index,question] of questions.entries()){if(!String(question?.questionNumber||"").trim())throw new Error(`Question ${index+1} has no printed reference`);if(!String(question?.questionText||"").trim())throw new Error(`Question ${question.questionNumber} has no text`);if(!(Number(question?.pageStart)>0))throw new Error(`Question ${question.questionNumber} has no source page`);for(const table of question.tables||[]){const rows=table?.rows||table?.cells;if(!Array.isArray(rows)||!rows.every(Array.isArray))throw new Error(`Table linked to question ${question.questionNumber} has invalid rows and columns`)}for(const asset of question.assets||[]){const box=asset?.bboxNormalized||{};if([box.x,box.y,box.width,box.height].some((value)=>!Number.isFinite(Number(value)))||Number(box.width)<=0||Number(box.height)<=0||Number(box.x)<0||Number(box.y)<0||Number(box.x)+Number(box.width)>1.05||Number(box.y)+Number(box.height)>1.05)throw new Error(`Visual linked to question ${question.questionNumber} has invalid page geometry`)}}}
function validateMarkingExtraction(payload){if(!payload||typeof payload!=="object")throw new Error("Marking-scheme analysis did not return an object");if(!Array.isArray(payload.items)||!payload.items.length)throw new Error("Marking-scheme analysis did not find any answer items");for(const [index,item] of payload.items.entries()){if(!String(item?.questionNumber||"").trim())throw new Error(`Marking item ${index+1} has no printed reference`);if(!String(item?.answerText||"").trim())throw new Error(`Marking item ${item.questionNumber} has no answer text`)}}
export function assessmentVisionQuality(payload,type="student_paper"){const records=type==="marking_scheme"?(payload?.items||[]):studentQuestions(payload);if(!records.length)return 0;let earned=0,total=0;for(const record of records){const number=record.questionNumber,totalWeight=type==="marking_scheme"?4:6;total+=totalWeight;earned+=String(number||"").trim()?1:0;earned+=String(type==="marking_scheme"?record.answerText:record.questionText||"").trim()?1:0;earned+=Number(type==="marking_scheme"?record.pageNumber:record.pageStart)>0?1:0;earned+=Number(record.confidence)>=.7?1:0;if(type!=="marking_scheme"){earned+=record.responseSpace&&record.responseSpace.type?1:0;earned+=Array.isArray(record.assets)?1:0}}return Math.round((earned/Math.max(1,total))*100)}

export async function parseStudentPaper({pages,metadata,schoolId,userId,pdfData}) {
  const text=pages.map((page)=>`--- Page ${page.page_number} ---\n${page.text_content}`).join("\n").slice(0,120000)
  const fallback={coverPage:{title:metadata.title||"",schoolName:"",subject:"",className:"",duration:"",totalMarks:"",instructions:[],detectedFields:[],assets:[],confidence:.35},sections:[],warnings:["AI parsing was unavailable. Regex candidates require review."]}
  const result=await parseAssessmentImportDocument({schoolId,userId,fallback,validate:validateStudentExtraction,attachments:pdfData?[{mimeType:"application/pdf",filename:"student-question-paper.pdf",data:pdfData}]:[],prompt:`Prompt version: ${ASSESSMENT_VISION_PROMPT_VERSION}.\n${visualInstructions}\n\nStructure this student assessment paper without shortening any question wording. The first page is the authoritative original cover: describe its editable structure and fields, but do not redesign or replace it. Metadata: ${JSON.stringify(metadata)}\n\nEmbedded text aid:\n${text}`,schemaHint:`Return JSON {coverPage:{title,schoolName,subject,className,duration,totalMarks,instructions:[],detectedFields:[{label,value,type,bbox:{x,y,width,height}}],assets:[],layout:{pageSize,widthPoints,heightPoints,headerStyle,titleAlignment,metadataColumns,candidateFields:[],instructionBlock:{bbox},footerStyle},confidence,handwritingDetected},sections:[{title,instructions,questions:[{tempQuestionId,sequenceIndex,questionNumber,parentQuestionNumber,questionText,marks,pageStart,pageEnd,formulaCandidates:[],assets:[{assetKey,assetType:"diagram|figure|graph|map|photo|apparatus",pageNumber,bboxNormalized:{x,y,width,height},bboxPoints:{x,y,width,height},description,figureLabel,linkedQuestionNumber,confidence}],tables:[{tableId,caption,pageNumber,headerRow,columnHeaders:["Column heading"],rows:[["cell by column"]],confidence}],responseSpace:{type:"ruled_lines|blank_space|blank_box|graph_grid|none",lineCount,heightPoints,pageNumber,startsAfterQuestion,confidence,evidence},confidence,difficulty,detectedTopicText,handwritingDetected,transcriptionNotes}]}],warnings:[]}`})
  result.qualityScore=assessmentVisionQuality(result.data,"student_paper")
  return withAiDiagnostic(result,"Student paper")
}

export async function parseMarkingScheme({pages,metadata,schoolId,userId,pdfData}) {
  const text=pages.map((page)=>`--- Page ${page.page_number} ---\n${page.text_content}`).join("\n").slice(0,120000)
  const result=await parseAssessmentImportDocument({schoolId,userId,fallback:{items:[],warnings:["AI marking-scheme parsing was unavailable."]},validate:validateMarkingExtraction,attachments:pdfData?[{mimeType:"application/pdf",filename:"marking-scheme.pdf",data:pdfData}]:[],prompt:`Prompt version: ${ASSESSMENT_VISION_PROMPT_VERSION}.\n${visualInstructions}\n\nExtract every marking-scheme item and preserve full answer wording, alternative answers, marking points, marks and the exact printed question reference. Do not renumber marking items. Metadata: ${JSON.stringify(metadata)}\n\nEmbedded text aid:\n${text}`,schemaHint:`Return JSON {items:[{tempQuestionId,sequenceIndex,questionNumber,parentQuestionNumber,answerText,markingPoints:[{point,marks}],totalMarks,pageNumber,confidence,handwritingDetected,transcriptionNotes}],warnings:[]}`})
  result.qualityScore=assessmentVisionQuality(result.data,"marking_scheme")
  return withAiDiagnostic(result,"Marking scheme")
}

export function matchQuestionsToMarkingScheme(questions=[],items=[]) {
  const links=[]
  const used=new Set()
  questions.forEach((question)=>{const exact=items.find((item,index)=>!used.has(index)&&numberKey(item.question_number)===numberKey(question.question_number));if(exact){const itemIndex=items.indexOf(exact);used.add(itemIndex);links.push({question,markingItem:exact,matchMethod:"exact_number",confidence:.98})}})
  return links
}

export function normalizeFormulaText(raw="") { return {raw:String(raw),latex:String(raw),displayText:String(raw),assetId:null,confidence:.45} }
export function generateReviewWarnings({questions=[],items=[],links=[],assets=[]}) {const warnings=[];for(const q of questions){if(!String(q.question_number||q.questionNumber||"").trim()||String(q.question_number||q.questionNumber)==="?")warnings.push("A question reference could not be read. Review its original printed number before approval.");if(Number(q.confidence)<.72)warnings.push(`Question ${q.question_number} was extracted with low confidence.`);if(!links.some((l)=>l.question===q))warnings.push(`Question ${q.question_number} has no confidently matched marking-scheme answer.`)}for(const asset of assets){if(asset.asset_type==="formula_image")warnings.push(`Formula image extracted from page ${asset.page_number}; please review.`);if(["diagram","table_image"].includes(asset.asset_type)&&Number(asset.confidence)<.72)warnings.push(`A visual linked to question ${asset.linked_question_number||asset.linked_question_temp_id||"?"} on page ${asset.page_number} needs diagram review.`)}if(!questions.length)warnings.push("The system could not confidently extract questions from this PDF. You can still use the page previews and manually create questions from them.");return warnings}
